import {
  Image as ImageIcon,
  Video,
  FileText,
  Layout,
  Palette,
} from "lucide-react";

export interface Asset {
  id: string;
  name: string;
  type: "image" | "video" | "document" | "template" | "graphic";
  category: string;
  size: string;
  format: string;
  dimensions?: string;
  dateAdded: string;
  addedBy: string;
  tags: string[];
  url?: string;
  thumbnail?: string;
  usageCount?: number;
  aiScore?: number;
}

export interface FolderItem {
  id: string;
  name: string;
  description?: string;
  itemCount: number;
  lastModified: string;
  modifiedBy: string;
  color: string;
  tags?: string[];
  aiOptimized?: boolean;
  subFolders?: FolderItem[];
}

export const assetTypeColors = {
  image: "#4B6BFB",
  video: "#EC4899",
  document: "#10B981",
  template: "#F59E0B",
  graphic: "#8B5CF6",
};

export const assetTypeIcons = {
  image: ImageIcon,
  video: Video,
  document: FileText,
  template: Layout,
  graphic: Palette,
};

export const sampleAssets: Asset[] = [
  {
    id: "1",
    name: "Spring Campaign Hero Banner",
    type: "image",
    category: "Marketing",
    size: "2.4 MB",
    format: "PNG",
    dimensions: "1920x1080",
    dateAdded: "Oct 8, 2025",
    addedBy: "Sarah Chen",
    tags: ["Campaign", "Hero", "Spring"],
    usageCount: 24,
    aiScore: 94,
  },
  {
    id: "2",
    name: "Product Demo Video",
    type: "video",
    category: "Product",
    size: "45.2 MB",
    format: "MP4",
    dimensions: "1920x1080",
    dateAdded: "Oct 7, 2025",
    addedBy: "Mike Johnson",
    tags: ["Demo", "Product", "Tutorial"],
    usageCount: 18,
    aiScore: 91,
  },
  {
    id: "3",
    name: "Q4 Marketing Strategy",
    type: "document",
    category: "Strategy",
    size: "1.8 MB",
    format: "PDF",
    dateAdded: "Oct 6, 2025",
    addedBy: "Anna Martinez",
    tags: ["Strategy", "Q4", "Planning"],
    usageCount: 45,
    aiScore: 88,
  },
  {
    id: "4",
    name: "Email Newsletter Template",
    type: "template",
    category: "Email",
    size: "850 KB",
    format: "HTML",
    dateAdded: "Oct 5, 2025",
    addedBy: "Emma Wilson",
    tags: ["Email", "Newsletter", "Template"],
    usageCount: 67,
    aiScore: 92,
  },
  {
    id: "5",
    name: "Brand Icons Set",
    type: "graphic",
    category: "Branding",
    size: "1.2 MB",
    format: "SVG",
    dateAdded: "Oct 4, 2025",
    addedBy: "David Lee",
    tags: ["Icons", "Brand", "UI"],
    usageCount: 156,
    aiScore: 96,
  },
  {
    id: "6",
    name: "Social Media Post Templates",
    type: "template",
    category: "Social",
    size: "3.5 MB",
    format: "PSD",
    dateAdded: "Oct 3, 2025",
    addedBy: "Sarah Chen",
    tags: ["Social", "Templates", "Design"],
    usageCount: 89,
    aiScore: 90,
  },
  {
    id: "7",
    name: "Customer Testimonial Video",
    type: "video",
    category: "Marketing",
    size: "67.8 MB",
    format: "MP4",
    dimensions: "1920x1080",
    dateAdded: "Oct 2, 2025",
    addedBy: "Mike Johnson",
    tags: ["Testimonial", "Customer", "Video"],
    usageCount: 34,
    aiScore: 87,
  },
  {
    id: "8",
    name: "Product Photography Set",
    type: "image",
    category: "Product",
    size: "15.6 MB",
    format: "JPG",
    dimensions: "3840x2160",
    dateAdded: "Oct 1, 2025",
    addedBy: "Emma Wilson",
    tags: ["Product", "Photography", "Catalog"],
    usageCount: 123,
    aiScore: 95,
  },
  {
    id: "9",
    name: "Brand Guidelines 2025",
    type: "document",
    category: "Branding",
    size: "4.2 MB",
    format: "PDF",
    dateAdded: "Sep 30, 2025",
    addedBy: "Anna Martinez",
    tags: ["Brand", "Guidelines", "Standards"],
    usageCount: 201,
    aiScore: 98,
  },
  {
    id: "10",
    name: "Landing Page Template",
    type: "template",
    category: "Web",
    size: "2.1 MB",
    format: "HTML",
    dateAdded: "Sep 28, 2025",
    addedBy: "David Lee",
    tags: ["Landing", "Web", "Template"],
    usageCount: 56,
    aiScore: 89,
  },
  {
    id: "11",
    name: "Infographic: User Journey",
    type: "graphic",
    category: "Marketing",
    size: "1.9 MB",
    format: "AI",
    dateAdded: "Sep 27, 2025",
    addedBy: "Sarah Chen",
    tags: ["Infographic", "UX", "Journey"],
    usageCount: 42,
    aiScore: 93,
  },
  {
    id: "12",
    name: "Company Overview Presentation",
    type: "document",
    category: "Presentation",
    size: "8.4 MB",
    format: "PPTX",
    dateAdded: "Sep 25, 2025",
    addedBy: "Anna Martinez",
    tags: ["Presentation", "Overview", "Company"],
    usageCount: 78,
    aiScore: 91,
  },
];

export const mainFolders: FolderItem[] = [
  {
    id: "templates-folder",
    name: "Templates",
    description: "All template files and designs",
    itemCount: 124,
    lastModified: "Oct 10, 2025",
    modifiedBy: "Sarah Chen",
    color: "#F59E0B",
    tags: ["Templates", "Design"],
    aiOptimized: true,
    subFolders: [
      {
        id: "social-media-template",
        name: "Social Media Template",
        description: "Ready-to-use templates for social media platforms",
        itemCount: 48,
        lastModified: "Oct 9, 2025",
        modifiedBy: "Sarah Chen",
        color: "#4B6BFB",
        tags: ["Social", "Templates"],
        aiOptimized: true,
      },
      {
        id: "email-templates",
        name: "Email Templates",
        description: "Newsletter and email campaign templates",
        itemCount: 24,
        lastModified: "Oct 8, 2025",
        modifiedBy: "Emma Wilson",
        color: "#10B981",
        tags: ["Email", "Marketing"],
        aiOptimized: true,
      },
      {
        id: "presentation-decks",
        name: "Presentation Decks",
        description: "Pitch decks and presentation templates",
        itemCount: 28,
        lastModified: "Oct 7, 2025",
        modifiedBy: "Mike Johnson",
        color: "#8B5CF6",
        tags: ["Presentations", "Sales"],
      },
      {
        id: "marketing-collateral",
        name: "Marketing Collateral",
        description: "Brochures, flyers, and promotional materials",
        itemCount: 24,
        lastModified: "Oct 6, 2025",
        modifiedBy: "Anna Martinez",
        color: "#EC4899",
        tags: ["Marketing", "Print"],
        aiOptimized: true,
      },
    ],
  },
  {
    id: "documents-folder",
    name: "Documents",
    description: "Document files and resources",
    itemCount: 86,
    lastModified: "Oct 9, 2025",
    modifiedBy: "Anna Martinez",
    color: "#10B981",
    tags: ["Documents", "Files"],
    aiOptimized: true,
    subFolders: [
      {
        id: "brand-guidelines",
        name: "Brand Guidelines",
        description: "Brand standards and guidelines",
        itemCount: 15,
        lastModified: "Oct 9, 2025",
        modifiedBy: "Anna Martinez",
        color: "#4B6BFB",
        tags: ["Brand", "Standards"],
        aiOptimized: true,
      },
      {
        id: "strategy-docs",
        name: "Strategy Documents",
        description: "Marketing and business strategy documents",
        itemCount: 28,
        lastModified: "Oct 8, 2025",
        modifiedBy: "Sarah Chen",
        color: "#F59E0B",
        tags: ["Strategy", "Planning"],
      },
      {
        id: "presentations",
        name: "Presentations",
        description: "Company and product presentations",
        itemCount: 23,
        lastModified: "Oct 7, 2025",
        modifiedBy: "Mike Johnson",
        color: "#8B5CF6",
        tags: ["Presentations", "Decks"],
      },
      {
        id: "reports",
        name: "Reports",
        description: "Performance and analytics reports",
        itemCount: 20,
        lastModified: "Oct 6, 2025",
        modifiedBy: "Emma Wilson",
        color: "#EC4899",
        tags: ["Reports", "Analytics"],
      },
    ],
  },
  {
    id: "videos-folder",
    name: "Videos",
    description: "Video files and media content",
    itemCount: 156,
    lastModified: "Oct 11, 2025",
    modifiedBy: "Mike Johnson",
    color: "#EC4899",
    tags: ["Videos", "Media"],
    aiOptimized: true,
    subFolders: [
      {
        id: "product-videos",
        name: "Product Videos",
        description: "Product demos and promotional videos",
        itemCount: 45,
        lastModified: "Oct 11, 2025",
        modifiedBy: "Mike Johnson",
        color: "#4B6BFB",
        tags: ["Product", "Demo"],
        aiOptimized: true,
      },
      {
        id: "campaign-videos",
        name: "Campaign Videos",
        description: "Marketing campaign video content",
        itemCount: 38,
        lastModified: "Oct 10, 2025",
        modifiedBy: "Sarah Chen",
        color: "#10B981",
        tags: ["Campaign", "Marketing"],
        aiOptimized: true,
      },
      {
        id: "testimonials",
        name: "Customer Testimonials",
        description: "Customer testimonial and review videos",
        itemCount: 26,
        lastModified: "Oct 9, 2025",
        modifiedBy: "Emma Wilson",
        color: "#F59E0B",
        tags: ["Testimonials", "Reviews"],
      },
      {
        id: "video-source",
        name: "Video Source Files",
        description: "Raw video footage and source files",
        itemCount: 47,
        lastModified: "Oct 8, 2025",
        modifiedBy: "David Lee",
        color: "#8B5CF6",
        tags: ["Source", "Raw"],
      },
    ],
  },
  {
    id: "images-folder",
    name: "Images",
    description: "Image files and photography",
    itemCount: 312,
    lastModified: "Oct 12, 2025",
    modifiedBy: "David Lee",
    color: "#4B6BFB",
    tags: ["Images", "Photography"],
    aiOptimized: true,
    subFolders: [
      {
        id: "product-images",
        name: "Product Images",
        description: "High-resolution product photography",
        itemCount: 156,
        lastModified: "Oct 12, 2025",
        modifiedBy: "David Lee",
        color: "#4B6BFB",
        tags: ["Product", "Photography"],
        aiOptimized: true,
      },
      {
        id: "campaign-images",
        name: "Campaign Images",
        description: "Marketing campaign imagery and graphics",
        itemCount: 89,
        lastModified: "Oct 11, 2025",
        modifiedBy: "Sarah Chen",
        color: "#10B981",
        tags: ["Campaign", "Graphics"],
        aiOptimized: true,
      },
      {
        id: "brand-assets",
        name: "Brand Assets",
        description: "Logos, icons, and brand imagery",
        itemCount: 45,
        lastModified: "Oct 10, 2025",
        modifiedBy: "Anna Martinez",
        color: "#F59E0B",
        tags: ["Brand", "Assets"],
      },
      {
        id: "stock-photos",
        name: "Stock Photos",
        description: "Licensed stock photography",
        itemCount: 22,
        lastModified: "Oct 9, 2025",
        modifiedBy: "Emma Wilson",
        color: "#EC4899",
        tags: ["Stock", "Photos"],
      },
    ],
  },
  {
    id: "campaign-assets",
    name: "Campaign Assets",
    description: "Marketing campaigns and promotional materials",
    itemCount: 245,
    lastModified: "Oct 13, 2025",
    modifiedBy: "Sarah Chen",
    color: "#8B5CF6",
    tags: ["Marketing", "Campaigns"],
    aiOptimized: true,
    subFolders: [
      {
        id: "spring-campaign",
        name: "Spring Campaign 2025",
        description: "Spring season marketing materials",
        itemCount: 56,
        lastModified: "Oct 13, 2025",
        modifiedBy: "Sarah Chen",
        color: "#10B981",
        tags: ["Spring", "Campaign"],
        aiOptimized: true,
      },
      {
        id: "holiday-campaign",
        name: "Holiday Campaign",
        description: "Holiday season promotional assets",
        itemCount: 78,
        lastModified: "Oct 12, 2025",
        modifiedBy: "Emma Wilson",
        color: "#F59E0B",
        tags: ["Holiday", "Campaign"],
      },
      {
        id: "product-launch",
        name: "Product Launch Campaign",
        description: "New product launch materials",
        itemCount: 45,
        lastModified: "Oct 11, 2025",
        modifiedBy: "Mike Johnson",
        color: "#4B6BFB",
        tags: ["Launch", "Product"],
        aiOptimized: true,
      },
      {
        id: "social-media-campaign",
        name: "Social Media Campaigns",
        description: "Social media marketing assets",
        itemCount: 66,
        lastModified: "Oct 10, 2025",
        modifiedBy: "Anna Martinez",
        color: "#06B6D4",
        tags: ["Social", "Digital"],
      },
    ],
  },
  {
    id: "brand-hub",
    name: "Brand Hub",
    description: "Brand identity and design system assets",
    itemCount: 186,
    lastModified: "Oct 10, 2025",
    modifiedBy: "Anna Martinez",
    color: "#06B6D4",
    tags: ["Brand", "Identity"],
    aiOptimized: true,
    subFolders: [
      {
        id: "logos",
        name: "Logos & Brand Marks",
        description: "Official logos and brand marks",
        itemCount: 28,
        lastModified: "Oct 10, 2025",
        modifiedBy: "Anna Martinez",
        color: "#4B6BFB",
        tags: ["Logos", "Brand"],
        aiOptimized: true,
      },
      {
        id: "color-palettes",
        name: "Color Palettes",
        description: "Brand color schemes and palettes",
        itemCount: 15,
        lastModified: "Oct 9, 2025",
        modifiedBy: "David Lee",
        color: "#EC4899",
        tags: ["Colors", "Brand"],
      },
      {
        id: "typography",
        name: "Typography",
        description: "Brand fonts and typography assets",
        itemCount: 12,
        lastModified: "Oct 8, 2025",
        modifiedBy: "Sarah Chen",
        color: "#10B981",
        tags: ["Fonts", "Typography"],
      },
      {
        id: "icons-illustrations",
        name: "Icons & Illustrations",
        description: "Vector icons and brand illustrations",
        itemCount: 66,
        lastModified: "Oct 7, 2025",
        modifiedBy: "Emma Wilson",
        color: "#F59E0B",
        tags: ["Design", "UI"],
      },
      {
        id: "brand-templates",
        name: "Brand Templates",
        description: "Branded design templates",
        itemCount: 65,
        lastModified: "Oct 6, 2025",
        modifiedBy: "Mike Johnson",
        color: "#8B5CF6",
        tags: ["Templates", "Brand"],
        aiOptimized: true,
      },
    ],
  },
  {
    id: "product-assets",
    name: "Product Assets",
    description: "Product photography and media files",
    itemCount: 312,
    lastModified: "Oct 14, 2025",
    modifiedBy: "David Lee",
    color: "#14B8A6",
    tags: ["Product", "Media"],
    aiOptimized: true,
    subFolders: [
      {
        id: "product-photography",
        name: "Product Photography",
        description: "High-resolution product photos",
        itemCount: 156,
        lastModified: "Oct 14, 2025",
        modifiedBy: "David Lee",
        color: "#4B6BFB",
        tags: ["Photography", "Product"],
        aiOptimized: true,
      },
      {
        id: "lifestyle-shots",
        name: "Lifestyle Shots",
        description: "Products in lifestyle contexts",
        itemCount: 67,
        lastModified: "Oct 13, 2025",
        modifiedBy: "Emma Wilson",
        color: "#EC4899",
        tags: ["Lifestyle", "Product"],
      },
      {
        id: "360-views",
        name: "360° Product Views",
        description: "Interactive 360-degree product views",
        itemCount: 34,
        lastModified: "Oct 12, 2025",
        modifiedBy: "Mike Johnson",
        color: "#10B981",
        tags: ["360", "Interactive"],
      },
      {
        id: "product-demos",
        name: "Product Demo Videos",
        description: "Product demonstration videos",
        itemCount: 55,
        lastModified: "Oct 11, 2025",
        modifiedBy: "Sarah Chen",
        color: "#F59E0B",
        tags: ["Demo", "Videos"],
        aiOptimized: true,
      },
    ],
  },
];
