import { Card } from "../../ui/card";
import { motion } from "motion/react";
import { Button } from "../../ui/button";
import { Input } from "../../ui/input";
import { Label } from "../../ui/label";
import { Textarea } from "../../ui/textarea";
import { Edit2, Save, Plus, Trash2 } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../../ui/select";
import { useState, useEffect } from "react";
import type { BrandTypography } from "../../../lib/supabase/marketing/brands";

interface Typography {
  headings: BrandTypography[];
  body: BrandTypography[];
}

interface TypographySectionProps {
  typography: Typography;
  fontStack?: string;
  isEditing?: boolean;
  onEdit?: () => void;
  onSave?: () => void;
  onCancel?: () => void;
  onChange?: (typography: Typography) => void;
  onFontStackChange?: (fontStack: string) => void;
}

// Common web fonts
const WEB_FONTS = [
  { value: "system", label: "System Fonts", fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif" },
  { value: "arial", label: "Arial", fontFamily: "Arial, sans-serif" },
  { value: "helvetica", label: "Helvetica", fontFamily: "Helvetica, Arial, sans-serif" },
  { value: "times", label: "Times New Roman", fontFamily: "'Times New Roman', Times, serif" },
  { value: "georgia", label: "Georgia", fontFamily: "Georgia, serif" },
  { value: "verdana", label: "Verdana", fontFamily: "Verdana, sans-serif" },
  { value: "courier", label: "Courier New", fontFamily: "'Courier New', Courier, monospace" },
  { value: "roboto", label: "Roboto", fontFamily: "'Roboto', sans-serif" },
  { value: "open-sans", label: "Open Sans", fontFamily: "'Open Sans', sans-serif" },
  { value: "lato", label: "Lato", fontFamily: "'Lato', sans-serif" },
  { value: "montserrat", label: "Montserrat", fontFamily: "'Montserrat', sans-serif" },
  { value: "raleway", label: "Raleway", fontFamily: "'Raleway', sans-serif" },
  { value: "playfair", label: "Playfair Display", fontFamily: "'Playfair Display', serif" },
  { value: "poppins", label: "Poppins", fontFamily: "'Poppins', sans-serif" },
  { value: "inter", label: "Inter", fontFamily: "'Inter', sans-serif" },
  { value: "custom", label: "Custom Font (URL)", fontFamily: "" },
];

export function TypographySection({
  typography,
  fontStack = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  isEditing = false,
  onEdit,
  onSave,
  onCancel,
  onChange,
  onFontStackChange,
}: TypographySectionProps) {
  const [localFontStack, setLocalFontStack] = useState(fontStack);
  const [isEditingFontStack, setIsEditingFontStack] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(true);
  const [manualFontStack, setManualFontStack] = useState<string | null>(null);

  // Track loaded fonts
  const [loadedFonts, setLoadedFonts] = useState<Set<string>>(new Set());

  // Helper function to get font family from typography type
  const getFontFamily = (type: BrandTypography): string => {
    const fontUrl = type.usage || "";
    
    // If usage contains a URL, it's a custom font
    if (fontUrl && fontUrl.startsWith("http")) {
      // Extract font name from URL or use a generic name
      // For Google Fonts: https://fonts.googleapis.com/css2?family=FontName
      const match = fontUrl.match(/family=([^:&]+)/);
      if (match) {
        return `'${match[1].replace(/\+/g, ' ')}', sans-serif`;
      }
      return "sans-serif"; // Fallback
    }
    
    // If usage contains a font name, use it
    if (fontUrl && !fontUrl.startsWith("http")) {
      const font = WEB_FONTS.find(f => f.value === fontUrl || f.label.toLowerCase() === fontUrl.toLowerCase());
      return font ? font.fontFamily : fontUrl;
    }
    
    // Default to system fonts
    return WEB_FONTS[0].fontFamily;
  };

  // Auto-generate font stack from typography settings
  const generateFontStack = (): string => {
    const fonts = new Set<string>();
    
    // Collect all fonts from headings and body
    [...typography.headings, ...typography.body].forEach(type => {
      const fontFamily = getFontFamily(type);
      
      // Extract font names from font-family string
      // Match patterns like 'Font Name' or Font Name
      const fontMatches = fontFamily.match(/'([^']+)'/g) || 
                         fontFamily.match(/([A-Za-z][A-Za-z\s]+?)(?=,\s*(?:sans-serif|serif|monospace|$))/g);
      
      if (fontMatches) {
        fontMatches.forEach(match => {
          // Clean up the font name
          const cleanName = match.replace(/['"]/g, '').trim();
          // Exclude generic font families
          if (cleanName && 
              !cleanName.toLowerCase().includes('sans-serif') && 
              !cleanName.toLowerCase().includes('serif') &&
              !cleanName.toLowerCase().includes('monospace') &&
              !cleanName.toLowerCase().includes('cursive') &&
              !cleanName.toLowerCase().includes('fantasy')) {
            fonts.add(cleanName);
          }
        });
      }
    });
    
    // Build font stack with fallbacks
    const fontArray = Array.from(fonts);
    if (fontArray.length > 0) {
      // Add system fonts as fallback
      return fontArray.map(f => `'${f}'`).join(', ') + ', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';
    }
    
    // Default fallback if no fonts found
    return "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";
  };

  // Get the current font stack (auto-generated or manual)
  const getCurrentFontStack = (): string => {
    if (!isAutoGenerated && manualFontStack) {
      return manualFontStack;
    }
    return generateFontStack();
  };

  // Load Google Fonts when needed
  useEffect(() => {
    const fontsToLoad = new Set<string>();
    
    [...typography.headings, ...typography.body].forEach((type) => {
      const fontUrl = type.usage || "";
      if (fontUrl && fontUrl.startsWith("http") && !loadedFonts.has(fontUrl)) {
        fontsToLoad.add(fontUrl);
      }
    });

    fontsToLoad.forEach((url) => {
      const link = document.createElement("link");
      link.rel = "stylesheet";
      link.href = url;
      document.head.appendChild(link);
      setLoadedFonts((prev) => new Set([...prev, url]));
    });
  }, [typography, loadedFonts]);

  // Update local font stack when typography changes (if auto-generated)
  useEffect(() => {
    if (isAutoGenerated) {
      const autoGenerated = generateFontStack();
      setLocalFontStack(autoGenerated);
      if (onFontStackChange) {
        onFontStackChange(autoGenerated);
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [typography, isAutoGenerated]);

  // Initialize font stack on mount
  useEffect(() => {
    if (fontStack && !manualFontStack) {
      // Check if the provided fontStack matches auto-generated
      const autoGenerated = generateFontStack();
      if (fontStack === autoGenerated) {
        setIsAutoGenerated(true);
        setLocalFontStack(autoGenerated);
      } else {
        setIsAutoGenerated(false);
        setManualFontStack(fontStack);
        setLocalFontStack(fontStack);
      }
    } else if (!fontStack) {
      // No font stack provided, use auto-generated
      const autoGenerated = generateFontStack();
      setLocalFontStack(autoGenerated);
      setIsAutoGenerated(true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const addTypography = (category: "headings" | "body") => {
    if (!onChange) return;
    const newType: BrandTypography = {
      id: Date.now(),
      name: "New Typography",
      size: "16px",
      weight: "400",
      lineHeight: "1.5",
      category,
      usage: "system", // Default to system fonts
      sortOrder: typography[category].length,
    };
    onChange({
      ...typography,
      [category]: [...typography[category], newType],
    });
  };

  const removeTypography = (category: "headings" | "body", index: number) => {
    if (!onChange) return;
    onChange({
      ...typography,
      [category]: typography[category].filter((_, i) => i !== index),
    });
  };

  const updateTypography = (category: "headings" | "body", index: number, updates: Partial<BrandTypography>) => {
    if (!onChange) return;
    const updated = [...typography[category]];
    updated[index] = { ...updated[index], ...updates };
    onChange({
      ...typography,
      [category]: updated,
    });
  };

  const renderTypographyItem = (type: BrandTypography, index: number, category: "headings" | "body") => {
    const fontFamily = getFontFamily(type);
    const isCustomUrl = type.usage && type.usage.startsWith("http");
    // Check if usage is "custom" or if it's a URL (custom font), or if it's empty (just selected custom)
    // If usage is empty string, it means custom was just selected
    const selectedFont = isCustomUrl ? "custom" : (type.usage === "" ? "custom" : (type.usage || "system"));
    const showCustomUrlInput = selectedFont === "custom";

    if (isEditing) {
      return (
        <Card className="p-6 border-glass-border bg-glass-bg/30 backdrop-blur-sm">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <div>
                <Label className="text-xs opacity-60">Name</Label>
                <Input
                  value={type.name}
                  onChange={(e) => updateTypography(category, index, { name: e.target.value })}
                  className="mt-1"
                />
              </div>
              <div>
                <Label className="text-xs opacity-60">Font</Label>
                <Select
                  value={selectedFont}
                  onValueChange={(value) => {
                    if (value === "custom") {
                      // When custom is selected, set usage to empty string to show URL input
                      updateTypography(category, index, { usage: "" });
                    } else {
                      const font = WEB_FONTS.find(f => f.value === value);
                      updateTypography(category, index, { usage: font ? font.value : value });
                    }
                  }}
                >
                  <SelectTrigger className="mt-1">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {WEB_FONTS.map((font) => (
                      <SelectItem key={font.value} value={font.value}>
                        {font.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              {showCustomUrlInput && (
                <div>
                  <Label className="text-xs opacity-60">Font URL (Google Fonts, etc.)</Label>
                  <Input
                    value={type.usage || ""}
                    onChange={(e) => updateTypography(category, index, { usage: e.target.value })}
                    className="mt-1"
                    placeholder="https://fonts.googleapis.com/css2?family=FontName"
                  />
                  <p className="text-xs opacity-50 mt-1">
                    Enter a Google Fonts URL or custom font stylesheet URL
                  </p>
                </div>
              )}
              <div>
                <Label className="text-xs opacity-60">Size</Label>
                <Input
                  value={type.size}
                  onChange={(e) => updateTypography(category, index, { size: e.target.value })}
                  className="mt-1"
                  placeholder="e.g., 24px, 1.5rem"
                />
              </div>
              <div>
                <Label className="text-xs opacity-60">Weight</Label>
                <Input
                  value={type.weight}
                  onChange={(e) => updateTypography(category, index, { weight: e.target.value })}
                  className="mt-1"
                  placeholder="e.g., 400, 600, bold"
                />
              </div>
              <div>
                <Label className="text-xs opacity-60">Line Height</Label>
                <Input
                  value={type.lineHeight}
                  onChange={(e) => updateTypography(category, index, { lineHeight: e.target.value })}
                  className="mt-1"
                  placeholder="e.g., 1.5, 24px"
                />
              </div>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => removeTypography(category, index)}
                className="w-full text-red-600 hover:text-red-700"
              >
                <Trash2 className="w-4 h-4 mr-2" />
                Remove
              </Button>
            </div>
            <div className="flex items-center justify-center p-6 bg-accent/10 rounded-lg">
              <div
                style={{
                  fontFamily: fontFamily,
                  fontSize: type.size,
                  fontWeight: type.weight,
                  lineHeight: type.lineHeight,
                }}
              >
                {category === "headings" ? "The quick brown fox" : "The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs."}
              </div>
            </div>
          </div>
        </Card>
      );
    }

    return (
      <motion.div
        key={type.id || type.name}
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: index * 0.05 }}
        className="pb-6 border-b border-glass-border last:border-b-0 last:pb-0"
      >
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
          <div>
            <div
              style={{
                fontFamily: fontFamily,
                fontSize: type.size,
                fontWeight: type.weight,
                lineHeight: type.lineHeight,
              }}
            >
              {category === "headings" ? "The quick brown fox" : "The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs."}
            </div>
          </div>
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="opacity-60">Type:</span>
              <span>{type.name}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="opacity-60">Font:</span>
              <span className="text-sm">
                {isCustomUrl ? "Custom Font" : WEB_FONTS.find(f => f.value === type.usage)?.label || type.usage || "System Fonts"}
              </span>
            </div>
            <div className="flex items-center justify-between">
              <span className="opacity-60">Size:</span>
              <span>{type.size}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="opacity-60">Weight:</span>
              <span>{type.weight}</span>
            </div>
            {type.usage && !isCustomUrl && (
              <div className="flex items-center justify-between">
                <span className="opacity-60">Usage:</span>
                <span className="text-sm">{type.usage}</span>
              </div>
            )}
          </div>
        </div>
      </motion.div>
    );
  };

  return (
    <div className="space-y-6">
      {/* Edit/Save Button */}
      {onEdit && onSave && onCancel && (
        <div className="flex justify-end">
          {!isEditing ? (
            <Button 
              onClick={onEdit}
              className="gap-2 bg-[#4B6BFB] hover:bg-[#3A5BEB]"
            >
              <Edit2 className="w-4 h-4" />
              Edit Typography
            </Button>
          ) : (
            <div className="flex gap-2">
              <Button 
                variant="outline"
                onClick={onCancel}
              >
                Cancel
              </Button>
              <Button 
                onClick={onSave}
                className="gap-2 bg-[#4B6BFB] hover:bg-[#3A5BEB]"
              >
                <Save className="w-4 h-4" />
                Save Changes
              </Button>
            </div>
          )}
        </div>
      )}

      {/* Headings */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <h3>Headings</h3>
          {isEditing && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => addTypography("headings")}
              className="gap-2"
            >
              <Plus className="w-4 h-4" />
              Add Typography
            </Button>
          )}
        </div>
        <Card className="p-6 border-glass-border bg-glass-bg/30 backdrop-blur-sm">
          <div className="space-y-6">
            {typography.headings.length === 0 && !isEditing ? (
              <p className="opacity-60 text-center py-8">No heading typography defined</p>
            ) : (
              typography.headings.map((type, index) => renderTypographyItem(type, index, "headings"))
            )}
          </div>
        </Card>
      </div>

      {/* Body Text */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <h3>Body Text</h3>
          {isEditing && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => addTypography("body")}
              className="gap-2"
            >
              <Plus className="w-4 h-4" />
              Add Typography
            </Button>
          )}
        </div>
        <Card className="p-6 border-glass-border bg-glass-bg/30 backdrop-blur-sm">
          <div className="space-y-6">
            {typography.body.length === 0 && !isEditing ? (
              <p className="opacity-60 text-center py-8">No body typography defined</p>
            ) : (
              typography.body.map((type, index) => renderTypographyItem(type, index, "body"))
            )}
          </div>
        </Card>
      </div>

      {/* Font Stack */}
      <Card className="p-6 border-glass-border bg-glass-bg/30 backdrop-blur-sm">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <h3>Font Stack</h3>
            {isAutoGenerated && (
              <span className="text-xs px-2 py-1 rounded bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300">
                Auto-generated
              </span>
            )}
          </div>
          {isEditing && (
            <div className="flex gap-2">
              {!isAutoGenerated && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    const autoGenerated = generateFontStack();
                    setLocalFontStack(autoGenerated);
                    setManualFontStack(null);
                    setIsAutoGenerated(true);
                    if (onFontStackChange) {
                      onFontStackChange(autoGenerated);
                    }
                  }}
                  className="gap-2 text-xs"
                >
                  Reset to Auto
                </Button>
              )}
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setIsEditingFontStack(!isEditingFontStack)}
                className="gap-2"
              >
                <Edit2 className="w-4 h-4" />
                {isEditingFontStack ? "Done" : "Edit"}
              </Button>
            </div>
          )}
        </div>
        {isEditing && isEditingFontStack ? (
          <div className="space-y-3">
            <div>
              <Label className="text-xs opacity-60 mb-2 block">
                {isAutoGenerated ? "Override auto-generated font stack" : "Font Stack"}
              </Label>
              <Textarea
                value={localFontStack}
                onChange={(e) => setLocalFontStack(e.target.value)}
                className="font-mono text-sm"
                rows={3}
                placeholder="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;"
              />
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  setLocalFontStack(getCurrentFontStack());
                  setIsEditingFontStack(false);
                }}
              >
                Cancel
              </Button>
              <Button
                size="sm"
                onClick={() => {
                  setManualFontStack(localFontStack);
                  setIsAutoGenerated(false);
                  if (onFontStackChange) {
                    onFontStackChange(localFontStack);
                  }
                  setIsEditingFontStack(false);
                }}
                className="bg-[#4B6BFB] hover:bg-[#3A5BEB]"
              >
                Save
              </Button>
            </div>
          </div>
        ) : (
          <>
            <div className="p-4 rounded-lg bg-accent/30 font-mono text-sm">
              font-family: {getCurrentFontStack()};
            </div>
            <p className="mt-4 opacity-60">
              {isAutoGenerated 
                ? "Auto-generated from typography settings above. Edit to override."
                : "Manually configured font stack. Click 'Reset to Auto' to regenerate from typography settings."}
            </p>
          </>
        )}
      </Card>
    </div>
  );
}
