/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Updated project ID: cltiumpfpllawsvvbrqg
export const projectId = "cltiumpfpllawsvvbrqg"
// NOTE: You need to update the publicAnonKey from your Supabase dashboard
// Go to: Project Settings > API > anon/public key
export const publicAnonKey = "YOUR_ANON_KEY_HERE"