import {
  Sparkles,
  Zap,
  Target,
  BarChart3,
} from "lucide-react";
import { Agent, Task } from "../types";

export const agents: Agent[] = [
  {
    id: "task-assistant",
    name: "Task Assistant",
    icon: Sparkles,
    color: "#4B6BFB",
    gradient: "from-[#4B6BFB] to-[#6B8AFF]",
    description: "Your intelligent task companion. I can help you complete tasks, break them down into steps, and provide guidance.",
  },
  {
    id: "productivity",
    name: "Productivity Coach",
    icon: Zap,
    color: "#10B981",
    gradient: "from-[#10B981] to-[#34D399]",
    description: "Boost your productivity with smart suggestions, time management tips, and workflow optimization.",
  },
  {
    id: "planning",
    name: "Planning Agent",
    icon: Target,
    color: "#F59E0B",
    gradient: "from-[#F59E0B] to-[#FBBF24]",
    description: "Strategic planning and prioritization expert. I help you organize and plan your work effectively.",
  },
  {
    id: "analysis",
    name: "Analytics Agent",
    icon: BarChart3,
    color: "#8B5CF6",
    gradient: "from-[#8B5CF6] to-[#A78BFA]",
    description: "Analyze your task patterns, provide insights, and help optimize your workflow.",
  },
];

export const todayTasks: Task[] = [
  {
    id: "1",
    title: "Complete Q4 Marketing Report",
    description: "Analyze campaign performance and prepare comprehensive report for stakeholders",
    dueDate: "Today, 3:00 PM",
    priority: "High",
    status: "In Progress",
    assignee: "You",
    project: "Marketing Campaign",
    progress: 65,
    tags: ["Report", "Marketing"],
  },
  {
    id: "2",
    title: "Review Product Launch Strategy",
    description: "Final review of product launch materials and timeline",
    dueDate: "Today, 5:00 PM",
    priority: "High",
    status: "Todo",
    assignee: "You",
    project: "Product Launch",
    progress: 0,
    tags: ["Strategy", "Product"],
  },
  {
    id: "3",
    title: "Update Customer Database",
    description: "Import new customer data and verify contact information",
    dueDate: "Today, 6:00 PM",
    priority: "Medium",
    status: "Todo",
    assignee: "You",
    project: "CRM Updates",
    progress: 0,
    tags: ["Data", "CRM"],
  },
  {
    id: "4",
    title: "Prepare Team Meeting Agenda",
    description: "Create agenda for tomorrow's team sync meeting",
    dueDate: "Today, 7:00 PM",
    priority: "Medium",
    status: "Todo",
    assignee: "You",
    project: "Team Management",
    progress: 0,
    tags: ["Meeting", "Planning"],
  },
  {
    id: "5",
    title: "Review Design Mockups",
    description: "Provide feedback on new website design mockups",
    dueDate: "Today, 8:00 PM",
    priority: "Low",
    status: "Review",
    assignee: "You",
    project: "Website Redesign",
    progress: 80,
    tags: ["Design", "Review"],
  },
];
