/**
 * Promotion Data
 * 
 * NOTE: This file is kept for backward compatibility during migration.
 * Eventually, all data should come from Supabase queries via the mappers.
 * 
 * Updated to match new Promotion interface:
 * - Use database types: 'fixed_amount', 'buy_x_get_y', 'buy_more_get_more', 'free_shipping'
 * - Use Date objects for dates
 */

import { Promotion } from "../../../../types/modules/marketing";

// Re-export the Promotion type from the centralized types
export type { Promotion };

// Color constants for promotion types (matching database types)
export const promotionTypeColors = {
  percentage: "#4B6BFB",
  fixed_amount: "#10B981", // Updated from 'value'
  buy_x_get_y: "#F59E0B", // Updated from 'bogo'
  free_shipping: "#8B5CF6", // Updated from 'free-items'
  buy_more_get_more: "#EC4899", // Updated from 'bmgm'
} as const;

// Label constants for promotion types (matching database types)
export const promotionTypeLabels = {
  percentage: "Percentage Off",
  fixed_amount: "Fixed Amount Off", // Updated from 'Value Off'
  buy_x_get_y: "Buy X Get Y (BOGO)", // Updated from 'Buy One Get One (BOGO)'
  free_shipping: "Free Shipping", // Updated from 'Free Items'
  buy_more_get_more: "Buy More Get More (BMGM)",
} as const;

// Sample Promotions Data
export const samplePromotions: Promotion[] = [
  {
    id: "1",
    name: "Fall Flash Sale",
    code: "FALL2025",
    type: "percentage",
    value: "25%",
    status: "active",
    startDate: "Oct 10",
    endDate: "Oct 20",
    redemptions: 3547,
    redemptionLimit: 5000,
    revenue: "$124,890",
    discount: "$41,630",
    channels: ["Email", "Social", "Website"],
    performance: 71,
    conversionRate: "8.2%",
    aiScore: 94,
    targetAudience: "Returning customers",
    isActive: true,
    products: ["Diamond Ring #1234", "Gold Necklace #5678"],
    categories: ["Jewelry", "Rings"],
    attributes: ["14K Gold", "Natural Diamond"],
    campaigns: ["Fall Collection 2025"],
    percentageValue: 25,
  },
  {
    id: "2",
    name: "New Customer Welcome",
    code: "WELCOME15",
    type: "percentage",
    value: "15%",
    status: "active",
    startDate: "Oct 1",
    endDate: "Dec 31",
    redemptions: 1248,
    revenue: "$42,340",
    discount: "$7,480",
    channels: ["Email", "Website"],
    performance: 62,
    conversionRate: "12.4%",
    aiScore: 88,
    targetAudience: "New customers",
    isActive: true,
    categories: ["All Products"],
    campaigns: ["Customer Acquisition Q4"],
    percentageValue: 15,
  },
  {
    id: "3",
    name: "Free Shipping October",
    code: "FREESHIP",
    type: "free_shipping", // Updated from 'free-items'
    value: "Free",
    status: "active",
    startDate: new Date("2024-10-01"), // Updated to Date object
    endDate: new Date("2024-10-31"), // Updated to Date object
    redemptions: 2893,
    revenue: "$89,220",
    discount: "$14,370",
    channels: ["Website", "App"],
    performance: 58,
    conversionRate: "5.6%",
    aiScore: 72,
    targetAudience: "All customers",
    isActive: false,
    minimumPurchase: 100,
  },
  {
    id: "4",
    name: "Holiday Bundle Deal",
    code: "BUNDLE50",
    type: "fixed_amount", // Updated from 'value'
    value: "$50 off",
    status: "scheduled",
    startDate: "Nov 1",
    endDate: "Nov 30",
    redemptions: 0,
    redemptionLimit: 3000,
    revenue: "$0",
    discount: "$0",
    channels: ["All Channels"],
    performance: 0,
    conversionRate: "0%",
    aiScore: 91,
    targetAudience: "Premium customers",
    isActive: true,
    valueAmount: 50,
    minimumPurchase: 200,
  },
  {
    id: "5",
    name: "Black Friday 2024",
    code: "BF2024",
    type: "percentage",
    value: "40%",
    status: "scheduled",
    startDate: "Nov 29",
    endDate: "Dec 2",
    redemptions: 0,
    redemptionLimit: 10000,
    revenue: "$0",
    discount: "$0",
    channels: ["All Channels"],
    performance: 0,
    conversionRate: "0%",
    aiScore: 98,
    targetAudience: "All customers",
    isActive: true,
    categories: ["All Products"],
    campaigns: ["Black Friday Sale"],
    percentageValue: 40,
  },
  {
    id: "6",
    name: "Summer Sale 2024",
    code: "SUMMER24",
    type: "percentage",
    value: "30%",
    status: "expired",
    startDate: "Jun 1",
    endDate: "Aug 31",
    redemptions: 8942,
    redemptionLimit: 10000,
    revenue: "$342,580",
    discount: "$146,820",
    channels: ["Email", "Social", "Website"],
    performance: 89,
    conversionRate: "9.8%",
    aiScore: 92,
    targetAudience: "All customers",
    isActive: false,
    percentageValue: 30,
  },
  {
    id: "7",
    name: "Spring Clearance",
    code: "SPRING20",
    type: "percentage",
    value: "20%",
    status: "expired",
    startDate: "Mar 1",
    endDate: "May 31",
    redemptions: 5623,
    redemptionLimit: 7000,
    revenue: "$198,450",
    discount: "$49,612",
    channels: ["Website", "Email"],
    performance: 80,
    conversionRate: "7.4%",
    targetAudience: "Returning customers",
    isActive: false,
    percentageValue: 20,
  },
  {
    id: "8",
    name: "Valentine's Day Special",
    code: "VDAY15",
    type: "percentage",
    value: "15%",
    status: "expired",
    startDate: "Feb 10",
    endDate: "Feb 14",
    redemptions: 2341,
    redemptionLimit: 3000,
    revenue: "$87,340",
    discount: "$15,420",
    channels: ["Social", "Email"],
    performance: 78,
    conversionRate: "11.2%",
    targetAudience: "All customers",
    isActive: false,
    percentageValue: 15,
  },
  {
    id: "9",
    name: "New Year Blowout",
    code: "NY2024",
    type: "percentage",
    value: "35%",
    status: "expired",
    startDate: "Jan 1",
    endDate: "Jan 7",
    redemptions: 4521,
    redemptionLimit: 5000,
    revenue: "$156,780",
    discount: "$84,560",
    channels: ["All Channels"],
    performance: 90,
    conversionRate: "13.5%",
    aiScore: 95,
    targetAudience: "All customers",
    isActive: false,
    percentageValue: 35,
  },
  {
    id: "10",
    name: "Cyber Monday 2023",
    code: "CM2023",
    type: "fixed_amount", // Updated from 'value'
    value: "$75 off",
    status: "expired",
    startDate: "Nov 27, 2023",
    endDate: "Nov 27, 2023",
    redemptions: 3892,
    redemptionLimit: 4000,
    revenue: "$267,340",
    discount: "$291,900",
    channels: ["Website", "App"],
    performance: 97,
    conversionRate: "15.8%",
    aiScore: 96,
    targetAudience: "Premium customers",
    isActive: false,
    valueAmount: 75,
  },
  {
    id: "11",
    name: "Winter Collection Launch",
    code: "WINTER2025",
    type: "percentage",
    value: "20%",
    status: "draft",
    startDate: "Dec 1",
    endDate: "Dec 31",
    redemptions: 0,
    redemptionLimit: 5000,
    revenue: "$0",
    discount: "$0",
    channels: ["Email", "Social", "Website"],
    performance: 0,
    conversionRate: "0%",
    aiScore: 85,
    targetAudience: "All customers",
    isActive: false,
    percentageValue: 20,
  },
  {
    id: "12",
    name: "VIP Early Access",
    code: "VIPEARLY",
    type: "value",
    value: "$100 off",
    status: "draft",
    startDate: "TBD",
    endDate: "TBD",
    redemptions: 0,
    redemptionLimit: 1000,
    revenue: "$0",
    discount: "$0",
    channels: ["Email"],
    performance: 0,
    conversionRate: "0%",
    aiScore: 92,
    targetAudience: "VIP members",
    isActive: false,
    valueAmount: 100,
  },
  {
    id: "13",
    name: "Back to School Bundle",
    code: "SCHOOL25",
    type: "buy_x_get_y", // Updated from 'bogo'
    value: "Buy 2 Get 1",
    status: "draft",
    startDate: "TBD",
    endDate: "TBD",
    redemptions: 0,
    revenue: "$0",
    discount: "$0",
    channels: ["Website", "App"],
    performance: 0,
    conversionRate: "0%",
    aiScore: 78,
    targetAudience: "Students & Parents",
    isActive: false,
    buyQuantity: 2,
    getQuantity: 1,
  },
];
