-- ============================================================================
-- System & Multi-Tenancy Module
-- ============================================================================
-- This migration creates the core multi-tenant RBAC system tables
-- Dependencies: auth.users (Supabase Auth)
-- ============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS citext;

-- ----------------------------------------------------------------------------
-- 1. sys_tenants
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sys_tenants (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    slug VARCHAR NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'active',
    owner_user_id UUID NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    billing_plan VARCHAR NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    deleted_at TIMESTAMPTZ NULL,
    is_personal BOOLEAN DEFAULT false,
    timezone VARCHAR NULL,
    locale VARCHAR NULL,
    domain VARCHAR NULL,
    external_id VARCHAR NULL,
    notes TEXT NULL,
    
    CONSTRAINT chk_sys_tenants_status CHECK (status IN ('active', 'suspended', 'deleted')),
    CONSTRAINT uq_sys_tenants_name UNIQUE (name),
    CONSTRAINT uq_sys_tenants_slug UNIQUE (slug)
);

COMMENT ON TABLE sys_tenants IS 'Multi-tenant organizations/businesses. Each tenant has isolated data and can have its own users, roles, and configurations.';
COMMENT ON COLUMN sys_tenants.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN sys_tenants.name IS 'Organization/business name';
COMMENT ON COLUMN sys_tenants.slug IS 'URL-friendly identifier (e.g., ''acme-corp'')';
COMMENT ON COLUMN sys_tenants.status IS 'Status: ''active'', ''suspended'', ''deleted''';
COMMENT ON COLUMN sys_tenants.owner_user_id IS 'Tenant owner (Supabase auth user)';
COMMENT ON COLUMN sys_tenants.deleted_at IS 'Soft delete timestamp';

-- Foreign Keys
ALTER TABLE sys_tenants 
    ADD CONSTRAINT fk_sys_tenants_owner_user_id 
    FOREIGN KEY (owner_user_id) REFERENCES auth.users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sys_tenants_owner_user_id ON sys_tenants(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_sys_tenants_status ON sys_tenants(status);
CREATE INDEX IF NOT EXISTS idx_sys_tenants_deleted_at ON sys_tenants(deleted_at) WHERE deleted_at IS NULL;

-- ----------------------------------------------------------------------------
-- 2. sys_users
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sys_users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auth_user_id UUID UNIQUE NOT NULL,
    primary_tenant_id BIGINT NULL,
    email CITEXT NULL,
    phone VARCHAR NULL,
    full_name VARCHAR NULL,
    avatar_url TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    last_sign_in_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB DEFAULT '{}'::jsonb,
    external_id VARCHAR NULL,
    locale VARCHAR NULL,
    timezone VARCHAR NULL,
    deactivated_at TIMESTAMPTZ NULL,
    notes TEXT NULL,
    title VARCHAR NULL,
    department VARCHAR NULL,
    manager_user_id BIGINT NULL,
    
    CONSTRAINT uq_sys_users_auth_user_id UNIQUE (auth_user_id)
);

COMMENT ON TABLE sys_users IS 'Application users linked to Supabase auth.users, with profile information and tenant metadata. Users can belong to multiple tenants.';
COMMENT ON COLUMN sys_users.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN sys_users.auth_user_id IS 'Link to Supabase auth user (one-to-one)';
COMMENT ON COLUMN sys_users.primary_tenant_id IS 'User''s primary/default tenant';
COMMENT ON COLUMN sys_users.manager_user_id IS 'Self-referential: user''s manager';

-- Foreign Keys
ALTER TABLE sys_users 
    ADD CONSTRAINT fk_sys_users_auth_user_id 
    FOREIGN KEY (auth_user_id) REFERENCES auth.users(id);
    
ALTER TABLE sys_users 
    ADD CONSTRAINT fk_sys_users_primary_tenant_id 
    FOREIGN KEY (primary_tenant_id) REFERENCES sys_tenants(id);
    
ALTER TABLE sys_users 
    ADD CONSTRAINT fk_sys_users_manager_user_id 
    FOREIGN KEY (manager_user_id) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sys_users_email ON sys_users(email);
CREATE INDEX IF NOT EXISTS idx_sys_users_primary_tenant ON sys_users(primary_tenant_id);
CREATE INDEX IF NOT EXISTS idx_sys_users_is_active ON sys_users(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_sys_users_manager ON sys_users(manager_user_id);

-- ----------------------------------------------------------------------------
-- 3. sys_roles
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sys_roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    key VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    description TEXT NULL,
    is_system BOOLEAN NOT NULL DEFAULT false,
    is_default BOOLEAN NOT NULL DEFAULT false,
    priority INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    external_id VARCHAR NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    
    CONSTRAINT uq_sys_roles_tenant_key UNIQUE (tenant_id, key),
    CONSTRAINT uq_sys_roles_tenant_name UNIQUE (tenant_id, name)
);

COMMENT ON TABLE sys_roles IS 'Role catalog per tenant. Defines roles like ''admin'', ''editor'', ''viewer'' that are scoped to a specific tenant.';
COMMENT ON COLUMN sys_roles.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN sys_roles.tenant_id IS 'Tenant owner (CASCADE on tenant delete)';
COMMENT ON COLUMN sys_roles.key IS 'Machine-readable key (e.g., ''admin'', ''editor'', ''viewer'')';
COMMENT ON COLUMN sys_roles.name IS 'Human-readable name (e.g., ''Administrator'', ''Editor'', ''Viewer'')';
COMMENT ON COLUMN sys_roles.is_system IS 'Reserved system roles (protected from deletion)';
COMMENT ON COLUMN sys_roles.is_default IS 'Assigned automatically when user joins tenant';

-- Foreign Keys
ALTER TABLE sys_roles 
    ADD CONSTRAINT fk_sys_roles_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sys_roles_tenant ON sys_roles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sys_roles_is_default ON sys_roles(tenant_id, is_default) WHERE is_default = true;
CREATE INDEX IF NOT EXISTS idx_sys_roles_is_system ON sys_roles(is_system);

-- ----------------------------------------------------------------------------
-- 4. sys_permissions
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sys_permissions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    description TEXT NULL,
    resource VARCHAR NULL,
    action VARCHAR NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    tags TEXT[] DEFAULT '{}',
    metadata JSONB DEFAULT '{}'::jsonb
);

COMMENT ON TABLE sys_permissions IS 'Global permission catalog (capabilities/actions) shared across all tenants. Defines what actions can be performed.';
COMMENT ON COLUMN sys_permissions.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN sys_permissions.key IS 'Machine-readable key (e.g., ''order.read'', ''order.write'', ''product.delete'')';
COMMENT ON COLUMN sys_permissions.name IS 'Human-readable name (e.g., ''Read Orders'', ''Write Orders'')';
COMMENT ON COLUMN sys_permissions.resource IS 'Resource type (e.g., ''orders'', ''products'', ''customers'')';
COMMENT ON COLUMN sys_permissions.action IS 'Action type (e.g., ''read'', ''write'', ''delete'', ''manage'')';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sys_permissions_resource_action ON sys_permissions(resource, action);
CREATE INDEX IF NOT EXISTS idx_sys_permissions_resource ON sys_permissions(resource);

-- ----------------------------------------------------------------------------
-- 5. sys_role_permissions
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sys_role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT pk_sys_role_permissions PRIMARY KEY (role_id, permission_id)
);

COMMENT ON TABLE sys_role_permissions IS 'Many-to-many bridge table linking roles to permissions. Defines what permissions each role has.';

-- Foreign Keys
ALTER TABLE sys_role_permissions 
    ADD CONSTRAINT fk_sys_role_permissions_role_id 
    FOREIGN KEY (role_id) REFERENCES sys_roles(id) ON DELETE CASCADE;
    
ALTER TABLE sys_role_permissions 
    ADD CONSTRAINT fk_sys_role_permissions_permission_id 
    FOREIGN KEY (permission_id) REFERENCES sys_permissions(id) ON DELETE RESTRICT;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission ON sys_role_permissions(permission_id);

-- ----------------------------------------------------------------------------
-- 6. sys_user_roles
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sys_user_roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NULL,
    assigned_by BIGINT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    
    CONSTRAINT uq_sys_user_roles_tenant_user_role UNIQUE (tenant_id, user_id, role_id)
);

COMMENT ON TABLE sys_user_roles IS 'Assigns users to roles within a tenant context. Tracks user-role membership per tenant.';
COMMENT ON COLUMN sys_user_roles.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN sys_user_roles.tenant_id IS 'Tenant context (CASCADE on tenant delete)';
COMMENT ON COLUMN sys_user_roles.user_id IS 'User (CASCADE on user delete)';
COMMENT ON COLUMN sys_user_roles.role_id IS 'Role (CASCADE on role delete)';
COMMENT ON COLUMN sys_user_roles.expires_at IS 'Expiration timestamp (NULL = permanent)';
COMMENT ON COLUMN sys_user_roles.assigned_by IS 'User who assigned this role';

-- Foreign Keys
ALTER TABLE sys_user_roles 
    ADD CONSTRAINT fk_sys_user_roles_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id) ON DELETE CASCADE;
    
ALTER TABLE sys_user_roles 
    ADD CONSTRAINT fk_sys_user_roles_user_id 
    FOREIGN KEY (user_id) REFERENCES sys_users(id) ON DELETE CASCADE;
    
ALTER TABLE sys_user_roles 
    ADD CONSTRAINT fk_sys_user_roles_role_id 
    FOREIGN KEY (role_id) REFERENCES sys_roles(id) ON DELETE CASCADE;
    
ALTER TABLE sys_user_roles 
    ADD CONSTRAINT fk_sys_user_roles_assigned_by 
    FOREIGN KEY (assigned_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_user_roles_user_tenant ON sys_user_roles(user_id, tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON sys_user_roles(role_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_expires ON sys_user_roles(expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_roles_tenant_user ON sys_user_roles(tenant_id, user_id);

-- ============================================================================
-- Triggers
-- ============================================================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sys_tenants_updated_at
    BEFORE UPDATE ON sys_tenants
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_sys_users_updated_at
    BEFORE UPDATE ON sys_users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_sys_roles_updated_at
    BEFORE UPDATE ON sys_roles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_sys_permissions_updated_at
    BEFORE UPDATE ON sys_permissions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- 7. sys_brands
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sys_brands (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    code VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    description TEXT NULL,
    logo_url TEXT NULL,
    status VARCHAR NOT NULL DEFAULT 'active',
    website_url VARCHAR NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL,
    
    CONSTRAINT chk_sys_brands_status CHECK (status IN ('active', 'inactive', 'archived')),
    CONSTRAINT uq_sys_brands_tenant_code UNIQUE (tenant_id, code),
    CONSTRAINT uq_sys_brands_tenant_name UNIQUE (tenant_id, name)
);

COMMENT ON TABLE sys_brands IS 'Brand entities belonging to a tenant. One tenant (company) can have multiple brands, each brand can have multiple stores.';
COMMENT ON COLUMN sys_brands.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN sys_brands.tenant_id IS 'Tenant owner (CASCADE on tenant delete)';
COMMENT ON COLUMN sys_brands.code IS 'Machine-readable brand code (e.g., ''BRAND-001'', ''HEBES'')';
COMMENT ON COLUMN sys_brands.name IS 'Human-readable brand name (e.g., ''Hebes Jewelry'', ''Ebes'')';
COMMENT ON COLUMN sys_brands.status IS 'Status: ''active'', ''inactive'', ''archived''';
COMMENT ON COLUMN sys_brands.logo_url IS 'Brand logo URL';
COMMENT ON COLUMN sys_brands.website_url IS 'Brand website URL';

-- Foreign Keys
ALTER TABLE sys_brands 
    ADD CONSTRAINT fk_sys_brands_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id) ON DELETE CASCADE;
    
ALTER TABLE sys_brands 
    ADD CONSTRAINT fk_sys_brands_created_by 
    FOREIGN KEY (created_by) REFERENCES sys_users(id);
    
ALTER TABLE sys_brands 
    ADD CONSTRAINT fk_sys_brands_updated_by 
    FOREIGN KEY (updated_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sys_brands_tenant_id ON sys_brands(tenant_id);
CREATE INDEX IF NOT EXISTS idx_sys_brands_status ON sys_brands(status);
CREATE INDEX IF NOT EXISTS idx_sys_brands_deleted_at ON sys_brands(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_sys_brands_code ON sys_brands(code);

-- Trigger for sys_brands
CREATE TRIGGER trg_sys_brands_updated_at
    BEFORE UPDATE ON sys_brands
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- 8. sys_stores
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sys_stores (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brand_id BIGINT NOT NULL,
    code VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    description TEXT NULL,
    address_line1 VARCHAR NULL,
    address_line2 VARCHAR NULL,
    city VARCHAR NULL,
    state VARCHAR NULL,
    country VARCHAR NULL,
    postal_code VARCHAR NULL,
    phone VARCHAR NULL,
    email CITEXT NULL,
    status VARCHAR NOT NULL DEFAULT 'active',
    is_headquarters BOOLEAN NOT NULL DEFAULT false,
    manager_user_id BIGINT NULL,
    opening_date DATE NULL,
    closing_date DATE NULL,
    timezone VARCHAR NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL,
    
    CONSTRAINT chk_sys_stores_status CHECK (status IN ('active', 'inactive', 'closed')),
    CONSTRAINT chk_sys_stores_closing_date CHECK (closing_date IS NULL OR opening_date IS NULL OR closing_date >= opening_date),
    CONSTRAINT uq_sys_stores_brand_code UNIQUE (brand_id, code),
    CONSTRAINT uq_sys_stores_brand_name UNIQUE (brand_id, name)
);

COMMENT ON TABLE sys_stores IS 'Physical or virtual store locations belonging to a brand. One brand can have many stores, but each store belongs to exactly one brand.';
COMMENT ON COLUMN sys_stores.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN sys_stores.brand_id IS 'Brand owner (CASCADE on brand delete)';
COMMENT ON COLUMN sys_stores.code IS 'Machine-readable store code (e.g., ''STORE-001'', ''HQ'')';
COMMENT ON COLUMN sys_stores.name IS 'Human-readable store name (e.g., ''Main Store'', ''Downtown Branch'')';
COMMENT ON COLUMN sys_stores.status IS 'Status: ''active'', ''inactive'', ''closed''';
COMMENT ON COLUMN sys_stores.is_headquarters IS 'Whether this is the brand headquarters';
COMMENT ON COLUMN sys_stores.manager_user_id IS 'Store manager';

-- Foreign Keys
ALTER TABLE sys_stores 
    ADD CONSTRAINT fk_sys_stores_brand_id 
    FOREIGN KEY (brand_id) REFERENCES sys_brands(id) ON DELETE CASCADE;
    
ALTER TABLE sys_stores 
    ADD CONSTRAINT fk_sys_stores_manager_user_id 
    FOREIGN KEY (manager_user_id) REFERENCES sys_users(id);
    
ALTER TABLE sys_stores 
    ADD CONSTRAINT fk_sys_stores_created_by 
    FOREIGN KEY (created_by) REFERENCES sys_users(id);
    
ALTER TABLE sys_stores 
    ADD CONSTRAINT fk_sys_stores_updated_by 
    FOREIGN KEY (updated_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sys_stores_brand_id ON sys_stores(brand_id);
CREATE INDEX IF NOT EXISTS idx_sys_stores_status ON sys_stores(status);
CREATE INDEX IF NOT EXISTS idx_sys_stores_manager ON sys_stores(manager_user_id);
CREATE INDEX IF NOT EXISTS idx_sys_stores_is_headquarters ON sys_stores(brand_id, is_headquarters) WHERE is_headquarters = true;
CREATE INDEX IF NOT EXISTS idx_sys_stores_deleted_at ON sys_stores(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_sys_stores_city ON sys_stores(city);
CREATE INDEX IF NOT EXISTS idx_sys_stores_country ON sys_stores(country);
CREATE INDEX IF NOT EXISTS idx_sys_stores_opening_date ON sys_stores(opening_date);

-- ============================================================================
-- Triggers for sys_stores
-- ============================================================================

CREATE TRIGGER trg_sys_stores_updated_at
    BEFORE UPDATE ON sys_stores
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Initial Data (Optional - for seeding)
-- ============================================================================

-- Insert default permissions (example)
-- INSERT INTO sys_permissions (key, name, resource, action) VALUES
--     ('order.read', 'Read Orders', 'orders', 'read'),
--     ('order.write', 'Write Orders', 'orders', 'write'),
--     ('order.delete', 'Delete Orders', 'orders', 'delete'),
--     ('product.read', 'Read Products', 'products', 'read'),
--     ('product.write', 'Write Products', 'products', 'write'),
--     ('customer.read', 'Read Customers', 'customers', 'read'),
--     ('customer.write', 'Write Customers', 'customers', 'write'),
--     ('store.read', 'Read Stores', 'stores', 'read'),
--     ('store.write', 'Write Stores', 'stores', 'write'),
--     ('store.manage', 'Manage Stores', 'stores', 'manage')
-- ON CONFLICT (key) DO NOTHING;

