-- ============================================================================
-- Channels & Platforms Module
-- ============================================================================
-- This migration creates tables for marketing platforms and their pages/accounts
-- Dependencies: sys_tenants (001_system_tenant.sql)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. channels_platforms
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS channels_platforms (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    platform_type VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    total_reach INTEGER DEFAULT 0,
    total_engagement NUMERIC(5,2) DEFAULT 0,
    total_budget NUMERIC(12,2) DEFAULT 0,
    page_count INTEGER DEFAULT 0,
    metadata JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    
    CONSTRAINT chk_channels_platforms_name CHECK (name != ''),
    CONSTRAINT chk_channels_platforms_platform_type CHECK (
        platform_type IN ('facebook', 'instagram', 'youtube', 'google-ads', 'tiktok', 'zalo', 'email', 'linkedin', 'twitter', 'pinterest')
    ),
    CONSTRAINT chk_channels_platforms_status CHECK (status IN ('active', 'inactive')),
    CONSTRAINT uq_channels_platforms_tenant_platform UNIQUE (tenant_id, platform_type)
);

COMMENT ON TABLE channels_platforms IS 'Top-level marketing platforms (Facebook, Instagram, YouTube, etc.)';
COMMENT ON COLUMN channels_platforms.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN channels_platforms.tenant_id IS 'Multi-tenancy support';
COMMENT ON COLUMN channels_platforms.platform_type IS 'Platform type: facebook, instagram, youtube, etc.';
COMMENT ON COLUMN channels_platforms.status IS 'Status: active, inactive';

-- Foreign Keys
ALTER TABLE channels_platforms 
    ADD CONSTRAINT fk_channels_platforms_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_channels_platforms_tenant_id ON channels_platforms(tenant_id);
CREATE INDEX IF NOT EXISTS idx_channels_platforms_platform_type ON channels_platforms(platform_type);
CREATE INDEX IF NOT EXISTS idx_channels_platforms_status ON channels_platforms(status);
CREATE INDEX IF NOT EXISTS idx_channels_platforms_deleted_at ON channels_platforms(deleted_at) WHERE deleted_at IS NULL;

-- ----------------------------------------------------------------------------
-- 2. channels_platform_pages
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS channels_platform_pages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    name VARCHAR(256) NOT NULL,
    entity_id VARCHAR(200) DEFAULT NULL,
    entity_id_secondary VARCHAR(200) DEFAULT NULL,
    reach INTEGER DEFAULT 0,
    engagement NUMERIC(5,2) DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    budget NUMERIC(12,2) DEFAULT NULL,
    metadata JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    
    CONSTRAINT chk_channels_platform_pages_name CHECK (name != ''),
    CONSTRAINT chk_channels_platform_pages_engagement CHECK (engagement >= 0 AND engagement <= 100),
    CONSTRAINT chk_channels_platform_pages_status CHECK (status IN ('active', 'inactive')),
    CONSTRAINT uq_channels_platform_pages_tenant_platform_entity UNIQUE (tenant_id, platform_id, entity_id) 
        WHERE entity_id IS NOT NULL
);

COMMENT ON TABLE channels_platform_pages IS 'Individual pages/accounts within platforms';
COMMENT ON COLUMN channels_platform_pages.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN channels_platform_pages.tenant_id IS 'Multi-tenancy support';
COMMENT ON COLUMN channels_platform_pages.platform_id IS 'Parent platform';
COMMENT ON COLUMN channels_platform_pages.entity_id IS 'External entity ID (page_id_meta, account_id, channel_id, etc.)';
COMMENT ON COLUMN channels_platform_pages.entity_id_secondary IS 'Secondary external ID (page_id_pancake, etc.)';

-- Foreign Keys
ALTER TABLE channels_platform_pages 
    ADD CONSTRAINT fk_channels_platform_pages_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id);
    
ALTER TABLE channels_platform_pages 
    ADD CONSTRAINT fk_channels_platform_pages_platform_id 
    FOREIGN KEY (platform_id) REFERENCES channels_platforms(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_channels_platform_pages_tenant_id ON channels_platform_pages(tenant_id);
CREATE INDEX IF NOT EXISTS idx_channels_platform_pages_platform_id ON channels_platform_pages(platform_id);
CREATE INDEX IF NOT EXISTS idx_channels_platform_pages_entity_id ON channels_platform_pages(entity_id) WHERE entity_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_channels_platform_pages_status ON channels_platform_pages(status);
CREATE INDEX IF NOT EXISTS idx_channels_platform_pages_tenant_platform ON channels_platform_pages(tenant_id, platform_id);
CREATE INDEX IF NOT EXISTS idx_channels_platform_pages_deleted_at ON channels_platform_pages(deleted_at) WHERE deleted_at IS NULL;

-- ============================================================================
-- Triggers
-- ============================================================================

CREATE TRIGGER trg_channels_platforms_updated_at
    BEFORE UPDATE ON channels_platforms
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_channels_platform_pages_updated_at
    BEFORE UPDATE ON channels_platform_pages
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

