-- ============================================================================
-- CRM Customer Module
-- ============================================================================
-- This migration creates tables for CRM customer management
-- Dependencies: sys_tenants, sys_users (001_system_tenant.sql)
-- Note: Some tables reference orders, mkt_campaigns, project which will be created later
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. crm_personal_keys
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_personal_keys (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    external_key TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE crm_personal_keys IS 'Canonical person identifier used across CRM. Central hub for all person-related data.';
COMMENT ON COLUMN crm_personal_keys.id IS 'Personal key identifier';
COMMENT ON COLUMN crm_personal_keys.external_key IS 'External identifier (unique)';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_crm_personal_keys_created_at ON crm_personal_keys(created_at);

-- ----------------------------------------------------------------------------
-- 2. crm_personal_contacts
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_personal_contacts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    personal_key_id INTEGER NOT NULL,
    lead_id BIGINT NULL,
    original_lead_id BIGINT NULL,
    contact_type TEXT NULL,
    contact_value TEXT NULL,
    is_primary BOOLEAN DEFAULT false,
    is_verified BOOLEAN DEFAULT false,
    verified_at TIMESTAMPTZ NULL,
    platform_name TEXT NULL,
    platform_user_id TEXT NULL,
    platform_page_id TEXT NULL,
    platform_profile_url TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE crm_personal_contacts IS 'Multiple contacts per person (email, phone, social media). Relates to leads historically.';
COMMENT ON COLUMN crm_personal_contacts.personal_key_id IS 'Person identifier';
COMMENT ON COLUMN crm_personal_contacts.lead_id IS 'Current lead';
COMMENT ON COLUMN crm_personal_contacts.original_lead_id IS 'Original lead';

-- Foreign Keys (some will be added later when referenced tables exist)
ALTER TABLE crm_personal_contacts 
    ADD CONSTRAINT fk_crm_personal_contacts_personal_key_id 
    FOREIGN KEY (personal_key_id) REFERENCES crm_personal_keys(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_crm_personal_contacts_personal_key ON crm_personal_contacts(personal_key_id, is_primary);
CREATE INDEX IF NOT EXISTS idx_crm_personal_contacts_lead_id ON crm_personal_contacts(lead_id);
CREATE INDEX IF NOT EXISTS idx_crm_personal_contacts_contact_value ON crm_personal_contacts(contact_value);
CREATE INDEX IF NOT EXISTS idx_crm_personal_contacts_type ON crm_personal_contacts(contact_type);

-- ----------------------------------------------------------------------------
-- 3. crm_personal_addresses
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_personal_addresses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    personal_key_id INTEGER NOT NULL,
    type VARCHAR DEFAULT 'primary',
    address_line1 VARCHAR NULL,
    address_line2 VARCHAR NULL,
    city VARCHAR NULL,
    state VARCHAR NULL,
    country VARCHAR NULL,
    postal_code VARCHAR NULL,
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE crm_personal_addresses IS 'Address information for persons. Used for billing and shipping in orders.';
COMMENT ON COLUMN crm_personal_addresses.personal_key_id IS 'Person identifier';
COMMENT ON COLUMN crm_personal_addresses.type IS 'Address type';

-- Foreign Keys
ALTER TABLE crm_personal_addresses 
    ADD CONSTRAINT fk_crm_personal_addresses_personal_key_id 
    FOREIGN KEY (personal_key_id) REFERENCES crm_personal_keys(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_crm_personal_addresses_personal_key ON crm_personal_addresses(personal_key_id, is_default);
CREATE INDEX IF NOT EXISTS idx_crm_personal_addresses_type ON crm_personal_addresses(type);

-- ----------------------------------------------------------------------------
-- 4. crm_personal_profile
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_personal_profile (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    personal_key_id INTEGER NOT NULL,
    birth_date DATE NULL,
    custom_attributes JSONB NULL,
    notes TEXT NULL,
    display_name TEXT NULL,
    title TEXT NULL,
    five_element TEXT NULL,
    intention TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE crm_personal_profile IS 'Profile data with custom attributes stored as JSONB. Additional person information.';
COMMENT ON COLUMN crm_personal_profile.personal_key_id IS 'Person identifier';
COMMENT ON COLUMN crm_personal_profile.custom_attributes IS 'Custom attributes (flexible storage)';

-- Foreign Keys
ALTER TABLE crm_personal_profile 
    ADD CONSTRAINT fk_crm_personal_profile_personal_key_id 
    FOREIGN KEY (personal_key_id) REFERENCES crm_personal_keys(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_crm_personal_profile_personal_key ON crm_personal_profile(personal_key_id);
CREATE INDEX IF NOT EXISTS idx_crm_personal_profile_custom_attrs ON crm_personal_profile USING gin (custom_attributes);

-- ----------------------------------------------------------------------------
-- 5. crm_personal_journey
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_personal_journey (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    personal_key_id INTEGER NOT NULL,
    stage VARCHAR NULL,
    emotion VARCHAR NULL,
    next_action TEXT NULL,
    summary_text TEXT NULL,
    confidence_score NUMERIC NULL,
    sentiment_score NUMERIC NULL,
    recorded_by BIGINT NULL,
    source TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE crm_personal_journey IS 'Timeline entries for a person''s journey. Tracks stages, emotions, actions, and analytics.';
COMMENT ON COLUMN crm_personal_journey.personal_key_id IS 'Person identifier';
COMMENT ON COLUMN crm_personal_journey.recorded_by IS 'Staff who recorded';

-- Foreign Keys
ALTER TABLE crm_personal_journey 
    ADD CONSTRAINT fk_crm_personal_journey_personal_key_id 
    FOREIGN KEY (personal_key_id) REFERENCES crm_personal_keys(id);
    
ALTER TABLE crm_personal_journey 
    ADD CONSTRAINT fk_crm_personal_journey_recorded_by 
    FOREIGN KEY (recorded_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_crm_personal_journey_personal_key ON crm_personal_journey(personal_key_id, created_at);
CREATE INDEX IF NOT EXISTS idx_crm_personal_journey_recorded_by ON crm_personal_journey(recorded_by);
CREATE INDEX IF NOT EXISTS idx_crm_personal_journey_stage ON crm_personal_journey(stage);
CREATE INDEX IF NOT EXISTS idx_crm_personal_journey_created_at ON crm_personal_journey(created_at);

-- ----------------------------------------------------------------------------
-- 6. crm_leads
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_leads (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    personal_key_id INTEGER NOT NULL,
    status VARCHAR NULL,
    source VARCHAR NULL,
    assigned_to BIGINT NULL,
    order_id BIGINT NULL,
    tenant_id BIGINT NOT NULL,
    converted_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE crm_leads IS 'Lead lifecycle management prior to or alongside customer conversion.';
COMMENT ON COLUMN crm_leads.personal_key_id IS 'Person identifier';
COMMENT ON COLUMN crm_leads.assigned_to IS 'Assigned staff';
COMMENT ON COLUMN crm_leads.order_id IS 'Linked order';
COMMENT ON COLUMN crm_leads.tenant_id IS 'Tenant';

-- Foreign Keys
ALTER TABLE crm_leads 
    ADD CONSTRAINT fk_crm_leads_personal_key_id 
    FOREIGN KEY (personal_key_id) REFERENCES crm_personal_keys(id);
    
ALTER TABLE crm_leads 
    ADD CONSTRAINT fk_crm_leads_assigned_to 
    FOREIGN KEY (assigned_to) REFERENCES sys_users(id);
    
ALTER TABLE crm_leads 
    ADD CONSTRAINT fk_crm_leads_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id);

-- Note: order_id FK will be added after orders table is created

-- Indexes
CREATE INDEX IF NOT EXISTS idx_crm_leads_personal_key ON crm_leads(personal_key_id);
CREATE INDEX IF NOT EXISTS idx_crm_leads_tenant_id ON crm_leads(tenant_id);
CREATE INDEX IF NOT EXISTS idx_crm_leads_assigned_to ON crm_leads(assigned_to);
CREATE INDEX IF NOT EXISTS idx_crm_leads_status ON crm_leads(status);
CREATE INDEX IF NOT EXISTS idx_crm_leads_created_at ON crm_leads(created_at);

-- ----------------------------------------------------------------------------
-- 7. crm_customers
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_customers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    personal_key_id INTEGER NOT NULL,
    lifetime_value NUMERIC NULL,
    paid_orders_count INTEGER NULL,
    lead_status VARCHAR NULL,
    potential_status VARCHAR NULL,
    source VARCHAR NULL,
    customer_rank VARCHAR NULL,
    last_order_at TIMESTAMPTZ NULL,
    tenant_id BIGINT NOT NULL,
    first_lead_id BIGINT NULL,
    id_batch INTEGER NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE crm_customers IS 'Canonical customer record. Tracks lifetime value, order history, and customer status.';
COMMENT ON COLUMN crm_customers.personal_key_id IS 'Person identifier';
COMMENT ON COLUMN crm_customers.tenant_id IS 'Tenant';
COMMENT ON COLUMN crm_customers.first_lead_id IS 'First lead';
COMMENT ON COLUMN crm_customers.id_batch IS 'Re-engagement batch';

-- Foreign Keys
ALTER TABLE crm_customers 
    ADD CONSTRAINT fk_crm_customers_personal_key_id 
    FOREIGN KEY (personal_key_id) REFERENCES crm_personal_keys(id);
    
ALTER TABLE crm_customers 
    ADD CONSTRAINT fk_crm_customers_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id);
    
ALTER TABLE crm_customers 
    ADD CONSTRAINT fk_crm_customers_first_lead_id 
    FOREIGN KEY (first_lead_id) REFERENCES crm_leads(id);

-- Note: id_batch FK will be added after crm_reengaged_batches table is created

-- Indexes
CREATE INDEX IF NOT EXISTS idx_crm_customers_personal_key ON crm_customers(personal_key_id);
CREATE INDEX IF NOT EXISTS idx_crm_customers_tenant_id ON crm_customers(tenant_id);
CREATE INDEX IF NOT EXISTS idx_crm_customers_first_lead_id ON crm_customers(first_lead_id);
CREATE INDEX IF NOT EXISTS idx_crm_customers_last_order_at ON crm_customers(last_order_at);
CREATE INDEX IF NOT EXISTS idx_crm_customers_lifetime_value ON crm_customers(lifetime_value);

-- ----------------------------------------------------------------------------
-- 8. crm_potential
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_potential (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    personal_key_id INTEGER NOT NULL,
    assigned_to BIGINT NULL,
    status VARCHAR NULL,
    stage VARCHAR NULL,
    priority VARCHAR NULL,
    campaign_id BIGINT NULL,
    converted_to_order_id BIGINT NULL,
    tenant_id BIGINT NOT NULL,
    estimated_value NUMERIC NULL,
    probability_score INTEGER NULL,
    expected_close_date DATE NULL,
    interested_products TEXT[] NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE crm_potential IS 'Sales opportunity/pipeline entity. Tracks sales opportunities with stages, priorities, and conversion.';
COMMENT ON COLUMN crm_potential.personal_key_id IS 'Person identifier';
COMMENT ON COLUMN crm_potential.assigned_to IS 'Assigned staff';
COMMENT ON COLUMN crm_potential.campaign_id IS 'Marketing campaign';
COMMENT ON COLUMN crm_potential.converted_to_order_id IS 'Converted order';
COMMENT ON COLUMN crm_potential.tenant_id IS 'Tenant';

-- Foreign Keys
ALTER TABLE crm_potential 
    ADD CONSTRAINT fk_crm_potential_personal_key_id 
    FOREIGN KEY (personal_key_id) REFERENCES crm_personal_keys(id);
    
ALTER TABLE crm_potential 
    ADD CONSTRAINT fk_crm_potential_assigned_to 
    FOREIGN KEY (assigned_to) REFERENCES sys_users(id);
    
ALTER TABLE crm_potential 
    ADD CONSTRAINT fk_crm_potential_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id);

-- Note: campaign_id and converted_to_order_id FKs will be added after those tables are created

-- Indexes
CREATE INDEX IF NOT EXISTS idx_crm_potential_personal_key ON crm_potential(personal_key_id);
CREATE INDEX IF NOT EXISTS idx_crm_potential_assigned_to ON crm_potential(assigned_to);
CREATE INDEX IF NOT EXISTS idx_crm_potential_campaign_id ON crm_potential(campaign_id);
CREATE INDEX IF NOT EXISTS idx_crm_potential_tenant_id ON crm_potential(tenant_id);
CREATE INDEX IF NOT EXISTS idx_crm_potential_status_stage ON crm_potential(status, stage);
CREATE INDEX IF NOT EXISTS idx_crm_potential_expected_close_date ON crm_potential(expected_close_date);

-- ----------------------------------------------------------------------------
-- 9. crm_reengaged_batches
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_reengaged_batches (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    batch_name VARCHAR NULL,
    assigned_to BIGINT NULL,
    historical_value INTEGER NULL,
    status VARCHAR NULL,
    created_date DATE NULL,
    target_size INTEGER NULL,
    start_date DATE NULL,
    end_date DATE NULL,
    contacted_count INTEGER NULL,
    response_count INTEGER NULL,
    conversion_count INTEGER NULL,
    reactivated_revenue NUMERIC NULL,
    target_revenue NUMERIC NULL,
    target_response_rate NUMERIC NULL,
    created_by BIGINT NULL
);

COMMENT ON TABLE crm_reengaged_batches IS 'Re-engagement campaign grouping. Tracks batch campaigns for customer re-engagement.';
COMMENT ON COLUMN crm_reengaged_batches.assigned_to IS 'Assigned staff';
COMMENT ON COLUMN crm_reengaged_batches.created_by IS 'Created by staff';

-- Foreign Keys
ALTER TABLE crm_reengaged_batches 
    ADD CONSTRAINT fk_crm_reengaged_batches_assigned_to 
    FOREIGN KEY (assigned_to) REFERENCES sys_users(id);
    
ALTER TABLE crm_reengaged_batches 
    ADD CONSTRAINT fk_crm_reengaged_batches_created_by 
    FOREIGN KEY (created_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_crm_reengaged_batches_status ON crm_reengaged_batches(status);
CREATE INDEX IF NOT EXISTS idx_crm_reengaged_batches_created_date ON crm_reengaged_batches(created_date);
CREATE INDEX IF NOT EXISTS idx_crm_reengaged_batches_dates ON crm_reengaged_batches(start_date, end_date);

-- Now add FK from crm_customers to crm_reengaged_batches
ALTER TABLE crm_customers 
    ADD CONSTRAINT fk_crm_customers_id_batch 
    FOREIGN KEY (id_batch) REFERENCES crm_reengaged_batches(id);

-- ----------------------------------------------------------------------------
-- 10. crm_reengage_personal_keys
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_reengage_personal_keys (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    batch_id INTEGER NOT NULL,
    personal_key_id INTEGER NOT NULL,
    assigned_to BIGINT NULL,
    priority VARCHAR NULL,
    status VARCHAR NULL,
    contact_attempts INTEGER NULL,
    last_contact_method VARCHAR NULL,
    added_to_batch_at TIMESTAMPTZ NULL,
    contacted_at TIMESTAMPTZ NULL,
    responded_at TIMESTAMPTZ NULL,
    converted_at TIMESTAMPTZ NULL,
    opted_out_at TIMESTAMPTZ NULL,
    converted_order_id BIGINT NULL,
    conversion_value NUMERIC NULL,
    failure_reason VARCHAR NULL,
    notes TEXT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE crm_reengage_personal_keys IS 'Batch membership and contact outcomes. Tracks individual person participation in re-engagement batches.';
COMMENT ON COLUMN crm_reengage_personal_keys.batch_id IS 'Batch identifier';
COMMENT ON COLUMN crm_reengage_personal_keys.personal_key_id IS 'Person identifier';
COMMENT ON COLUMN crm_reengage_personal_keys.assigned_to IS 'Assigned staff';
COMMENT ON COLUMN crm_reengage_personal_keys.converted_order_id IS 'Converted order';

-- Foreign Keys
ALTER TABLE crm_reengage_personal_keys 
    ADD CONSTRAINT fk_crm_reengage_personal_keys_batch_id 
    FOREIGN KEY (batch_id) REFERENCES crm_reengaged_batches(id);
    
ALTER TABLE crm_reengage_personal_keys 
    ADD CONSTRAINT fk_crm_reengage_personal_keys_personal_key_id 
    FOREIGN KEY (personal_key_id) REFERENCES crm_personal_keys(id);
    
ALTER TABLE crm_reengage_personal_keys 
    ADD CONSTRAINT fk_crm_reengage_personal_keys_assigned_to 
    FOREIGN KEY (assigned_to) REFERENCES sys_users(id);

-- Note: converted_order_id FK will be added after orders table is created

-- Indexes
CREATE INDEX IF NOT EXISTS idx_crm_reengage_personal_keys_batch_id ON crm_reengage_personal_keys(batch_id, personal_key_id, assigned_to, status);
CREATE INDEX IF NOT EXISTS idx_crm_reengage_personal_keys_personal_key ON crm_reengage_personal_keys(personal_key_id);
CREATE INDEX IF NOT EXISTS idx_crm_reengage_personal_keys_status ON crm_reengage_personal_keys(status);
CREATE INDEX IF NOT EXISTS idx_crm_reengage_personal_keys_priority ON crm_reengage_personal_keys(priority);

-- ----------------------------------------------------------------------------
-- 11. crm_reengage_batches_stats
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_reengage_batches_stats (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    batch_id INTEGER NOT NULL,
    snapshot_date DATE NULL,
    contacted_count INTEGER NULL,
    response_count INTEGER NULL,
    conversion_count INTEGER NULL,
    revenue_generated NUMERIC NULL,
    total_contacted INTEGER NULL,
    total_responses INTEGER NULL,
    total_conversions INTEGER NULL,
    total_revenue NUMERIC NULL,
    response_rate NUMERIC NULL,
    conversion_rate NUMERIC NULL,
    avg_revenue_per_conversion NUMERIC NULL,
    sms_sent INTEGER NULL,
    email_sent INTEGER NULL,
    phone_calls INTEGER NULL,
    notes TEXT NULL
);

COMMENT ON TABLE crm_reengage_batches_stats IS 'Aggregations by day/batch. Daily snapshot of batch performance metrics.';
COMMENT ON COLUMN crm_reengage_batches_stats.batch_id IS 'Batch identifier';
COMMENT ON COLUMN crm_reengage_batches_stats.snapshot_date IS 'Snapshot date';

-- Foreign Keys
ALTER TABLE crm_reengage_batches_stats 
    ADD CONSTRAINT fk_crm_reengage_batches_stats_batch_id 
    FOREIGN KEY (batch_id) REFERENCES crm_reengaged_batches(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_crm_reengage_batches_stats_batch_id ON crm_reengage_batches_stats(batch_id, snapshot_date);
CREATE INDEX IF NOT EXISTS idx_crm_reengage_batches_stats_snapshot_date ON crm_reengage_batches_stats(snapshot_date);

-- ============================================================================
-- Triggers
-- ============================================================================

CREATE TRIGGER trg_crm_personal_contacts_updated_at
    BEFORE UPDATE ON crm_personal_contacts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_crm_personal_addresses_updated_at
    BEFORE UPDATE ON crm_personal_addresses
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_crm_personal_profile_updated_at
    BEFORE UPDATE ON crm_personal_profile
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_crm_leads_updated_at
    BEFORE UPDATE ON crm_leads
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_crm_customers_updated_at
    BEFORE UPDATE ON crm_customers
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_crm_potential_updated_at
    BEFORE UPDATE ON crm_potential
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Additional Foreign Keys (to be added after referenced tables are created)
-- ============================================================================

-- These will be added in later migration files:
-- ALTER TABLE crm_personal_contacts ADD CONSTRAINT fk_crm_personal_contacts_lead_id FOREIGN KEY (lead_id) REFERENCES crm_leads(id);
-- ALTER TABLE crm_personal_contacts ADD CONSTRAINT fk_crm_personal_contacts_original_lead_id FOREIGN KEY (original_lead_id) REFERENCES crm_leads(id);
-- ALTER TABLE crm_leads ADD CONSTRAINT fk_crm_leads_order_id FOREIGN KEY (order_id) REFERENCES orders(id);
-- ALTER TABLE crm_potential ADD CONSTRAINT fk_crm_potential_campaign_id FOREIGN KEY (campaign_id) REFERENCES mkt_campaigns(id);
-- ALTER TABLE crm_potential ADD CONSTRAINT fk_crm_potential_converted_to_order_id FOREIGN KEY (converted_to_order_id) REFERENCES orders(id);
-- ALTER TABLE crm_reengage_personal_keys ADD CONSTRAINT fk_crm_reengage_personal_keys_converted_order_id FOREIGN KEY (converted_order_id) REFERENCES orders(id);

