-- ============================================================================
-- Orders Domain Module
-- ============================================================================
-- This migration creates tables for order management
-- Dependencies: sys_tenants, sys_users, sys_stores (001_system_tenant.sql), 
--               crm_customers, crm_personal_addresses (003_crm_customer.sql),
--               channels_platform_pages (002_channels_platforms.sql),
--               product (will be created later)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. orders
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR NOT NULL,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
    total NUMERIC NULL,
    id_customer BIGINT NULL,
    shipping_address_id BIGINT NULL,
    billing_address_id BIGINT NULL,
    external_order_id TEXT NULL,
    store_id BIGINT NULL,
    channel_platform_page_id BIGINT NULL,
    tenant_id BIGINT NOT NULL,
    customer_notes TEXT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL,
    
    CONSTRAINT chk_orders_total CHECK (total >= 0),
    CONSTRAINT uq_orders_external_order UNIQUE (external_order_id, tenant_id) 
        WHERE external_order_id IS NOT NULL
);

COMMENT ON TABLE orders IS 'Order headers - the central table for all order information.';
COMMENT ON COLUMN orders.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN orders.status IS 'Order status';
COMMENT ON COLUMN orders.total IS 'Total order amount (must be non-negative)';
COMMENT ON COLUMN orders.id_customer IS 'Customer who placed order';
COMMENT ON COLUMN orders.shipping_address_id IS 'Shipping address';
COMMENT ON COLUMN orders.billing_address_id IS 'Billing address';
COMMENT ON COLUMN orders.external_order_id IS 'External system order ID';
COMMENT ON COLUMN orders.store_id IS 'Store where order was placed';
COMMENT ON COLUMN orders.channel_platform_page_id IS 'Channel/platform page where order originated';
COMMENT ON COLUMN orders.tenant_id IS 'Multi-tenant support';

-- Foreign Keys
ALTER TABLE orders 
    ADD CONSTRAINT fk_orders_id_customer 
    FOREIGN KEY (id_customer) REFERENCES crm_customers(id);
    
ALTER TABLE orders 
    ADD CONSTRAINT fk_orders_shipping_address_id 
    FOREIGN KEY (shipping_address_id) REFERENCES crm_personal_addresses(id);
    
ALTER TABLE orders 
    ADD CONSTRAINT fk_orders_billing_address_id 
    FOREIGN KEY (billing_address_id) REFERENCES crm_personal_addresses(id);
    
ALTER TABLE orders 
    ADD CONSTRAINT fk_orders_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id);
    
ALTER TABLE orders 
    ADD CONSTRAINT fk_orders_store_id 
    FOREIGN KEY (store_id) REFERENCES sys_stores(id);
    
ALTER TABLE orders 
    ADD CONSTRAINT fk_orders_channel_platform_page_id 
    FOREIGN KEY (channel_platform_page_id) REFERENCES channels_platform_pages(id);
    
ALTER TABLE orders 
    ADD CONSTRAINT fk_orders_created_by 
    FOREIGN KEY (created_by) REFERENCES sys_users(id);
    
ALTER TABLE orders 
    ADD CONSTRAINT fk_orders_updated_by 
    FOREIGN KEY (updated_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_orders_tenant_id ON orders(tenant_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(id_customer);
CREATE INDEX IF NOT EXISTS idx_orders_store_id ON orders(store_id);
CREATE INDEX IF NOT EXISTS idx_orders_channel_platform_page_id ON orders(channel_platform_page_id);
CREATE INDEX IF NOT EXISTS idx_orders_date_created ON orders(date_created);
CREATE INDEX IF NOT EXISTS idx_orders_external_order_id ON orders(external_order_id);
CREATE INDEX IF NOT EXISTS idx_orders_tenant_status_date ON orders(tenant_id, status, date_created);
CREATE INDEX IF NOT EXISTS idx_orders_deleted_at ON orders(deleted_at) WHERE deleted_at IS NULL;

-- ----------------------------------------------------------------------------
-- 2. order_items
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NULL,
    line_item_id VARCHAR NULL,
    status VARCHAR NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC NOT NULL,
    total_price NUMERIC NOT NULL GENERATED ALWAYS AS (quantity * unit_price) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    
    CONSTRAINT chk_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT chk_order_items_unit_price CHECK (unit_price >= 0)
);

COMMENT ON TABLE order_items IS 'Normalized order line items - individual products/services in an order.';
COMMENT ON COLUMN order_items.order_id IS 'Parent order';
COMMENT ON COLUMN order_items.product_id IS 'Product identifier';
COMMENT ON COLUMN order_items.quantity IS 'Quantity ordered (must be positive)';
COMMENT ON COLUMN order_items.unit_price IS 'Price per unit (must be non-negative)';
COMMENT ON COLUMN order_items.total_price IS 'Total line price (calculated)';

-- Foreign Keys
ALTER TABLE order_items 
    ADD CONSTRAINT fk_order_items_order_id 
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
    
ALTER TABLE order_items 
    ADD CONSTRAINT fk_order_items_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE SET NULL;

-- Note: product_id FK uses ON DELETE SET NULL to preserve historical order data
-- when products are deleted, while maintaining referential integrity for active products

-- Foreign Keys for audit fields
ALTER TABLE order_items 
    ADD CONSTRAINT fk_order_items_created_by 
    FOREIGN KEY (created_by) REFERENCES sys_users(id);
    
ALTER TABLE order_items 
    ADD CONSTRAINT fk_order_items_updated_by 
    FOREIGN KEY (updated_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_status ON order_items(order_id, status);

-- ----------------------------------------------------------------------------
-- 3. item_after_sales
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS item_after_sales (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NULL,
    order_item_id BIGINT NOT NULL,
    original_order_item_id BIGINT NULL,
    case_type VARCHAR NULL,
    status INTEGER NULL,
    rma_code VARCHAR NULL UNIQUE,
    amount NUMERIC NULL,
    tracking_number VARCHAR NULL,
    status_tracking VARCHAR NULL,
    reason TEXT NULL,
    details TEXT NULL,
    received_date DATE NULL,
    inquiry_date DATE NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL,
    
    CONSTRAINT chk_item_after_sales_amount CHECK (amount >= 0)
);

COMMENT ON TABLE item_after_sales IS 'After-sales service cases including returns, repairs, and exchanges at item level.';
COMMENT ON COLUMN item_after_sales.order_id IS 'Parent order (denormalized for performance)';
COMMENT ON COLUMN item_after_sales.order_item_id IS 'Related order item';
COMMENT ON COLUMN item_after_sales.original_order_item_id IS 'Original order item (if different)';
COMMENT ON COLUMN item_after_sales.rma_code IS 'Return Merchandise Authorization code';

-- Foreign Keys
ALTER TABLE item_after_sales 
    ADD CONSTRAINT fk_item_after_sales_order_id 
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
    
ALTER TABLE item_after_sales 
    ADD CONSTRAINT fk_item_after_sales_order_item_id 
    FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE;
    
ALTER TABLE item_after_sales 
    ADD CONSTRAINT fk_item_after_sales_original_order_item_id 
    FOREIGN KEY (original_order_item_id) REFERENCES order_items(id);
    
ALTER TABLE item_after_sales 
    ADD CONSTRAINT fk_item_after_sales_created_by 
    FOREIGN KEY (created_by) REFERENCES sys_users(id);
    
ALTER TABLE item_after_sales 
    ADD CONSTRAINT fk_item_after_sales_updated_by 
    FOREIGN KEY (updated_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_item_after_sales_order_id ON item_after_sales(order_id);
CREATE INDEX IF NOT EXISTS idx_item_after_sales_order_item_id ON item_after_sales(order_item_id);
CREATE INDEX IF NOT EXISTS idx_item_after_sales_status ON item_after_sales(status);
CREATE INDEX IF NOT EXISTS idx_item_after_sales_deleted_at ON item_after_sales(deleted_at) WHERE deleted_at IS NULL;

-- ----------------------------------------------------------------------------
-- 4. item_pre_orders
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS item_pre_orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NULL,
    order_item_id BIGINT NOT NULL,
    status INTEGER NULL,
    category VARCHAR NULL,
    vendor VARCHAR NULL,
    hold_until DATE NULL,
    processing_date DATE NULL,
    reason TEXT NULL,
    notes TEXT NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL
);

COMMENT ON TABLE item_pre_orders IS 'Pre-order records tied to order items - tracks items that are ordered but not yet available.';
COMMENT ON COLUMN item_pre_orders.order_id IS 'Parent order (denormalized for performance)';
COMMENT ON COLUMN item_pre_orders.order_item_id IS 'Parent order item';
COMMENT ON COLUMN item_pre_orders.hold_until IS 'Date to hold order until';

-- Foreign Keys
ALTER TABLE item_pre_orders 
    ADD CONSTRAINT fk_item_pre_orders_order_id 
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
    
ALTER TABLE item_pre_orders 
    ADD CONSTRAINT fk_item_pre_orders_order_item_id 
    FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE;
    
ALTER TABLE item_pre_orders 
    ADD CONSTRAINT fk_item_pre_orders_created_by 
    FOREIGN KEY (created_by) REFERENCES sys_users(id);
    
ALTER TABLE item_pre_orders 
    ADD CONSTRAINT fk_item_pre_orders_updated_by 
    FOREIGN KEY (updated_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_item_pre_orders_order_id ON item_pre_orders(order_id);
CREATE INDEX IF NOT EXISTS idx_item_pre_orders_order_item_id ON item_pre_orders(order_item_id);
CREATE INDEX IF NOT EXISTS idx_item_pre_orders_hold_until ON item_pre_orders(hold_until);
CREATE INDEX IF NOT EXISTS idx_item_pre_orders_deleted_at ON item_pre_orders(deleted_at) WHERE deleted_at IS NULL;

-- ----------------------------------------------------------------------------
-- 5. item_customization
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS item_customization (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NULL,
    order_item_id BIGINT NOT NULL UNIQUE,
    actual_amount NUMERIC NULL,
    balance_due NUMERIC NULL,
    payment_status INTEGER NULL,
    design_3d_image VARCHAR NULL,
    design_status INTEGER NULL,
    design_time TIMESTAMPTZ NULL,
    material_status INTEGER NULL,
    material_time TIMESTAMPTZ NULL,
    completion_status INTEGER NULL,
    completion_time TIMESTAMPTZ NULL,
    ship_date DATE NULL,
    check_status VARCHAR NULL,
    third_party_brand VARCHAR NULL,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL,
    
    CONSTRAINT chk_item_customization_actual_amount CHECK (actual_amount >= 0),
    CONSTRAINT chk_item_customization_balance_due CHECK (balance_due >= 0)
);

COMMENT ON TABLE item_customization IS 'Custom item-level workflow and billing for bespoke/custom-made jobs.';
COMMENT ON COLUMN item_customization.order_id IS 'Parent order (denormalized for performance)';
COMMENT ON COLUMN item_customization.order_item_id IS 'Custom order item (1:1)';
COMMENT ON COLUMN item_customization.actual_amount IS 'Actual item amount (must be non-negative)';
COMMENT ON COLUMN item_customization.balance_due IS 'Remaining balance (must be non-negative)';

-- Foreign Keys
ALTER TABLE item_customization 
    ADD CONSTRAINT fk_item_customization_order_id 
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
    
ALTER TABLE item_customization 
    ADD CONSTRAINT fk_item_customization_order_item_id 
    FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE;
    
ALTER TABLE item_customization 
    ADD CONSTRAINT fk_item_customization_created_by 
    FOREIGN KEY (created_by) REFERENCES sys_users(id);
    
ALTER TABLE item_customization 
    ADD CONSTRAINT fk_item_customization_updated_by 
    FOREIGN KEY (updated_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_item_customization_order_id ON item_customization(order_id);
CREATE INDEX IF NOT EXISTS idx_item_customization_statuses ON item_customization(payment_status, design_status, material_status, completion_status);
CREATE INDEX IF NOT EXISTS idx_item_customization_deleted_at ON item_customization(deleted_at) WHERE deleted_at IS NULL;

-- ----------------------------------------------------------------------------
-- 6. orders_meta
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders_meta (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL UNIQUE,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE orders_meta IS 'Order metadata - extended information in a 1:1 relationship with orders.';
COMMENT ON COLUMN orders_meta.order_id IS 'Related order (1:1)';
COMMENT ON COLUMN orders_meta.metadata IS 'Flexible metadata storage';

-- Foreign Keys
ALTER TABLE orders_meta 
    ADD CONSTRAINT fk_orders_meta_order_id 
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
    
ALTER TABLE orders_meta 
    ADD CONSTRAINT fk_orders_meta_created_by 
    FOREIGN KEY (created_by) REFERENCES sys_users(id);
    
ALTER TABLE orders_meta 
    ADD CONSTRAINT fk_orders_meta_updated_by 
    FOREIGN KEY (updated_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_orders_meta_metadata_gin ON orders_meta USING gin (metadata);

-- ----------------------------------------------------------------------------
-- 7. order_meta_crm
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_meta_crm (
    id BIGINT PRIMARY KEY,
    sales_staff_id BIGINT NULL,
    referrer_staff_id BIGINT NULL,
    support_by VARCHAR NULL,
    social_review TEXT NULL,
    customer_feedback TEXT NULL,
    follow_up_status VARCHAR NULL,
    approval_status VARCHAR NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE order_meta_crm IS 'CRM metadata for orders - tracks sales staff, source, feedback, and follow-up status in a 1:1 relationship with orders.';
COMMENT ON COLUMN order_meta_crm.id IS 'Related order (1:1, PK)';
COMMENT ON COLUMN order_meta_crm.sales_staff_id IS 'Staff who closed the order';
COMMENT ON COLUMN order_meta_crm.referrer_staff_id IS 'Staff who referred/introduced';
COMMENT ON COLUMN order_meta_crm.support_by IS 'Support staff identifier';
COMMENT ON COLUMN order_meta_crm.social_review IS 'Social media review text';
COMMENT ON COLUMN order_meta_crm.customer_feedback IS 'Customer feedback text';
COMMENT ON COLUMN order_meta_crm.follow_up_status IS 'Follow-up status';
COMMENT ON COLUMN order_meta_crm.approval_status IS 'Approval status';

-- Foreign Keys
ALTER TABLE order_meta_crm 
    ADD CONSTRAINT fk_order_meta_crm_id 
    FOREIGN KEY (id) REFERENCES orders(id) ON DELETE CASCADE;
    
ALTER TABLE order_meta_crm 
    ADD CONSTRAINT fk_order_meta_crm_sales_staff_id 
    FOREIGN KEY (sales_staff_id) REFERENCES sys_users(id);
    
ALTER TABLE order_meta_crm 
    ADD CONSTRAINT fk_order_meta_crm_referrer_staff_id 
    FOREIGN KEY (referrer_staff_id) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_order_meta_crm_sales_staff_id ON order_meta_crm(sales_staff_id);
CREATE INDEX IF NOT EXISTS idx_order_meta_crm_referrer_staff_id ON order_meta_crm(referrer_staff_id);
CREATE INDEX IF NOT EXISTS idx_order_meta_crm_follow_up_status ON order_meta_crm(follow_up_status);
CREATE INDEX IF NOT EXISTS idx_order_meta_crm_approval_status ON order_meta_crm(approval_status);

-- ----------------------------------------------------------------------------
-- 8. order_images
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_images (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    image_url VARCHAR NOT NULL,
    image_type VARCHAR NULL,
    description TEXT NULL,
    sort_order INTEGER NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL
);

COMMENT ON TABLE order_images IS 'Order images and attachments - stores image URLs and metadata for orders.';
COMMENT ON COLUMN order_images.order_id IS 'Related order';
COMMENT ON COLUMN order_images.image_url IS 'Image file URL/path';
COMMENT ON COLUMN order_images.image_type IS 'Image type (e.g., ''receipt'', ''product'', ''custom'')';

-- Foreign Keys
ALTER TABLE order_images 
    ADD CONSTRAINT fk_order_images_order_id 
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
    
ALTER TABLE order_images 
    ADD CONSTRAINT fk_order_images_created_by 
    FOREIGN KEY (created_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_order_images_order_id ON order_images(order_id);
CREATE INDEX IF NOT EXISTS idx_order_images_image_type ON order_images(image_type);

-- ----------------------------------------------------------------------------
-- 9. order_payments
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    payment_method VARCHAR(100) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    transaction_id VARCHAR(300) NOT NULL DEFAULT '',
    due_date TIMESTAMPTZ NULL,
    paid_date TIMESTAMPTZ NULL,
    is_deposit BOOLEAN NOT NULL DEFAULT false,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ NULL,
    
    CONSTRAINT chk_order_payments_amount CHECK (amount > 0),
    CONSTRAINT chk_order_payments_status CHECK (status IN ('pending', 'paid', 'failed', 'refunded')),
    CONSTRAINT chk_order_payments_paid_date CHECK (paid_date IS NULL OR due_date IS NULL OR paid_date >= due_date),
    CONSTRAINT uq_order_payment_transaction_id_nonempty UNIQUE (transaction_id) 
        WHERE transaction_id <> ''
);

COMMENT ON TABLE order_payments IS 'Order payment transactions - tracks individual payment records for orders, supporting deposits, installments, and multiple payment methods.';
COMMENT ON COLUMN order_payments.order_id IS 'Parent order (CASCADE on delete)';
COMMENT ON COLUMN order_payments.payment_method IS 'Payment method (e.g., ''credit_card'', ''paypal'', ''bank_transfer'')';
COMMENT ON COLUMN order_payments.amount IS 'Payment amount (must be positive)';
COMMENT ON COLUMN order_payments.status IS 'Payment status: ''pending'', ''paid'', ''failed'', ''refunded''';
COMMENT ON COLUMN order_payments.is_deposit IS 'Whether this is a deposit payment';

-- Foreign Keys
ALTER TABLE order_payments 
    ADD CONSTRAINT fk_order_payments_order_id 
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
    
ALTER TABLE order_payments 
    ADD CONSTRAINT fk_order_payments_created_by 
    FOREIGN KEY (created_by) REFERENCES sys_users(id);
    
ALTER TABLE order_payments 
    ADD CONSTRAINT fk_order_payments_updated_by 
    FOREIGN KEY (updated_by) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_order_payment_order_id ON order_payments(order_id);
CREATE INDEX IF NOT EXISTS idx_order_payment_status ON order_payments(status);
CREATE INDEX IF NOT EXISTS idx_order_payment_transaction_id ON order_payments(transaction_id);
CREATE INDEX IF NOT EXISTS idx_order_payment_paid_date ON order_payments(paid_date);
CREATE INDEX IF NOT EXISTS idx_order_payment_order_status ON order_payments(order_id, status);
CREATE INDEX IF NOT EXISTS idx_order_payment_order_paid_date ON order_payments(order_id, paid_date DESC);

-- ============================================================================
-- Triggers
-- ============================================================================

CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_order_items_updated_at
    BEFORE UPDATE ON order_items
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_item_after_sales_updated_at
    BEFORE UPDATE ON item_after_sales
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_item_pre_orders_updated_at
    BEFORE UPDATE ON item_pre_orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_item_customization_updated_at
    BEFORE UPDATE ON item_customization
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_orders_meta_updated_at
    BEFORE UPDATE ON orders_meta
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_order_meta_crm_updated_at
    BEFORE UPDATE ON order_meta_crm
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_order_payments_set_updated_at
    BEFORE UPDATE ON order_payments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Additional Foreign Keys (to be added after referenced tables are created)
-- ============================================================================

-- These will be added in later migration files:
-- ALTER TABLE crm_leads ADD CONSTRAINT fk_crm_leads_order_id FOREIGN KEY (order_id) REFERENCES orders(id);
-- ALTER TABLE crm_potential ADD CONSTRAINT fk_crm_potential_converted_to_order_id FOREIGN KEY (converted_to_order_id) REFERENCES orders(id);
-- ALTER TABLE crm_reengage_personal_keys ADD CONSTRAINT fk_crm_reengage_personal_keys_converted_order_id FOREIGN KEY (converted_order_id) REFERENCES orders(id);

