-- ============================================================================
-- Material Domain Module
-- ============================================================================
-- This migration creates tables for material management with variants and stock
-- Dependencies: sys_tenants, sys_users (001_system_tenant.sql),
--               product_attribute (005_product.sql),
--               warehouse (005_product.sql),
--               product (005_product.sql)
-- ============================================================================

-- Drop existing tables (if they exist)
DROP TABLE IF EXISTS material_history CASCADE;
DROP TABLE IF EXISTS material_stock CASCADE;
DROP TABLE IF EXISTS material_variant CASCADE;
DROP TABLE IF EXISTS material_product CASCADE;
DROP TABLE IF EXISTS material_attribute CASCADE;
DROP TABLE IF EXISTS material CASCADE;

-- ----------------------------------------------------------------------------
-- 1. material - Base material table (SHARED fields across all variants)
-- ----------------------------------------------------------------------------

-- Step 1: CREATE TABLE (columns and PRIMARY KEY only)
CREATE TABLE IF NOT EXISTS material (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    sku VARCHAR(100) NOT NULL,
    name VARCHAR(500) NOT NULL,
    category VARCHAR(100) NOT NULL,
    
    -- SHARED fields (common across all variants) - FK to product_attribute
    stone_attribute_id BIGINT NULL,        -- FK to product_attribute (type='stone')
    charm_attribute_id BIGINT NULL,        -- FK to product_attribute (type='charm')
    color_attribute_id BIGINT NULL,        -- FK to product_attribute (type='color')
    intention_attribute_id BIGINT NULL,    -- FK to product_attribute (type='intention')
    element_attribute_id BIGINT NULL,       -- FK to product_attribute (type='element')
    
    -- Common metadata
    thumbnail VARCHAR(500) DEFAULT '',     -- Thumbnail for material (shared by all variants)
    description TEXT DEFAULT '',
    is_active BOOLEAN DEFAULT TRUE,
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by_id BIGINT NULL,
    updated_by_id BIGINT NULL
);

-- Step 2: CHECK constraints
-- (none)

-- Step 3: UNIQUE constraints
ALTER TABLE material 
    ADD CONSTRAINT uq_material_tenant_sku 
    UNIQUE (tenant_id, sku);

-- Step 4: Foreign key constraints
ALTER TABLE material 
    ADD CONSTRAINT fk_material_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id) ON DELETE CASCADE;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_stone_attribute_id 
    FOREIGN KEY (stone_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_charm_attribute_id 
    FOREIGN KEY (charm_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_color_attribute_id 
    FOREIGN KEY (color_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_intention_attribute_id 
    FOREIGN KEY (intention_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_element_attribute_id 
    FOREIGN KEY (element_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_created_by_id 
    FOREIGN KEY (created_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_updated_by_id 
    FOREIGN KEY (updated_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Step 5: Comments
COMMENT ON TABLE material IS 'Base material information - contains SHARED fields (stone, charm, color, intention, element) that are common across all variants';
COMMENT ON COLUMN material.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN material.tenant_id IS 'Multi-tenant support';
COMMENT ON COLUMN material.sku IS 'Material SKU (unique per tenant)';
COMMENT ON COLUMN material.name IS 'Material name';
COMMENT ON COLUMN material.category IS 'Material category';
COMMENT ON COLUMN material.stone_attribute_id IS 'Stone attribute (SHARED - FK to product_attribute where type="stone")';
COMMENT ON COLUMN material.charm_attribute_id IS 'Charm attribute (SHARED - FK to product_attribute where type="charm")';
COMMENT ON COLUMN material.color_attribute_id IS 'Color attribute (SHARED - FK to product_attribute where type="color")';
COMMENT ON COLUMN material.intention_attribute_id IS 'Intention attribute (SHARED - FK to product_attribute where type="intention")';
COMMENT ON COLUMN material.element_attribute_id IS 'Element attribute (SHARED - FK to product_attribute where type="element")';
COMMENT ON COLUMN material.thumbnail IS 'Thumbnail image URL (shared by all variants)';
COMMENT ON COLUMN material.is_active IS 'Material active status';

-- Step 6: Indexes
CREATE INDEX IF NOT EXISTS idx_material_tenant_id ON material(tenant_id);
CREATE INDEX IF NOT EXISTS idx_material_sku ON material(sku);
CREATE INDEX IF NOT EXISTS idx_material_category ON material(category);
CREATE INDEX IF NOT EXISTS idx_material_name ON material(name);
CREATE INDEX IF NOT EXISTS idx_material_stone ON material(stone_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_charm ON material(charm_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_color ON material(color_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_intention ON material(intention_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_element ON material(element_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_is_active ON material(is_active);

-- Step 7: Triggers
-- (see Triggers section at end of file)

-- ----------------------------------------------------------------------------
-- 2. material_attribute - Attribute lookup/master table (optional, for backward compatibility)
-- ----------------------------------------------------------------------------

-- Step 1: CREATE TABLE (columns and PRIMARY KEY only)
CREATE TABLE IF NOT EXISTS material_attribute (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(100) NOT NULL,
    value VARCHAR(300) NOT NULL,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Step 2: CHECK constraints
-- (none)

-- Step 3: UNIQUE constraints
ALTER TABLE material_attribute 
    ADD CONSTRAINT uq_material_attribute_tenant_type_value 
    UNIQUE (tenant_id, type, value);

-- Step 4: Foreign key constraints
ALTER TABLE material_attribute 
    ADD CONSTRAINT fk_material_attribute_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id) ON DELETE CASCADE;

-- Step 5: Comments
COMMENT ON TABLE material_attribute IS 'Material attribute lookup/master table - valid values for collection, stone, metal, size, color, charm, etc. (optional, can use product_attribute instead)';
COMMENT ON COLUMN material_attribute.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN material_attribute.tenant_id IS 'Multi-tenant support';
COMMENT ON COLUMN material_attribute.name IS 'Attribute name (e.g., "Collection", "Stone", "Metal", "Color", "Charm")';
COMMENT ON COLUMN material_attribute.type IS 'Attribute type (e.g., "collection", "stone", "metal", "color", "charm", "size")';
COMMENT ON COLUMN material_attribute.value IS 'Attribute value (e.g., "Spring 2024", "Diamond", "Gold", "Red", "10mm")';
COMMENT ON COLUMN material_attribute.display_order IS 'Display order for UI dropdowns';

-- Step 6: Indexes
CREATE INDEX IF NOT EXISTS idx_material_attribute_tenant_id ON material_attribute(tenant_id);
CREATE INDEX IF NOT EXISTS idx_material_attribute_type ON material_attribute(type);
CREATE INDEX IF NOT EXISTS idx_material_attribute_type_value ON material_attribute(type, value);
CREATE INDEX IF NOT EXISTS idx_material_attribute_is_active ON material_attribute(is_active);

-- Step 7: Triggers
-- (see Triggers section at end of file)

-- ----------------------------------------------------------------------------
-- 3. material_variant - Material variants (UNIQUE fields per variant)
-- ----------------------------------------------------------------------------

-- Step 1: CREATE TABLE (columns and PRIMARY KEY only)
CREATE TABLE IF NOT EXISTS material_variant (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material_id BIGINT NOT NULL,
    sku VARCHAR(100) NOT NULL,
    name VARCHAR(500) NOT NULL,
    
    -- UNIQUE fields (specific to each variant) - FK to product_attribute
    size_attribute_id BIGINT NULL,         -- FK to product_attribute (type='bead_size')
    metal_attribute_id BIGINT NULL,        -- FK to product_attribute (type='metal')
    
    -- UNIQUE fields (specific to each variant) - direct values
    unit VARCHAR(100) NOT NULL,            -- Unit of measurement (e.g., "piece", "gram", "meter")
    
    -- Dimension (UNIQUE per variant) - single column only
    dimension VARCHAR(100) NULL,           -- Dimension value (e.g., "10x8x5", "6.7x5.1x2.6", "10mm")
    
    -- Pricing (UNIQUE per variant)
    price NUMERIC(12,2) NOT NULL DEFAULT 0,
    cost NUMERIC(12,2) NOT NULL DEFAULT 0,
    
    -- Physical properties (UNIQUE per variant)
    weight NUMERIC(10,3) NULL,
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by_id BIGINT NULL,
    updated_by_id BIGINT NULL
);

-- Step 2: CHECK constraints
ALTER TABLE material_variant 
    ADD CONSTRAINT chk_material_variant_price 
    CHECK (price >= 0);

ALTER TABLE material_variant 
    ADD CONSTRAINT chk_material_variant_cost 
    CHECK (cost >= 0);

ALTER TABLE material_variant 
    ADD CONSTRAINT chk_material_variant_weight 
    CHECK (weight IS NULL OR weight > 0);

-- Step 3: UNIQUE constraints
ALTER TABLE material_variant 
    ADD CONSTRAINT uq_material_variant_sku 
    UNIQUE (sku);

-- Step 4: Foreign key constraints
ALTER TABLE material_variant 
    ADD CONSTRAINT fk_material_variant_material_id 
    FOREIGN KEY (material_id) REFERENCES material(id) ON DELETE CASCADE;
    
ALTER TABLE material_variant 
    ADD CONSTRAINT fk_material_variant_size_attribute_id 
    FOREIGN KEY (size_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material_variant 
    ADD CONSTRAINT fk_material_variant_metal_attribute_id 
    FOREIGN KEY (metal_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material_variant 
    ADD CONSTRAINT fk_material_variant_created_by_id 
    FOREIGN KEY (created_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;
    
ALTER TABLE material_variant 
    ADD CONSTRAINT fk_material_variant_updated_by_id 
    FOREIGN KEY (updated_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Step 5: Comments
COMMENT ON TABLE material_variant IS 'Material variants - contains UNIQUE fields (size, metal, unit, dimension, price, cost, weight) that differ per variant';
COMMENT ON COLUMN material_variant.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN material_variant.material_id IS 'Base material ID (FK to material table)';
COMMENT ON COLUMN material_variant.sku IS 'Variant SKU (unique)';
COMMENT ON COLUMN material_variant.name IS 'Variant name (e.g., "Gold 10mm")';
COMMENT ON COLUMN material_variant.size_attribute_id IS 'Size/bead_size attribute (UNIQUE - FK to product_attribute where type="bead_size")';
COMMENT ON COLUMN material_variant.metal_attribute_id IS 'Metal attribute (UNIQUE - FK to product_attribute where type="metal")';
COMMENT ON COLUMN material_variant.unit IS 'Unit of measurement for this variant (UNIQUE per variant)';
COMMENT ON COLUMN material_variant.dimension IS 'Dimension value (UNIQUE per variant) - can store formats like "10x8x5", "6.7x5.1x2.6", "10mm", etc.';
COMMENT ON COLUMN material_variant.price IS 'Variant-specific price (UNIQUE per variant)';
COMMENT ON COLUMN material_variant.cost IS 'Variant-specific cost (UNIQUE per variant)';
COMMENT ON COLUMN material_variant.weight IS 'Variant-specific weight (UNIQUE per variant)';

-- Step 6: Indexes
CREATE INDEX IF NOT EXISTS idx_material_variant_material_id ON material_variant(material_id);
CREATE INDEX IF NOT EXISTS idx_material_variant_sku ON material_variant(sku);
CREATE INDEX IF NOT EXISTS idx_material_variant_size ON material_variant(size_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_variant_metal ON material_variant(metal_attribute_id);

-- Step 7: Triggers
-- (see Triggers section at end of file)

-- ----------------------------------------------------------------------------
-- 4. material_stock - Stock by warehouse/location (UNIQUE per variant)
-- ----------------------------------------------------------------------------

-- Step 1: CREATE TABLE (columns and PRIMARY KEY only)
CREATE TABLE IF NOT EXISTS material_stock (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material_id BIGINT NULL,
    material_variant_id BIGINT NULL,
    warehouse_id BIGINT NOT NULL,
    quantity NUMERIC(10,2) NOT NULL DEFAULT 0,
    conversion_factor NUMERIC(10,3) NULL,   -- Conversion factor (e.g., beads per unit)
    total_converted_quantity NUMERIC(10,2) GENERATED ALWAYS AS (quantity * COALESCE(conversion_factor, 0)) STORED,
    inbound NUMERIC(10,2) NOT NULL DEFAULT 0,
    outbound NUMERIC(10,2) NOT NULL DEFAULT 0,
    last_counted_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by_id BIGINT NULL
);

-- Step 2: CHECK constraints
ALTER TABLE material_stock 
    ADD CONSTRAINT chk_material_stock_quantity 
    CHECK (quantity >= 0);

ALTER TABLE material_stock 
    ADD CONSTRAINT chk_material_stock_conversion_factor 
    CHECK (conversion_factor IS NULL OR conversion_factor >= 0);

ALTER TABLE material_stock 
    ADD CONSTRAINT chk_material_stock_inbound 
    CHECK (inbound >= 0);

ALTER TABLE material_stock 
    ADD CONSTRAINT chk_material_stock_outbound 
    CHECK (outbound >= 0);

ALTER TABLE material_stock 
    ADD CONSTRAINT chk_material_stock_material_or_variant 
    CHECK (
        (material_id IS NOT NULL AND material_variant_id IS NULL) OR 
        (material_id IS NULL AND material_variant_id IS NOT NULL)
    );

-- Step 3: UNIQUE constraints
ALTER TABLE material_stock 
    ADD CONSTRAINT uq_material_stock_material_warehouse 
    UNIQUE (material_id, warehouse_id);

ALTER TABLE material_stock 
    ADD CONSTRAINT uq_material_stock_variant_warehouse 
    UNIQUE (material_variant_id, warehouse_id);

-- Step 4: Foreign key constraints
ALTER TABLE material_stock 
    ADD CONSTRAINT fk_material_stock_material_id 
    FOREIGN KEY (material_id) REFERENCES material(id) ON DELETE CASCADE;
    
ALTER TABLE material_stock 
    ADD CONSTRAINT fk_material_stock_material_variant_id 
    FOREIGN KEY (material_variant_id) REFERENCES material_variant(id) ON DELETE CASCADE;
    
ALTER TABLE material_stock 
    ADD CONSTRAINT fk_material_stock_warehouse_id 
    FOREIGN KEY (warehouse_id) REFERENCES warehouse(id) ON DELETE CASCADE;
    
ALTER TABLE material_stock 
    ADD CONSTRAINT fk_material_stock_updated_by_id 
    FOREIGN KEY (updated_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Step 5: Comments
COMMENT ON TABLE material_stock IS 'Material stock by warehouse/location - supports both base materials and variants (stock is UNIQUE per variant)';
COMMENT ON COLUMN material_stock.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN material_stock.material_id IS 'Base material ID (if stock is for base material without variants)';
COMMENT ON COLUMN material_stock.material_variant_id IS 'Material variant ID (if stock is for variant - most common case)';
COMMENT ON COLUMN material_stock.warehouse_id IS 'Warehouse ID (FK to warehouse table)';
COMMENT ON COLUMN material_stock.quantity IS 'Total stock quantity (UNIQUE per variant+warehouse)';
COMMENT ON COLUMN material_stock.conversion_factor IS 'Conversion factor (e.g., beads per unit, pieces per box)';
COMMENT ON COLUMN material_stock.total_converted_quantity IS 'Total converted quantity (computed: quantity * conversion_factor)';
COMMENT ON COLUMN material_stock.inbound IS 'Inbound quantity';
COMMENT ON COLUMN material_stock.outbound IS 'Outbound quantity';
COMMENT ON COLUMN material_stock.last_counted_at IS 'Last physical count date';

-- Step 6: Indexes
CREATE INDEX IF NOT EXISTS idx_material_stock_material_id ON material_stock(material_id);
CREATE INDEX IF NOT EXISTS idx_material_stock_material_variant_id ON material_stock(material_variant_id);
CREATE INDEX IF NOT EXISTS idx_material_stock_warehouse_id ON material_stock(warehouse_id);

-- Step 7: Triggers
-- (see Triggers section at end of file)

-- ----------------------------------------------------------------------------
-- 5. material_history - Audit trail for material changes
-- ----------------------------------------------------------------------------

-- Step 1: CREATE TABLE (columns and PRIMARY KEY only)
CREATE TABLE IF NOT EXISTS material_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material_id BIGINT NULL,
    material_variant_id BIGINT NULL,
    material_stock_id BIGINT NULL,
    action_type VARCHAR(50) NOT NULL,
    field_name VARCHAR(100) NULL,
    old_value TEXT NULL,
    new_value TEXT NULL,
    quantity_change NUMERIC(10,2) NULL,
    reference_type VARCHAR(50) NULL,
    reference_id BIGINT NULL,
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by_id BIGINT NULL
);

-- Step 2: CHECK constraints
ALTER TABLE material_history 
    ADD CONSTRAINT chk_material_history_action_type 
    CHECK (
        action_type IN ('create', 'update', 'delete', 'stock_in', 'stock_out', 'stock_adjust', 'reserve', 'unreserve', 'transfer')
    );

ALTER TABLE material_history 
    ADD CONSTRAINT chk_material_history_reference_type 
    CHECK (
        reference_type IS NULL OR reference_type IN ('order', 'production', 'purchase', 'adjustment', 'transfer', 'product')
    );

-- Step 3: UNIQUE constraints
-- (none)

-- Step 4: Foreign key constraints
ALTER TABLE material_history 
    ADD CONSTRAINT fk_material_history_material_id 
    FOREIGN KEY (material_id) REFERENCES material(id) ON DELETE SET NULL;
    
ALTER TABLE material_history 
    ADD CONSTRAINT fk_material_history_material_variant_id 
    FOREIGN KEY (material_variant_id) REFERENCES material_variant(id) ON DELETE SET NULL;
    
ALTER TABLE material_history 
    ADD CONSTRAINT fk_material_history_material_stock_id 
    FOREIGN KEY (material_stock_id) REFERENCES material_stock(id) ON DELETE SET NULL;
    
ALTER TABLE material_history 
    ADD CONSTRAINT fk_material_history_created_by_id 
    FOREIGN KEY (created_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Step 5: Comments
COMMENT ON TABLE material_history IS 'Audit trail for all material changes - tracks create, update, delete, stock movements, and reservations';
COMMENT ON COLUMN material_history.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN material_history.material_id IS 'Base material ID (if change is for base material)';
COMMENT ON COLUMN material_history.material_variant_id IS 'Material variant ID (if change is for variant)';
COMMENT ON COLUMN material_history.material_stock_id IS 'Material stock ID (if change is for stock)';
COMMENT ON COLUMN material_history.action_type IS 'Action type: create, update, delete, stock_in, stock_out, stock_adjust, reserve, unreserve, transfer';
COMMENT ON COLUMN material_history.field_name IS 'Field name that changed (for update actions)';
COMMENT ON COLUMN material_history.old_value IS 'Old value (for update actions)';
COMMENT ON COLUMN material_history.new_value IS 'New value (for update actions)';
COMMENT ON COLUMN material_history.quantity_change IS 'Quantity change (for stock actions)';
COMMENT ON COLUMN material_history.reference_type IS 'Reference type: order, production, purchase, adjustment, transfer, product';
COMMENT ON COLUMN material_history.reference_id IS 'Reference ID (e.g., order_id, production_id)';
COMMENT ON COLUMN material_history.notes IS 'Additional notes';

-- Step 6: Indexes
CREATE INDEX IF NOT EXISTS idx_material_history_material_id ON material_history(material_id);
CREATE INDEX IF NOT EXISTS idx_material_history_material_variant_id ON material_history(material_variant_id);
CREATE INDEX IF NOT EXISTS idx_material_history_material_stock_id ON material_history(material_stock_id);
CREATE INDEX IF NOT EXISTS idx_material_history_action_type ON material_history(action_type);
CREATE INDEX IF NOT EXISTS idx_material_history_created_at ON material_history(created_at);
CREATE INDEX IF NOT EXISTS idx_material_history_reference ON material_history(reference_type, reference_id) WHERE reference_type IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_material_history_created_by_id ON material_history(created_by_id);

-- Step 7: Triggers
-- (see Triggers section at end of file)

-- ----------------------------------------------------------------------------
-- 6. material_product - BOM tracking (materials/variants used in products)
-- ----------------------------------------------------------------------------

-- Step 1: CREATE TABLE (columns and PRIMARY KEY only)
CREATE TABLE IF NOT EXISTS material_product (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,              -- For shared attributes (stone, charm, color, intention, element)
    material_variant_id BIGINT NOT NULL,       -- For stock management and unique attributes (size, metal, unit, dimension, price, cost, weight)
    quantity NUMERIC(10,3) NOT NULL,
    unit VARCHAR(100) NOT NULL,
    is_inbound BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Step 2: CHECK constraints
ALTER TABLE material_product 
    ADD CONSTRAINT chk_material_product_quantity 
    CHECK (quantity > 0);

ALTER TABLE material_product 
    ADD CONSTRAINT chk_material_product_variant_belongs_to_material 
    CHECK (
        EXISTS (
            SELECT 1 FROM material_variant mv 
            WHERE mv.id = material_variant_id 
            AND mv.material_id = material_product.material_id
        )
    );

-- Step 3: UNIQUE constraints
-- (none - allow multiple entries for same product+variant if needed)

-- Step 4: Foreign key constraints
ALTER TABLE material_product 
    ADD CONSTRAINT fk_material_product_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
    
ALTER TABLE material_product 
    ADD CONSTRAINT fk_material_product_material_id 
    FOREIGN KEY (material_id) REFERENCES material(id) ON DELETE CASCADE;
    
ALTER TABLE material_product 
    ADD CONSTRAINT fk_material_product_material_variant_id 
    FOREIGN KEY (material_variant_id) REFERENCES material_variant(id) ON DELETE CASCADE;

-- Step 5: Comments
COMMENT ON TABLE material_product IS 'Bill of Materials (BOM) - materials/variants used in products';
COMMENT ON COLUMN material_product.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN material_product.product_id IS 'Product ID';
COMMENT ON COLUMN material_product.material_id IS 'Base material ID - used to get SHARED attributes (stone, charm, color, intention, element)';
COMMENT ON COLUMN material_product.material_variant_id IS 'Material variant ID - used for stock management and to get UNIQUE attributes (size, metal, unit, dimension, price, cost, weight)';
COMMENT ON COLUMN material_product.quantity IS 'Quantity of material variant needed per product';
COMMENT ON COLUMN material_product.unit IS 'Unit of measurement';
COMMENT ON COLUMN material_product.is_inbound IS 'Whether this is inbound material (material per product)';

-- Step 6: Indexes
CREATE INDEX IF NOT EXISTS idx_material_product_product_id ON material_product(product_id);
CREATE INDEX IF NOT EXISTS idx_material_product_material_id ON material_product(material_id);
CREATE INDEX IF NOT EXISTS idx_material_product_material_variant_id ON material_product(material_variant_id);
CREATE INDEX IF NOT EXISTS idx_material_product_product_material ON material_product(product_id, material_id);
CREATE INDEX IF NOT EXISTS idx_material_product_product_variant ON material_product(product_id, material_variant_id);

-- Step 7: Triggers
-- (see Triggers section at end of file)

-- ============================================================================
-- Triggers
-- ============================================================================

-- Auto-update updated_at timestamp (reuse function from 001_system_tenant.sql)
-- If function doesn't exist, create it
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_material_updated_at
    BEFORE UPDATE ON material
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_material_attribute_updated_at
    BEFORE UPDATE ON material_attribute
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_material_variant_updated_at
    BEFORE UPDATE ON material_variant
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_material_stock_updated_at
    BEFORE UPDATE ON material_stock
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_material_product_updated_at
    BEFORE UPDATE ON material_product
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Notes
-- ============================================================================

-- 1. Material Structure
--    - material: Base material with SHARED attributes (stone, charm, color, intention, element)
--    - material_variant: Variants with UNIQUE attributes (size, metal, unit, dimension, price, cost, weight)
--    - material_stock: Stock managed per variant+warehouse
--    - material_product: BOM linking products to material variants (uses both material_id and material_variant_id)

-- 2. Stock Management
--    - Stock is managed at variant level (material_stock.material_variant_id)
--    - total_converted_quantity is computed: quantity * conversion_factor
--    - Supports both base materials and variants (via CHECK constraint)

-- 3. Product Material Relationship
--    - material_product uses material_id to get SHARED attributes
--    - material_product uses material_variant_id for stock management and UNIQUE attributes
--    - CHECK constraint ensures variant belongs to the specified material

-- 4. Attribute References
--    - Shared attributes (stone, charm, color, intention, element) reference product_attribute
--    - Unique attributes (size, metal) also reference product_attribute
--    - This ensures data consistency across the system

-- 5. Unit Management
--    - unit is stored in material_variant (not in material_stock) to avoid data duplication
--    - Stock only manages quantities, not units

