-- ============================================================================
-- Product Domain Module
-- ============================================================================
-- This migration creates tables for product catalog, categories, variants, materials, and reviews
-- Dependencies: sys_tenants, sys_users (001_system_tenant.sql),
--               crm_personal_keys (003_crm_customer.sql),
--               promotion (will be created later in 007_marketing_campaigns.sql)
-- Note: Inventory audit tables are in 006_inventory_audit.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. category
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS category (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) NOT NULL,
    parent_id BIGINT DEFAULT 0,
    
    CONSTRAINT fk_category_parent_id 
        FOREIGN KEY (parent_id) REFERENCES category(id)
);

COMMENT ON TABLE category IS 'Product categories with hierarchical structure (self-referencing parent_id)';
COMMENT ON COLUMN category.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN category.name IS 'Category name';
COMMENT ON COLUMN category.parent_id IS 'Parent category ID (0 = root category, self-referencing)';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_category_parent_id ON category(parent_id);
CREATE INDEX IF NOT EXISTS idx_category_name ON category(name);

-- ----------------------------------------------------------------------------
-- 2. product
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sku VARCHAR(100) NOT NULL,
    name VARCHAR(500) NOT NULL,
    product_type VARCHAR(50) DEFAULT 'standard',
    retail_price NUMERIC(12,2) DEFAULT 0,
    sale_price NUMERIC(12,2) DEFAULT 0,
    description_en TEXT DEFAULT '',
    description_vn TEXT DEFAULT '',
    is_pre_order BOOLEAN DEFAULT FALSE,
    promotion_id INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by_id BIGINT NULL,
    updated_by_id BIGINT NULL,
    status VARCHAR(50) DEFAULT 'draft',
    published_at TIMESTAMPTZ NULL,
    
    CONSTRAINT uq_product_sku UNIQUE (sku),
    CONSTRAINT chk_product_type CHECK (product_type IN ('standard', 'custom', 'variant', 'set', 'jewelry', 'diamond', 'gemstone')),
    CONSTRAINT chk_product_status CHECK (status IN ('draft', 'publish', 'updated', 'do_not_import')),
    CONSTRAINT chk_product_prices CHECK (retail_price >= 0 AND sale_price >= 0)
);

COMMENT ON TABLE product IS 'Main product catalog - core product information';
COMMENT ON COLUMN product.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN product.sku IS 'Stock Keeping Unit - unique product identifier';
COMMENT ON COLUMN product.name IS 'Product name';
COMMENT ON COLUMN product.product_type IS 'Product type: standard, custom, variant, set, jewelry, diamond, gemstone';
COMMENT ON COLUMN product.retail_price IS 'Retail price (NUMERIC for precision)';
COMMENT ON COLUMN product.sale_price IS 'Sale price (NUMERIC for precision)';
COMMENT ON COLUMN product.description_en IS 'English description';
COMMENT ON COLUMN product.description_vn IS 'Vietnamese description';
COMMENT ON COLUMN product.is_pre_order IS 'Whether product is available for pre-order';
COMMENT ON COLUMN product.promotion_id IS 'Active promotion ID (FK to promotion table, added later)';
COMMENT ON COLUMN product.status IS 'Product status: draft, publish, updated, do_not_import';
COMMENT ON COLUMN product.published_at IS 'Date when product was published (NULL if not published yet)';
COMMENT ON COLUMN product.created_by_id IS 'Staff who created the product';
COMMENT ON COLUMN product.updated_by_id IS 'Staff who last updated the product';

-- Foreign Keys
ALTER TABLE product 
    ADD CONSTRAINT fk_product_created_by_id 
    FOREIGN KEY (created_by_id) REFERENCES sys_users(id);
    
ALTER TABLE product 
    ADD CONSTRAINT fk_product_updated_by_id 
    FOREIGN KEY (updated_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Note: promotion_id FK will be added after promotion table is created
-- ALTER TABLE product 
--     ADD CONSTRAINT fk_product_promotion_id 
--     FOREIGN KEY (promotion_id) REFERENCES promotion(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_product_sku ON product(sku);
CREATE INDEX IF NOT EXISTS idx_product_name ON product(name);
CREATE INDEX IF NOT EXISTS idx_product_type ON product(product_type);
CREATE INDEX IF NOT EXISTS idx_product_price ON product(retail_price, sale_price);
CREATE INDEX IF NOT EXISTS idx_product_status ON product(status);
CREATE INDEX IF NOT EXISTS idx_product_published_at ON product(published_at);

-- ----------------------------------------------------------------------------
-- 3. product_category
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_category (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT uq_product_category_product_category UNIQUE (product_id, category_id)
);

COMMENT ON TABLE product_category IS 'Junction table linking products to categories (normalized from comma-separated category field)';
COMMENT ON COLUMN product_category.product_id IS 'Product ID';
COMMENT ON COLUMN product_category.category_id IS 'Category ID';

-- Foreign Keys
ALTER TABLE product_category 
    ADD CONSTRAINT fk_product_category_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
    
ALTER TABLE product_category 
    ADD CONSTRAINT fk_product_category_category_id 
    FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_product_category_product ON product_category(product_id);
CREATE INDEX IF NOT EXISTS idx_product_category_category ON product_category(category_id);

-- ----------------------------------------------------------------------------
-- 4. product_tag
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_tag (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    tag_name VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT uq_product_tag_product_tag UNIQUE (product_id, tag_name)
);

COMMENT ON TABLE product_tag IS 'Junction table for product tags (normalized from comma-separated tag field)';
COMMENT ON COLUMN product_tag.product_id IS 'Product ID';
COMMENT ON COLUMN product_tag.tag_name IS 'Tag name';

-- Foreign Keys
ALTER TABLE product_tag 
    ADD CONSTRAINT fk_product_tag_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_product_tag_product ON product_tag(product_id);
CREATE INDEX IF NOT EXISTS idx_product_tag_tag_name ON product_tag(tag_name);

-- ----------------------------------------------------------------------------
-- 5. warehouse
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS warehouse (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(10) NOT NULL,
    name VARCHAR(200) NOT NULL,
    address TEXT NULL,
    city VARCHAR(100) NULL,
    country VARCHAR(100) NULL,
    phone VARCHAR(50) NULL,
    email VARCHAR(200) NULL,
    manager_id BIGINT NULL,
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by_id BIGINT NULL,
    updated_by_id BIGINT NULL,
    
    CONSTRAINT uq_warehouse_code UNIQUE (code),
    CONSTRAINT chk_warehouse_status CHECK (status IN ('active', 'inactive', 'closed'))
);

COMMENT ON TABLE warehouse IS 'Warehouse/Location master data';
COMMENT ON COLUMN warehouse.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN warehouse.code IS 'Warehouse code (e.g., ''VN'', ''US'', ''WH-001'')';
COMMENT ON COLUMN warehouse.name IS 'Warehouse name';
COMMENT ON COLUMN warehouse.manager_id IS 'Warehouse manager (staff)';
COMMENT ON COLUMN warehouse.status IS 'Warehouse status: active, inactive, closed';

-- Foreign Keys
ALTER TABLE warehouse 
    ADD CONSTRAINT fk_warehouse_manager_id 
    FOREIGN KEY (manager_id) REFERENCES sys_users(id) ON DELETE SET NULL;
    
ALTER TABLE warehouse 
    ADD CONSTRAINT fk_warehouse_created_by_id 
    FOREIGN KEY (created_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;
    
ALTER TABLE warehouse 
    ADD CONSTRAINT fk_warehouse_updated_by_id 
    FOREIGN KEY (updated_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_warehouse_code ON warehouse(code);
CREATE INDEX IF NOT EXISTS idx_warehouse_name ON warehouse(name);
CREATE INDEX IF NOT EXISTS idx_warehouse_status ON warehouse(status);
CREATE INDEX IF NOT EXISTS idx_warehouse_manager ON warehouse(manager_id);

-- ----------------------------------------------------------------------------
-- 6. stock
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stock (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_sku VARCHAR(100) NOT NULL,
    warehouse_id BIGINT NOT NULL,
    qty INTEGER DEFAULT 0,
    outbound INTEGER DEFAULT 0,
    inbound INTEGER DEFAULT 0,
    name_product VARCHAR(500) NOT NULL,
    updated_by_id BIGINT NULL,
    time_group_sku TIMESTAMPTZ DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT uq_stock_product_sku_warehouse UNIQUE (product_sku, warehouse_id),
    CONSTRAINT chk_stock_qty CHECK (qty >= 0),
    CONSTRAINT chk_stock_outbound CHECK (outbound >= 0),
    CONSTRAINT chk_stock_inbound CHECK (inbound >= 0)
);

COMMENT ON TABLE stock IS 'Inventory stock levels per warehouse';
COMMENT ON COLUMN stock.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN stock.product_sku IS 'Product SKU (soft FK to product.sku)';
COMMENT ON COLUMN stock.warehouse_id IS 'Warehouse ID (FK)';
COMMENT ON COLUMN stock.qty IS 'Current quantity in stock';
COMMENT ON COLUMN stock.outbound IS 'Outbound quantity (shipped/transferred)';
COMMENT ON COLUMN stock.inbound IS 'Inbound quantity (expected/coming)';
COMMENT ON COLUMN stock.name_product IS 'Product name (denormalized for performance)';
COMMENT ON COLUMN stock.time_group_sku IS 'Time grouping for SKU rendering';

-- Foreign Keys
ALTER TABLE stock 
    ADD CONSTRAINT fk_stock_warehouse_id 
    FOREIGN KEY (warehouse_id) REFERENCES warehouse(id) ON DELETE CASCADE;
    
ALTER TABLE stock 
    ADD CONSTRAINT fk_stock_updated_by_id 
    FOREIGN KEY (updated_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_stock_product_sku ON stock(product_sku);
CREATE INDEX IF NOT EXISTS idx_stock_warehouse ON stock(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_stock_product_sku_warehouse ON stock(product_sku, warehouse_id);
CREATE INDEX IF NOT EXISTS idx_stock_time_group_sku ON stock(time_group_sku);

-- ----------------------------------------------------------------------------
-- 7. product_attribute
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_attribute (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(300) NOT NULL,
    type VARCHAR(100) NOT NULL,
    value VARCHAR(300) DEFAULT '',
    description_en VARCHAR(1000) DEFAULT '',
    description_vn VARCHAR(1000) DEFAULT '',
    
    CONSTRAINT uq_product_attribute_name UNIQUE (name)
);

COMMENT ON TABLE product_attribute IS 'Product attribute definitions (master table) - defines attribute types like Color, Size, Material';
COMMENT ON COLUMN product_attribute.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN product_attribute.name IS 'Attribute name (e.g., "Color", "Size", "Material")';
COMMENT ON COLUMN product_attribute.type IS 'Attribute type (e.g., "text", "number", "select")';
COMMENT ON COLUMN product_attribute.value IS 'Default/example value (not product-specific)';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_product_attribute_name ON product_attribute(name);
CREATE INDEX IF NOT EXISTS idx_product_attribute_type ON product_attribute(type);

-- ----------------------------------------------------------------------------
-- 8. product_attribute_value
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_attribute_value (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    attribute_id BIGINT NOT NULL,
    value VARCHAR(500) NOT NULL,
    is_variant_value BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT uq_product_attribute_value_product_attribute UNIQUE (product_id, attribute_id)
);

COMMENT ON TABLE product_attribute_value IS 'Junction table linking products to their attribute values (normalized from multiple attribute columns)';
COMMENT ON COLUMN product_attribute_value.product_id IS 'Product ID';
COMMENT ON COLUMN product_attribute_value.attribute_id IS 'Attribute ID';
COMMENT ON COLUMN product_attribute_value.value IS 'The actual attribute value for this product';
COMMENT ON COLUMN product_attribute_value.is_variant_value IS 'If TRUE, this attribute value is used as variant identifier for SKU generation';

-- Foreign Keys
ALTER TABLE product_attribute_value 
    ADD CONSTRAINT fk_product_attribute_value_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
    
ALTER TABLE product_attribute_value 
    ADD CONSTRAINT fk_product_attribute_value_attribute_id 
    FOREIGN KEY (attribute_id) REFERENCES product_attribute(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_product_attribute_value_product ON product_attribute_value(product_id);
CREATE INDEX IF NOT EXISTS idx_product_attribute_value_attribute ON product_attribute_value(attribute_id);
CREATE INDEX IF NOT EXISTS idx_product_attribute_value_product_attribute ON product_attribute_value(product_id, attribute_id);
CREATE INDEX IF NOT EXISTS idx_product_attribute_value_variant ON product_attribute_value(is_variant_value) WHERE is_variant_value = TRUE;

-- ----------------------------------------------------------------------------
-- 9. product_set_item
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_set_item (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    set_product_id BIGINT NOT NULL,
    item_product_id BIGINT NOT NULL,
    quantity INTEGER DEFAULT 1,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT uq_product_set_item_set_item UNIQUE (set_product_id, item_product_id),
    CONSTRAINT chk_product_set_item_quantity CHECK (quantity > 0)
);

COMMENT ON TABLE product_set_item IS 'Junction table linking set/bundle products to their component items';
COMMENT ON COLUMN product_set_item.set_product_id IS 'Parent product (set/bundle/composite)';
COMMENT ON COLUMN product_set_item.item_product_id IS 'Child product (component item)';
COMMENT ON COLUMN product_set_item.quantity IS 'Quantity of item in set';
COMMENT ON COLUMN product_set_item.sort_order IS 'Display order of items';

-- Foreign Keys
ALTER TABLE product_set_item 
    ADD CONSTRAINT fk_product_set_item_set_product_id 
    FOREIGN KEY (set_product_id) REFERENCES product(id) ON DELETE CASCADE;
    
ALTER TABLE product_set_item 
    ADD CONSTRAINT fk_product_set_item_item_product_id 
    FOREIGN KEY (item_product_id) REFERENCES product(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_product_set_item_set ON product_set_item(set_product_id);
CREATE INDEX IF NOT EXISTS idx_product_set_item_item ON product_set_item(item_product_id);

-- ----------------------------------------------------------------------------
-- 10. product_variant
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_variant (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_product_id BIGINT NOT NULL,
    variant_product_id BIGINT NOT NULL,
    variant_attribute VARCHAR(100) NOT NULL,
    variant_value VARCHAR(100) NOT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT uq_product_variant_parent_attribute_value UNIQUE (parent_product_id, variant_attribute, variant_value),
    CONSTRAINT uq_product_variant_variant_product UNIQUE (variant_product_id)
);

COMMENT ON TABLE product_variant IS 'Junction table linking variant parent products to their variant children';
COMMENT ON COLUMN product_variant.parent_product_id IS 'Parent product (variant parent)';
COMMENT ON COLUMN product_variant.variant_product_id IS 'Child product (variant instance)';
COMMENT ON COLUMN product_variant.variant_attribute IS 'Attribute name (e.g., "Size", "Color")';
COMMENT ON COLUMN product_variant.variant_value IS 'Attribute value (e.g., "S", "M", "L", "Red", "Blue")';

-- Foreign Keys
ALTER TABLE product_variant 
    ADD CONSTRAINT fk_product_variant_parent_product_id 
    FOREIGN KEY (parent_product_id) REFERENCES product(id) ON DELETE CASCADE;
    
ALTER TABLE product_variant 
    ADD CONSTRAINT fk_product_variant_variant_product_id 
    FOREIGN KEY (variant_product_id) REFERENCES product(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_product_variant_parent ON product_variant(parent_product_id);
CREATE INDEX IF NOT EXISTS idx_product_variant_variant ON product_variant(variant_product_id);
CREATE INDEX IF NOT EXISTS idx_product_variant_attribute ON product_variant(variant_attribute, variant_value);

-- ----------------------------------------------------------------------------
-- 11. product_image
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_image (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    thumbnail VARCHAR(1000) DEFAULT '',
    gallery TEXT DEFAULT '',
    updated_by_id BIGINT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT uq_product_image_product_id UNIQUE (product_id)
);

COMMENT ON TABLE product_image IS 'Product images, thumbnails, and gallery (normalized from thumb_nail, name_image columns)';
COMMENT ON COLUMN product_image.product_id IS 'Product ID (one-to-one relationship)';
COMMENT ON COLUMN product_image.thumbnail IS 'Thumbnail image URL';
COMMENT ON COLUMN product_image.gallery IS 'Gallery images as JSON array or comma-separated URLs';

-- Foreign Keys
ALTER TABLE product_image 
    ADD CONSTRAINT fk_product_image_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
    
ALTER TABLE product_image 
    ADD CONSTRAINT fk_product_image_updated_by_id 
    FOREIGN KEY (updated_by_id) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_product_image_product ON product_image(product_id);

-- ----------------------------------------------------------------------------
-- 12. diamond
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS diamond (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    item_id VARCHAR(100) NULL,
    shape VARCHAR(100) DEFAULT '',
    cut_grade VARCHAR(50) DEFAULT '',
    carat NUMERIC(5,3) DEFAULT 0,
    color VARCHAR(50) DEFAULT '',
    clarity VARCHAR(50) DEFAULT '',
    grading_lab VARCHAR(100) DEFAULT '',
    certificate_number VARCHAR(100) NULL,
    certificate_path VARCHAR(1000) DEFAULT '',
    image_path VARCHAR(1000) DEFAULT '',
    total_price NUMERIC(12,2) DEFAULT 0,
    measurement_length NUMERIC(6,2) DEFAULT 0,
    measurement_width NUMERIC(6,2) DEFAULT 0,
    measurement_height NUMERIC(6,2) DEFAULT 0,
    country VARCHAR(100) DEFAULT '',
    state_region VARCHAR(100) DEFAULT '',
    guaranteed_availability BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT uq_diamond_product_id UNIQUE (product_id),
    CONSTRAINT uq_diamond_item_id UNIQUE (item_id) WHERE item_id IS NOT NULL,
    CONSTRAINT uq_diamond_certificate_number UNIQUE (certificate_number) WHERE certificate_number IS NOT NULL,
    CONSTRAINT chk_diamond_carat CHECK (carat > 0)
);

COMMENT ON TABLE diamond IS 'Certified diamond specifications (optional, one-to-one with product for product_type=''diamond'')';
COMMENT ON COLUMN diamond.product_id IS 'Product ID (one-to-one, only for certified diamonds)';
COMMENT ON COLUMN diamond.item_id IS 'External Item ID';
COMMENT ON COLUMN diamond.carat IS 'Carat weight';
COMMENT ON COLUMN diamond.certificate_number IS 'Certificate number (e.g., GIA, IGI)';

-- Foreign Keys
ALTER TABLE diamond 
    ADD CONSTRAINT fk_diamond_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_diamond_product_id ON diamond(product_id);
CREATE INDEX IF NOT EXISTS idx_diamond_item_id ON diamond(item_id) WHERE item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_diamond_certificate_number ON diamond(certificate_number) WHERE certificate_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_diamond_carat ON diamond(carat);
CREATE INDEX IF NOT EXISTS idx_diamond_color ON diamond(color);
CREATE INDEX IF NOT EXISTS idx_diamond_clarity ON diamond(clarity);
CREATE INDEX IF NOT EXISTS idx_diamond_shape ON diamond(shape);
CREATE INDEX IF NOT EXISTS idx_diamond_cut_grade ON diamond(cut_grade);
CREATE INDEX IF NOT EXISTS idx_diamond_grading_lab ON diamond(grading_lab);

-- ----------------------------------------------------------------------------
-- 13. gemstone
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gemstone (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    item_id VARCHAR(100) NULL,
    shape VARCHAR(100) DEFAULT '',
    cut_grade VARCHAR(50) DEFAULT '',
    carat NUMERIC(5,3) DEFAULT 0,
    color VARCHAR(50) DEFAULT '',
    clarity VARCHAR(50) DEFAULT '',
    grading_lab VARCHAR(100) DEFAULT '',
    certificate_number VARCHAR(100) NULL,
    certificate_path VARCHAR(1000) DEFAULT '',
    image_path VARCHAR(1000) DEFAULT '',
    total_price NUMERIC(12,2) DEFAULT 0,
    measurement_length NUMERIC(6,2) DEFAULT 0,
    measurement_width NUMERIC(6,2) DEFAULT 0,
    measurement_height NUMERIC(6,2) DEFAULT 0,
    country VARCHAR(100) DEFAULT '',
    state_region VARCHAR(100) DEFAULT '',
    guaranteed_availability BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT uq_gemstone_product_id UNIQUE (product_id),
    CONSTRAINT uq_gemstone_item_id UNIQUE (item_id) WHERE item_id IS NOT NULL,
    CONSTRAINT uq_gemstone_certificate_number UNIQUE (certificate_number) WHERE certificate_number IS NOT NULL,
    CONSTRAINT chk_gemstone_carat CHECK (carat > 0)
);

COMMENT ON TABLE gemstone IS 'Certified gemstone specifications (optional, one-to-one with product for product_type=''gemstone'')';
COMMENT ON COLUMN gemstone.product_id IS 'Product ID (one-to-one, only for certified gemstones)';
COMMENT ON COLUMN gemstone.item_id IS 'External Item ID';
COMMENT ON COLUMN gemstone.carat IS 'Carat weight';
COMMENT ON COLUMN gemstone.certificate_number IS 'Certificate number (e.g., GIA, IGI)';

-- Foreign Keys
ALTER TABLE gemstone 
    ADD CONSTRAINT fk_gemstone_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_gemstone_product_id ON gemstone(product_id);
CREATE INDEX IF NOT EXISTS idx_gemstone_item_id ON gemstone(item_id) WHERE item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_gemstone_certificate_number ON gemstone(certificate_number) WHERE certificate_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_gemstone_carat ON gemstone(carat);
CREATE INDEX IF NOT EXISTS idx_gemstone_color ON gemstone(color);
CREATE INDEX IF NOT EXISTS idx_gemstone_clarity ON gemstone(clarity);
CREATE INDEX IF NOT EXISTS idx_gemstone_shape ON gemstone(shape);
CREATE INDEX IF NOT EXISTS idx_gemstone_cut_grade ON gemstone(cut_grade);
CREATE INDEX IF NOT EXISTS idx_gemstone_grading_lab ON gemstone(grading_lab);

-- ----------------------------------------------------------------------------
-- 14. material
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS material (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sku VARCHAR(100) NOT NULL,
    name VARCHAR(500) NOT NULL,
    category VARCHAR(100) NOT NULL,
    unit VARCHAR(100) NOT NULL,
    price NUMERIC(12,2) DEFAULT 0,
    cost NUMERIC(12,2) DEFAULT 0,
    weight NUMERIC(10,3) NULL,
    bead NUMERIC(10,3) NULL,
    stock_vn NUMERIC(10,2) DEFAULT 0,
    stock_us NUMERIC(10,2) DEFAULT 0,
    total_bead_vn INTEGER NULL,
    total_bead_us INTEGER NULL,
    metal VARCHAR(100) NULL,
    stone VARCHAR(100) NULL,
    size VARCHAR(100) NULL,
    collection VARCHAR(500) DEFAULT '',
    thumbnail VARCHAR(500) DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by_id BIGINT NULL,
    
    CONSTRAINT uq_material_sku UNIQUE (sku),
    CONSTRAINT chk_material_stock_vn CHECK (stock_vn >= 0),
    CONSTRAINT chk_material_stock_us CHECK (stock_us >= 0)
);

COMMENT ON TABLE material IS 'Material inventory and specifications - raw materials/components used in product manufacturing';
COMMENT ON COLUMN material.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN material.sku IS 'Material SKU';
COMMENT ON COLUMN material.name IS 'Material name';
COMMENT ON COLUMN material.category IS 'Material category';
COMMENT ON COLUMN material.stock_vn IS 'Stock quantity at VN location';
COMMENT ON COLUMN material.stock_us IS 'Stock quantity at US location';

-- Foreign Keys
ALTER TABLE material 
    ADD CONSTRAINT fk_material_updated_by_id 
    FOREIGN KEY (updated_by_id) REFERENCES sys_users(id);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_material_sku ON material(sku);
CREATE INDEX IF NOT EXISTS idx_material_category ON material(category);
CREATE INDEX IF NOT EXISTS idx_material_name ON material(name);

-- ----------------------------------------------------------------------------
-- 15. material_attribute
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS material_attribute (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(100) NOT NULL,
    value VARCHAR(300) DEFAULT ''
);

COMMENT ON TABLE material_attribute IS 'Material attribute lookup/master table - contains valid values for collection, stone, and other material attributes';
COMMENT ON COLUMN material_attribute.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN material_attribute.name IS 'Attribute name (e.g., "Collection", "Stone", "Color", "Charm")';
COMMENT ON COLUMN material_attribute.type IS 'Attribute type (e.g., "collection", "stone", "color", "charm")';
COMMENT ON COLUMN material_attribute.value IS 'Attribute value (e.g., "Spring 2024", "Diamond", "Red", "10mm")';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_material_attribute_name ON material_attribute(name);
CREATE INDEX IF NOT EXISTS idx_material_attribute_type ON material_attribute(type);
CREATE INDEX IF NOT EXISTS idx_material_attribute_type_value ON material_attribute(type, value);

-- ----------------------------------------------------------------------------
-- 16. material_product
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS material_product (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    unit VARCHAR(100) NOT NULL,
    inbound INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT chk_material_product_quantity CHECK (quantity > 0)
);

COMMENT ON TABLE material_product IS 'Junction table linking materials to products (materials used in products) - BOM tracking';
COMMENT ON COLUMN material_product.material_id IS 'Material ID';
COMMENT ON COLUMN material_product.product_id IS 'Product ID';
COMMENT ON COLUMN material_product.quantity IS 'Quantity of material used in product';
COMMENT ON COLUMN material_product.unit IS 'Unit of measurement';

-- Foreign Keys
ALTER TABLE material_product 
    ADD CONSTRAINT fk_material_product_material_id 
    FOREIGN KEY (material_id) REFERENCES material(id) ON DELETE CASCADE;
    
ALTER TABLE material_product 
    ADD CONSTRAINT fk_material_product_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_material_product_material ON material_product(material_id);
CREATE INDEX IF NOT EXISTS idx_material_product_product ON material_product(product_id);
CREATE INDEX IF NOT EXISTS idx_material_product_material_product ON material_product(material_id, product_id);

-- ----------------------------------------------------------------------------
-- 17. product_review
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_review (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    personal_key_id BIGINT NULL,
    rating INTEGER NOT NULL,
    title VARCHAR(500) DEFAULT '',
    comment TEXT DEFAULT '',
    status VARCHAR(50) DEFAULT 'pending',
    helpful_count INTEGER DEFAULT 0,
    reviewer_name VARCHAR(200) DEFAULT '',
    reviewer_email VARCHAR(300) DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_at TIMESTAMPTZ NULL,
    approved_by_id BIGINT NULL,
    
    CONSTRAINT chk_product_review_rating CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT chk_product_review_helpful_count CHECK (helpful_count >= 0),
    CONSTRAINT chk_product_review_status CHECK (status IN ('pending', 'approved', 'rejected', 'hidden'))
);

COMMENT ON TABLE product_review IS 'Product reviews and ratings - customer reviews with moderation workflow';
COMMENT ON COLUMN product_review.product_id IS 'Product ID';
COMMENT ON COLUMN product_review.personal_key_id IS 'Customer personal key (can be NULL for anonymous reviews)';
COMMENT ON COLUMN product_review.rating IS 'Rating from 1 to 5 stars';
COMMENT ON COLUMN product_review.status IS 'Review status: pending, approved, rejected, hidden';
COMMENT ON COLUMN product_review.helpful_count IS 'Number of helpful votes';
COMMENT ON COLUMN product_review.approved_by_id IS 'Staff who approved the review';

-- Foreign Keys
ALTER TABLE product_review 
    ADD CONSTRAINT fk_product_review_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
    
ALTER TABLE product_review 
    ADD CONSTRAINT fk_product_review_personal_key_id 
    FOREIGN KEY (personal_key_id) REFERENCES crm_personal_keys(id) ON DELETE SET NULL;
    
ALTER TABLE product_review 
    ADD CONSTRAINT fk_product_review_approved_by_id 
    FOREIGN KEY (approved_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_product_review_product ON product_review(product_id);
CREATE INDEX IF NOT EXISTS idx_product_review_personal_key ON product_review(personal_key_id);
CREATE INDEX IF NOT EXISTS idx_product_review_status ON product_review(status);
CREATE INDEX IF NOT EXISTS idx_product_review_rating ON product_review(rating);
CREATE INDEX IF NOT EXISTS idx_product_review_created_at ON product_review(created_at);
CREATE INDEX IF NOT EXISTS idx_product_review_product_status ON product_review(product_id, status);

-- ============================================================================
-- Triggers
-- ============================================================================

-- Auto-update updated_at timestamp (reuse function from 001_system_tenant.sql)
-- If function doesn't exist, create it
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_product_updated_at
    BEFORE UPDATE ON product
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_warehouse_updated_at
    BEFORE UPDATE ON warehouse
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_stock_updated_at
    BEFORE UPDATE ON stock
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_product_attribute_value_updated_at
    BEFORE UPDATE ON product_attribute_value
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_product_image_updated_at
    BEFORE UPDATE ON product_image
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_diamond_updated_at
    BEFORE UPDATE ON diamond
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_gemstone_updated_at
    BEFORE UPDATE ON gemstone
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_material_updated_at
    BEFORE UPDATE ON material
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_product_review_updated_at
    BEFORE UPDATE ON product_review
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Notes
-- ============================================================================

-- 1. Promotion Foreign Key
--    The product.promotion_id FK will be added after the promotion table is created
--    in migration 007_marketing_campaigns.sql. Uncomment the following after that:
--
--    ALTER TABLE product 
--        ADD CONSTRAINT fk_product_promotion_id 
--        FOREIGN KEY (promotion_id) REFERENCES promotion(id);

-- 2. Staff References
--    All staff.id references have been migrated to sys_users.id as per the
--    migration guidelines.

-- 3. Product Types
--    - standard: Regular products with predefined attributes
--    - custom: Customized products with flexible fields via product_attribute_value
--    - variant: Product variants parent (creates child variant products)
--    - set: Bundle/composite products containing multiple items
--    - jewelry: Jewelry products (uses standard attributes)
--    - diamond: Certified diamond products (has certificate in diamond table)
--    - gemstone: Gemstone products (has certificate in gemstone table)

-- 4. Stock Management
--    - Stock is managed per warehouse (one row per product per warehouse)
--    - Set products (product_type='set') stock is calculated from component items
--    - Formula: set_stock = MIN(item_stock / item_quantity_in_set) for all items

-- 5. Attribute System
--    - Product attributes normalized from direct columns to product_attribute_value
--    - Custom products can have any fields via product_attribute_value
--    - Variant products use is_variant_value=TRUE for SKU generation

