-- ============================================================================
-- Material Domain Module
-- ============================================================================
-- This migration creates tables for material management with variants and stock
-- Dependencies: sys_tenants, sys_users (001_system_tenant.sql),
--               product_attribute (005_product.sql),
--               warehouse (005_product.sql),
--               product (005_product.sql)
-- ============================================================================

-- Drop existing tables (if they exist)
DROP TABLE IF EXISTS material_history CASCADE;
DROP TABLE IF EXISTS material_stock CASCADE;
DROP TABLE IF EXISTS material_variant CASCADE;
DROP TABLE IF EXISTS material_product CASCADE;
DROP TABLE IF EXISTS material CASCADE;

-- ----------------------------------------------------------------------------
-- 1. material - Base material table (SHARED fields across all variants)
-- ----------------------------------------------------------------------------

-- Step 1: CREATE TABLE (columns and PRIMARY KEY only)
CREATE TABLE IF NOT EXISTS material (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    sku VARCHAR(100) NOT NULL,
    name VARCHAR(500) NOT NULL,
    category VARCHAR(100) NOT NULL,
    stone_attribute_id BIGINT NULL,
    charm_attribute_id BIGINT NULL,
    color_attribute_id BIGINT NULL,
    intention_attribute_id BIGINT NULL,
    element_attribute_id BIGINT NULL,
    thumbnail VARCHAR(500) DEFAULT '',
    description TEXT DEFAULT '',
    unit VARCHAR(100) DEFAULT '' NOT NULL,
    dimension VARCHAR(100) NULL,
    price NUMERIC(12,2) DEFAULT 0 NOT NULL,
    cost NUMERIC(12,2) DEFAULT 0 NOT NULL,
    weight NUMERIC(10,3) NULL,
    conversion_factor NUMERIC(10,3) NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by_id BIGINT NULL,
    updated_by_id BIGINT NULL
);

-- Step 2: CHECK constraints
ALTER TABLE material 
    ADD CONSTRAINT chk_material_price 
    CHECK (price >= 0);

ALTER TABLE material 
    ADD CONSTRAINT chk_material_cost 
    CHECK (cost >= 0);

ALTER TABLE material 
    ADD CONSTRAINT chk_material_weight 
    CHECK (weight IS NULL OR weight > 0);

ALTER TABLE material 
    ADD CONSTRAINT chk_material_conversion_factor 
    CHECK (conversion_factor IS NULL OR conversion_factor >= 0);

-- Step 3: UNIQUE constraints
ALTER TABLE material 
    ADD CONSTRAINT uq_material_tenant_sku 
    UNIQUE (tenant_id, sku);

-- Step 4: Foreign key constraints
ALTER TABLE material 
    ADD CONSTRAINT fk_material_tenant_id 
    FOREIGN KEY (tenant_id) REFERENCES sys_tenants(id) ON DELETE CASCADE;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_stone_attribute_id 
    FOREIGN KEY (stone_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_charm_attribute_id 
    FOREIGN KEY (charm_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_color_attribute_id 
    FOREIGN KEY (color_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_intention_attribute_id 
    FOREIGN KEY (intention_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_element_attribute_id 
    FOREIGN KEY (element_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_created_by_id 
    FOREIGN KEY (created_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;
    
ALTER TABLE material 
    ADD CONSTRAINT fk_material_updated_by_id 
    FOREIGN KEY (updated_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Step 5: Comments
-- (none)

-- Step 6: Indexes
CREATE INDEX IF NOT EXISTS idx_material_tenant_id ON material(tenant_id);
CREATE INDEX IF NOT EXISTS idx_material_sku ON material(sku);
CREATE INDEX IF NOT EXISTS idx_material_category ON material(category);
CREATE INDEX IF NOT EXISTS idx_material_name ON material(name);
CREATE INDEX IF NOT EXISTS idx_material_stone ON material(stone_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_charm ON material(charm_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_color ON material(color_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_intention ON material(intention_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_element ON material(element_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_is_active ON material(is_active);
CREATE INDEX IF NOT EXISTS idx_material_unit ON material(unit);
CREATE INDEX IF NOT EXISTS idx_material_price ON material(price);

-- Step 7: Triggers
-- (see Triggers section at end of file)

-- ----------------------------------------------------------------------------
-- 2. material_variant - Material variants (UNIQUE fields per variant)
-- ----------------------------------------------------------------------------

-- Step 1: CREATE TABLE (columns and PRIMARY KEY only)
CREATE TABLE IF NOT EXISTS material_variant (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material_id BIGINT NOT NULL,
    sku VARCHAR(100) NOT NULL,
    name VARCHAR(500) NOT NULL,
    size_attribute_id BIGINT NULL,
    metal_attribute_id BIGINT NULL,
    unit VARCHAR(100) NOT NULL,
    dimension VARCHAR(100) NULL,
    price NUMERIC(12,2) NOT NULL DEFAULT 0,
    cost NUMERIC(12,2) NOT NULL DEFAULT 0,
    weight NUMERIC(10,3) NULL,
    conversion_factor NUMERIC(10,3) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by_id BIGINT NULL,
    updated_by_id BIGINT NULL
);

-- Step 2: CHECK constraints
ALTER TABLE material_variant 
    ADD CONSTRAINT chk_material_variant_price 
    CHECK (price >= 0);

ALTER TABLE material_variant 
    ADD CONSTRAINT chk_material_variant_cost 
    CHECK (cost >= 0);

ALTER TABLE material_variant 
    ADD CONSTRAINT chk_material_variant_weight 
    CHECK (weight IS NULL OR weight > 0);

-- Step 3: UNIQUE constraints
ALTER TABLE material_variant 
    ADD CONSTRAINT uq_material_variant_sku 
    UNIQUE (sku);

-- Step 4: Foreign key constraints
ALTER TABLE material_variant 
    ADD CONSTRAINT fk_material_variant_material_id 
    FOREIGN KEY (material_id) REFERENCES material(id) ON DELETE CASCADE;
    
ALTER TABLE material_variant 
    ADD CONSTRAINT fk_material_variant_size_attribute_id 
    FOREIGN KEY (size_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material_variant 
    ADD CONSTRAINT fk_material_variant_metal_attribute_id 
    FOREIGN KEY (metal_attribute_id) REFERENCES product_attribute(id) ON DELETE SET NULL;
    
ALTER TABLE material_variant 
    ADD CONSTRAINT fk_material_variant_created_by_id 
    FOREIGN KEY (created_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;
    
ALTER TABLE material_variant 
    ADD CONSTRAINT fk_material_variant_updated_by_id 
    FOREIGN KEY (updated_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Step 5: Comments
-- (none)

-- Step 6: Indexes
CREATE INDEX IF NOT EXISTS idx_material_variant_material_id ON material_variant(material_id);
CREATE INDEX IF NOT EXISTS idx_material_variant_sku ON material_variant(sku);
CREATE INDEX IF NOT EXISTS idx_material_variant_size ON material_variant(size_attribute_id);
CREATE INDEX IF NOT EXISTS idx_material_variant_metal ON material_variant(metal_attribute_id);

-- Step 7: Triggers
-- (see Triggers section at end of file)

-- Add conversion_factor to material_variant (if table already exists)
ALTER TABLE material_variant 
    ADD COLUMN IF NOT EXISTS conversion_factor NUMERIC(10,3) NULL;

ALTER TABLE material_variant 
    ADD CONSTRAINT chk_material_variant_conversion_factor 
    CHECK (conversion_factor IS NULL OR conversion_factor >= 0);

-- ----------------------------------------------------------------------------
-- 3. material_stock - Stock by warehouse/location (UNIQUE per variant)
-- ----------------------------------------------------------------------------

-- Remove conversion_factor from material_stock (if table already exists)
ALTER TABLE material_stock 
    DROP COLUMN IF EXISTS conversion_factor;

-- Add total_converted_quantity to material_stock (if table already exists)
ALTER TABLE material_stock 
    ADD COLUMN IF NOT EXISTS total_converted_quantity NUMERIC(10,2) DEFAULT 0;

-- Step 1: CREATE TABLE (columns and PRIMARY KEY only)
CREATE TABLE IF NOT EXISTS material_stock (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material_id BIGINT NULL,
    material_variant_id BIGINT NULL,
    warehouse_id BIGINT NOT NULL,
    quantity NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_converted_quantity NUMERIC(10,2) NOT NULL DEFAULT 0,
    inbound NUMERIC(10,2) NOT NULL DEFAULT 0,
    outbound NUMERIC(10,2) NOT NULL DEFAULT 0,
    last_counted_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by_id BIGINT NULL
);

-- Step 2: CHECK constraints
ALTER TABLE material_stock 
    ADD CONSTRAINT chk_material_stock_quantity 
    CHECK (quantity >= 0);

ALTER TABLE material_stock 
    ADD CONSTRAINT chk_material_stock_total_converted_quantity 
    CHECK (total_converted_quantity >= 0);

ALTER TABLE material_stock 
    ADD CONSTRAINT chk_material_stock_inbound 
    CHECK (inbound >= 0);

ALTER TABLE material_stock 
    ADD CONSTRAINT chk_material_stock_outbound 
    CHECK (outbound >= 0);

ALTER TABLE material_stock 
    ADD CONSTRAINT chk_material_stock_material_or_variant 
    CHECK (
        (material_id IS NOT NULL AND material_variant_id IS NULL) OR 
        (material_id IS NULL AND material_variant_id IS NOT NULL)
    );

-- Step 3: UNIQUE constraints
ALTER TABLE material_stock 
    ADD CONSTRAINT uq_material_stock_material_warehouse 
    UNIQUE (material_id, warehouse_id);

ALTER TABLE material_stock 
    ADD CONSTRAINT uq_material_stock_variant_warehouse 
    UNIQUE (material_variant_id, warehouse_id);

-- Step 4: Foreign key constraints
ALTER TABLE material_stock 
    ADD CONSTRAINT fk_material_stock_material_id 
    FOREIGN KEY (material_id) REFERENCES material(id) ON DELETE CASCADE;
    
ALTER TABLE material_stock 
    ADD CONSTRAINT fk_material_stock_material_variant_id 
    FOREIGN KEY (material_variant_id) REFERENCES material_variant(id) ON DELETE CASCADE;
    
ALTER TABLE material_stock 
    ADD CONSTRAINT fk_material_stock_warehouse_id 
    FOREIGN KEY (warehouse_id) REFERENCES warehouse(id) ON DELETE CASCADE;
    
ALTER TABLE material_stock 
    ADD CONSTRAINT fk_material_stock_updated_by_id 
    FOREIGN KEY (updated_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Step 5: Comments
-- (none)

-- Step 6: Indexes
CREATE INDEX IF NOT EXISTS idx_material_stock_material_id ON material_stock(material_id);
CREATE INDEX IF NOT EXISTS idx_material_stock_material_variant_id ON material_stock(material_variant_id);
CREATE INDEX IF NOT EXISTS idx_material_stock_warehouse_id ON material_stock(warehouse_id);

-- Step 7: Triggers
-- (see Triggers section at end of file)

-- ----------------------------------------------------------------------------
-- 4. material_history - Audit trail for material changes
-- ----------------------------------------------------------------------------

-- Step 1: CREATE TABLE (columns and PRIMARY KEY only)
CREATE TABLE IF NOT EXISTS material_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material_id BIGINT NULL,
    material_variant_id BIGINT NULL,
    material_stock_id BIGINT NULL,
    action_type VARCHAR(50) NOT NULL,
    field_name VARCHAR(100) NULL,
    old_value TEXT NULL,
    new_value TEXT NULL,
    quantity_change NUMERIC(10,2) NULL,
    reference_type VARCHAR(50) NULL,
    reference_id BIGINT NULL,
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by_id BIGINT NULL
);

-- Step 2: CHECK constraints
ALTER TABLE material_history 
    ADD CONSTRAINT chk_material_history_action_type 
    CHECK (
        action_type IN ('create', 'update', 'delete', 'stock_in', 'stock_out', 'stock_adjust', 'reserve', 'unreserve', 'transfer')
    );

ALTER TABLE material_history 
    ADD CONSTRAINT chk_material_history_reference_type 
    CHECK (
        reference_type IS NULL OR reference_type IN ('order', 'production', 'purchase', 'adjustment', 'transfer', 'product')
    );

-- Step 3: UNIQUE constraints
-- (none)

-- Step 4: Foreign key constraints
ALTER TABLE material_history 
    ADD CONSTRAINT fk_material_history_material_id 
    FOREIGN KEY (material_id) REFERENCES material(id) ON DELETE SET NULL;
    
ALTER TABLE material_history 
    ADD CONSTRAINT fk_material_history_material_variant_id 
    FOREIGN KEY (material_variant_id) REFERENCES material_variant(id) ON DELETE SET NULL;
    
ALTER TABLE material_history 
    ADD CONSTRAINT fk_material_history_material_stock_id 
    FOREIGN KEY (material_stock_id) REFERENCES material_stock(id) ON DELETE SET NULL;
    
ALTER TABLE material_history 
    ADD CONSTRAINT fk_material_history_created_by_id 
    FOREIGN KEY (created_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Step 5: Comments
-- (none)

-- Step 6: Indexes
CREATE INDEX IF NOT EXISTS idx_material_history_material_id ON material_history(material_id);
CREATE INDEX IF NOT EXISTS idx_material_history_material_variant_id ON material_history(material_variant_id);
CREATE INDEX IF NOT EXISTS idx_material_history_material_stock_id ON material_history(material_stock_id);
CREATE INDEX IF NOT EXISTS idx_material_history_action_type ON material_history(action_type);
CREATE INDEX IF NOT EXISTS idx_material_history_created_at ON material_history(created_at);
CREATE INDEX IF NOT EXISTS idx_material_history_reference ON material_history(reference_type, reference_id) WHERE reference_type IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_material_history_created_by_id ON material_history(created_by_id);

-- Step 7: Triggers
-- (see Triggers section at end of file)

-- ----------------------------------------------------------------------------
-- 5. material_product - BOM tracking (materials/variants used in products)
-- ----------------------------------------------------------------------------

-- Step 1: CREATE TABLE (columns and PRIMARY KEY only)
CREATE TABLE IF NOT EXISTS material_product (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    material_variant_id BIGINT NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    unit VARCHAR(100) NOT NULL,
    is_inbound BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Step 2: CHECK constraints
ALTER TABLE material_product 
    ADD CONSTRAINT chk_material_product_quantity 
    CHECK (quantity > 0);

ALTER TABLE material_product 
    ADD CONSTRAINT chk_material_product_variant_belongs_to_material 
    CHECK (
        EXISTS (
            SELECT 1 FROM material_variant mv 
            WHERE mv.id = material_variant_id 
            AND mv.material_id = material_product.material_id
        )
    );

-- Step 3: UNIQUE constraints
-- (none - allow multiple entries for same product+variant if needed)

-- Step 4: Foreign key constraints
ALTER TABLE material_product 
    ADD CONSTRAINT fk_material_product_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
    
ALTER TABLE material_product 
    ADD CONSTRAINT fk_material_product_material_id 
    FOREIGN KEY (material_id) REFERENCES material(id) ON DELETE CASCADE;
    
ALTER TABLE material_product 
    ADD CONSTRAINT fk_material_product_material_variant_id 
    FOREIGN KEY (material_variant_id) REFERENCES material_variant(id) ON DELETE CASCADE;

-- Step 5: Comments
-- (none)

-- Step 6: Indexes
CREATE INDEX IF NOT EXISTS idx_material_product_product_id ON material_product(product_id);
CREATE INDEX IF NOT EXISTS idx_material_product_material_id ON material_product(material_id);
CREATE INDEX IF NOT EXISTS idx_material_product_material_variant_id ON material_product(material_variant_id);
CREATE INDEX IF NOT EXISTS idx_material_product_product_material ON material_product(product_id, material_id);
CREATE INDEX IF NOT EXISTS idx_material_product_product_variant ON material_product(product_id, material_variant_id);

-- Step 7: Triggers
-- (see Triggers section at end of file)

-- ============================================================================
-- Triggers
-- ============================================================================

-- Auto-update updated_at timestamp (reuse function from 001_system_tenant.sql)
-- If function doesn't exist, create it
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_material_updated_at
    BEFORE UPDATE ON material
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_material_variant_updated_at
    BEFORE UPDATE ON material_variant
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_material_stock_updated_at
    BEFORE UPDATE ON material_stock
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_material_product_updated_at
    BEFORE UPDATE ON material_product
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Notes
-- ============================================================================

-- 1. Material Structure
--    - material: Base material with SHARED attributes (stone, charm, color, intention, element)
--    - material_variant: Variants with UNIQUE attributes (size, metal, unit, dimension, price, cost, weight, conversion_factor)
--    - material_stock: Stock managed per variant+warehouse
--    - material_product: BOM linking products to material variants (uses both material_id and material_variant_id)

-- 2. Stock Management
--    - Stock is managed at variant level (material_stock.material_variant_id)
--    - total_converted_quantity: Calculate in application/query as quantity * material_variant.conversion_factor
--    - Supports both base materials and variants (via CHECK constraint)

-- 3. Product Material Relationship
--    - material_product uses material_id to get SHARED attributes
--    - material_product uses material_variant_id for stock management and UNIQUE attributes
--    - CHECK constraint ensures variant belongs to the specified material

-- 4. Attribute References
--    - Shared attributes (stone, charm, color, intention, element) reference product_attribute
--    - Unique attributes (size, metal) also reference product_attribute
--    - This ensures data consistency across the system

-- 5. Unit and Conversion Factor Management
--    - unit and conversion_factor are stored in material_variant (not in material_stock) to avoid data duplication
--    - Stock manages quantities (quantity, inbound, outbound) and total_converted_quantity
--    - total_converted_quantity: Calculate in application/query as quantity * material_variant.conversion_factor

-- ============================================================================
-- Migration: Add unit, price, cost, weight to material table (if table already exists)
-- ============================================================================
-- Run these ALTER TABLE statements if material table was created before these fields were added

-- Add unit column
ALTER TABLE material 
    ADD COLUMN IF NOT EXISTS unit VARCHAR(100) DEFAULT '' NOT NULL;

-- Add price column
ALTER TABLE material 
    ADD COLUMN IF NOT EXISTS price NUMERIC(12,2) DEFAULT 0 NOT NULL;

-- Add cost column
ALTER TABLE material 
    ADD COLUMN IF NOT EXISTS cost NUMERIC(12,2) DEFAULT 0 NOT NULL;

-- Add dimension column
ALTER TABLE material 
    ADD COLUMN IF NOT EXISTS dimension VARCHAR(100) NULL;

-- Add weight column
ALTER TABLE material 
    ADD COLUMN IF NOT EXISTS weight NUMERIC(10,3) NULL;

-- Add conversion_factor column
ALTER TABLE material 
    ADD COLUMN IF NOT EXISTS conversion_factor NUMERIC(10,3) NULL;

-- Add CHECK constraints (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'chk_material_price'
    ) THEN
        ALTER TABLE material 
            ADD CONSTRAINT chk_material_price 
            CHECK (price >= 0);
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'chk_material_cost'
    ) THEN
        ALTER TABLE material 
            ADD CONSTRAINT chk_material_cost 
            CHECK (cost >= 0);
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'chk_material_weight'
    ) THEN
        ALTER TABLE material 
            ADD CONSTRAINT chk_material_weight 
            CHECK (weight IS NULL OR weight > 0);
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'chk_material_conversion_factor'
    ) THEN
        ALTER TABLE material 
            ADD CONSTRAINT chk_material_conversion_factor 
            CHECK (conversion_factor IS NULL OR conversion_factor >= 0);
    END IF;
END $$;

-- Add indexes (if not exists)
CREATE INDEX IF NOT EXISTS idx_material_unit ON material(unit);
CREATE INDEX IF NOT EXISTS idx_material_price ON material(price);

