-- ============================================================================
-- Inventory Audit & History Module
-- ============================================================================
-- This migration creates tables for inventory audit cycles and stock discrepancy tracking
-- Dependencies: sys_tenants, sys_users (001_system_tenant.sql),
--               product, stock, warehouse (005_product.sql)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. inventory_history
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    audit_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    cycle_number INTEGER DEFAULT 1,
    status VARCHAR(50) DEFAULT 'pending',
    product_sku VARCHAR(100) NOT NULL,
    product_name VARCHAR(500) NOT NULL,
    recorded_quantity INTEGER NOT NULL DEFAULT 0,
    actual_quantity INTEGER NOT NULL DEFAULT 0,
    quantity_discrepancy INTEGER NOT NULL DEFAULT 0,
    details TEXT NULL,
    warehouse_id BIGINT NOT NULL,
    audited_by_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    CONSTRAINT chk_inventory_history_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled'))
);

COMMENT ON TABLE inventory_history IS 'Inventory audit history and stock discrepancy tracking';
COMMENT ON COLUMN inventory_history.id IS 'Auto-incrementing primary key';
COMMENT ON COLUMN inventory_history.product_id IS 'Product ID (FK to product table)';
COMMENT ON COLUMN inventory_history.stock_id IS 'Stock ID (FK to stock table)';
COMMENT ON COLUMN inventory_history.audit_date IS 'Date/time of audit';
COMMENT ON COLUMN inventory_history.cycle_number IS 'Audit cycle/round number';
COMMENT ON COLUMN inventory_history.status IS 'Audit status: pending, in_progress, completed, cancelled';
COMMENT ON COLUMN inventory_history.product_sku IS 'Product SKU (denormalized for historical accuracy)';
COMMENT ON COLUMN inventory_history.product_name IS 'Product name (denormalized for historical accuracy)';
COMMENT ON COLUMN inventory_history.recorded_quantity IS 'Quantity recorded in system before audit (from stock.qty)';
COMMENT ON COLUMN inventory_history.actual_quantity IS 'Actual quantity counted during audit';
COMMENT ON COLUMN inventory_history.quantity_discrepancy IS 'Calculated: actual_quantity - recorded_quantity';
COMMENT ON COLUMN inventory_history.details IS 'Audit notes and details';
COMMENT ON COLUMN inventory_history.warehouse_id IS 'Warehouse ID (FK)';
COMMENT ON COLUMN inventory_history.audited_by_id IS 'Staff who performed the audit';

-- Foreign Keys
ALTER TABLE inventory_history 
    ADD CONSTRAINT fk_inventory_history_product_id 
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;
    
ALTER TABLE inventory_history 
    ADD CONSTRAINT fk_inventory_history_stock_id 
    FOREIGN KEY (stock_id) REFERENCES stock(id) ON DELETE CASCADE;
    
ALTER TABLE inventory_history 
    ADD CONSTRAINT fk_inventory_history_warehouse_id 
    FOREIGN KEY (warehouse_id) REFERENCES warehouse(id) ON DELETE CASCADE;
    
ALTER TABLE inventory_history 
    ADD CONSTRAINT fk_inventory_history_audited_by_id 
    FOREIGN KEY (audited_by_id) REFERENCES sys_users(id) ON DELETE SET NULL;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_inventory_history_product ON inventory_history(product_id);
CREATE INDEX IF NOT EXISTS idx_inventory_history_stock ON inventory_history(stock_id);
CREATE INDEX IF NOT EXISTS idx_inventory_history_product_sku ON inventory_history(product_sku);
CREATE INDEX IF NOT EXISTS idx_inventory_history_warehouse ON inventory_history(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_inventory_history_audit_date ON inventory_history(audit_date);
CREATE INDEX IF NOT EXISTS idx_inventory_history_status ON inventory_history(status);
CREATE INDEX IF NOT EXISTS idx_inventory_history_cycle_number ON inventory_history(cycle_number);
CREATE INDEX IF NOT EXISTS idx_inventory_history_audited_by ON inventory_history(audited_by_id);
CREATE INDEX IF NOT EXISTS idx_inventory_history_product_warehouse ON inventory_history(product_id, warehouse_id);

-- ============================================================================
-- Triggers
-- ============================================================================

-- Auto-update updated_at timestamp (reuse function from 001_system_tenant.sql)
-- If function doesn't exist, create it
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_inventory_history_updated_at
    BEFORE UPDATE ON inventory_history
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Notes
-- ============================================================================

-- Inventory Audit System
--    - Tracks inventory audit cycles and stock discrepancies
--    - Audit Workflow: pending → in_progress → completed/cancelled
--    - Discrepancy Calculation: quantity_discrepancy = actual_quantity - recorded_quantity
--      - Positive: More items found than recorded (overage)
--      - Negative: Fewer items found than recorded (shortage)
--      - Zero: Count matches system records
--    - Historical Data: product_sku and product_name are denormalized to preserve
--      historical accuracy even if product/stock records are updated or deleted
--    - Data Source: recorded_quantity should be populated from stock.qty where
--      stock.product_sku matches and stock.warehouse_id matches the audit warehouse
--    - Multiple Audit Cycles: Same product, same warehouse, different cycles
--      allow tracking of inventory accuracy over time
--    - Warehouse Relationship: Links to warehouse table for proper referential integrity
--    - Product & Stock Links: 
--      - product_id links directly to product.id for product information
--      - stock_id links directly to stock.id for stock information
--      - warehouse_id links directly to warehouse.id for warehouse information
--      - recorded_quantity should be populated from stock.qty where stock.product_sku 
--        matches and stock.warehouse_id matches the audit warehouse

-- Example Usage:
--    Get all discrepancies for a product (with product and stock info):
--    SELECT ih.*, p.name as current_product_name, p.sku as current_product_sku,
--           s.qty, w.code as warehouse_code, w.name as warehouse_name, s.outbound, s.inbound
--    FROM inventory_history ih
--    JOIN product p ON ih.product_id = p.id
--    JOIN stock s ON ih.stock_id = s.id
--    JOIN warehouse w ON ih.warehouse_id = w.id
--    WHERE ih.product_id = 123 
--      AND ih.status = 'completed'
--    ORDER BY ih.audit_date DESC;

--    Find products with recurring discrepancies:
--    SELECT ih.product_id, ih.product_sku, ih.product_name, w.code as warehouse_code, 
--           COUNT(*) as audit_count,
--           AVG(ih.quantity_discrepancy) as avg_discrepancy
--    FROM inventory_history ih
--    JOIN warehouse w ON ih.warehouse_id = w.id
--    WHERE ih.status = 'completed'
--    GROUP BY ih.product_id, ih.product_sku, ih.product_name, w.code
--    HAVING COUNT(*) > 1 AND AVG(ABS(ih.quantity_discrepancy)) > 5
--    ORDER BY avg_discrepancy DESC;

--    Get latest audit for each product-warehouse:
--    SELECT DISTINCT ON (ih.product_id, ih.warehouse_id) 
--           ih.*, p.name as current_product_name, s.qty, w.code as warehouse_code, w.name as warehouse_name
--    FROM inventory_history ih
--    JOIN product p ON ih.product_id = p.id
--    JOIN stock s ON ih.stock_id = s.id AND s.warehouse_id = ih.warehouse_id
--    JOIN warehouse w ON ih.warehouse_id = w.id
--    WHERE ih.status = 'completed'
--    ORDER BY ih.product_id, ih.warehouse_id, ih.audit_date DESC;

