import type { AIFlow, ExternalTool } from "../types";

export const aiFlows: AIFlow[] = [
  // Layer 1: Fully Automated
  {
    id: "1",
    name: "Auto Campaign Performance Monitor",
    description: "Continuously tracks campaign metrics and auto-adjusts budgets",
    status: "active",
    layer: 1,
    category: "Analytics",
    metrics: {
      tasksProcessed: 3421,
      successRate: 97,
      avgTime: "Real-time",
      quality: 98,
      efficiency: 95,
    },
    lastRun: "Running",
    createdDate: "Sep 1, 2025",
  },
  {
    id: "2",
    name: "Social Media Auto-Scheduler",
    description: "Automatically posts content at optimal times across all platforms",
    status: "active",
    layer: 1,
    category: "Distribution",
    metrics: {
      tasksProcessed: 1847,
      successRate: 98,
      avgTime: "Real-time",
      quality: 96,
      efficiency: 92,
    },
    lastRun: "Running",
    createdDate: "Sep 15, 2025",
  },
  {
    id: "3",
    name: "Sentiment Analysis Engine",
    description: "Real-time monitoring of customer feedback and sentiment trends",
    status: "active",
    layer: 1,
    category: "Customer Insights",
    metrics: {
      tasksProcessed: 5892,
      successRate: 95,
      avgTime: "Real-time",
      quality: 94,
      efficiency: 97,
    },
    lastRun: "Running",
    createdDate: "Aug 20, 2025",
  },
  {
    id: "4",
    name: "Email Engagement Optimizer",
    description: "Automatically optimizes send times and content for each recipient",
    status: "paused",
    layer: 1,
    category: "Email Marketing",
    metrics: {
      tasksProcessed: 892,
      successRate: 89,
      avgTime: "Real-time",
      quality: 91,
      efficiency: 88,
    },
    lastRun: "2 hours ago",
    createdDate: "Aug 10, 2025",
  },

  // Layer 2: Human-Triggered
  {
    id: "5",
    name: "Content Generator",
    description: "Click to generate campaign content for ads, emails, and social posts",
    status: "active",
    layer: 2,
    category: "Content Creation",
    metrics: {
      tasksProcessed: 234,
      successRate: 94,
      avgTime: "2.3 min",
      quality: 87,
      efficiency: 85,
    },
    lastRun: "5 min ago",
    createdDate: "Oct 1, 2025",
  },
  {
    id: "6",
    name: "Influencer Match Finder",
    description: "Search and score potential brand partners on demand",
    status: "active",
    layer: 2,
    category: "Partnerships",
    metrics: {
      tasksProcessed: 127,
      successRate: 91,
      avgTime: "4.1 min",
      quality: 89,
      efficiency: 78,
    },
    lastRun: "18 min ago",
    createdDate: "Sep 25, 2025",
  },
  {
    id: "7",
    name: "A/B Test Generator",
    description: "Create multiple creative variants for testing with one click",
    status: "active",
    layer: 2,
    category: "Testing",
    metrics: {
      tasksProcessed: 89,
      successRate: 96,
      avgTime: "1.8 min",
      quality: 93,
      efficiency: 82,
    },
    lastRun: "1 hour ago",
    createdDate: "Sep 20, 2025",
  },
  {
    id: "8",
    name: "Audience Segment Builder",
    description: "Trigger AI to analyze and create customer segments",
    status: "requested",
    layer: 2,
    category: "Segmentation",
    metrics: {
      tasksProcessed: 0,
      successRate: 0,
      avgTime: "N/A",
      quality: 0,
      efficiency: 0,
    },
    createdDate: "Oct 18, 2025",
  },

  // Layer 3: Interactive Conversational
  {
    id: "9",
    name: "Marketing Strategy Co-Pilot",
    description: "Chat to create, refine, and adjust marketing plans collaboratively",
    status: "active",
    layer: 3,
    category: "Strategy",
    metrics: {
      tasksProcessed: 45,
      successRate: 93,
      avgTime: "15-30 min",
      quality: 92,
      efficiency: 65,
    },
    lastRun: "2 hours ago",
    createdDate: "Oct 5, 2025",
  },
  {
    id: "10",
    name: "Campaign Brief Assistant",
    description: "Interactive conversation to develop detailed campaign briefs",
    status: "active",
    layer: 3,
    category: "Planning",
    metrics: {
      tasksProcessed: 67,
      successRate: 91,
      avgTime: "20-40 min",
      quality: 90,
      efficiency: 60,
    },
    lastRun: "4 hours ago",
    createdDate: "Sep 28, 2025",
  },
  {
    id: "11",
    name: "Creative Direction Advisor",
    description: "Back-and-forth dialogue for creative concept development",
    status: "active",
    layer: 3,
    category: "Creative",
    metrics: {
      tasksProcessed: 34,
      successRate: 89,
      avgTime: "25-45 min",
      quality: 88,
      efficiency: 55,
    },
    lastRun: "Yesterday",
    createdDate: "Sep 18, 2025",
  },
  {
    id: "12",
    name: "Budget Planner Assistant",
    description: "Conversational AI to build and optimize marketing budgets",
    status: "requested",
    layer: 3,
    category: "Budgeting",
    metrics: {
      tasksProcessed: 0,
      successRate: 0,
      avgTime: "N/A",
      quality: 0,
      efficiency: 0,
    },
    createdDate: "Oct 19, 2025",
  },
];

export const externalTools: ExternalTool[] = [
  {
    id: "ext-1",
    name: "Google Studio",
    description: "Design and manage creative assets for Google Ads campaigns",
    category: "Creative Design",
    url: "https://studio.google.com",
    icon: "🎨",
    status: "connected",
  },
  {
    id: "ext-2",
    name: "ChatGPT",
    description: "AI conversational assistant for content ideation and copywriting",
    category: "AI Assistant",
    url: "https://chat.openai.com",
    icon: "💬",
    status: "connected",
  },
  {
    id: "ext-3",
    name: "Cursor",
    description: "AI-powered code editor for marketing automation development",
    category: "Development",
    url: "https://cursor.sh",
    icon: "⌨️",
    status: "available",
  },
  {
    id: "ext-4",
    name: "Codex",
    description: "Advanced AI coding assistant for custom integrations",
    category: "Development",
    url: "#",
    icon: "🔧",
    status: "available",
  },
  {
    id: "ext-5",
    name: "Sora",
    description: "AI video generation tool for marketing video content",
    category: "Video Creation",
    url: "https://openai.com/sora",
    icon: "🎬",
    status: "connected",
  },
  {
    id: "ext-6",
    name: "Midjourney",
    description: "AI image generation for marketing visuals and campaigns",
    category: "Image Generation",
    url: "https://midjourney.com",
    icon: "🖼️",
    status: "available",
  },
];
