export interface Attribute {
  id: string;
  name: string;
  type: "single" | "multiple" | "text";
  values: string[];
  applyTo: string[];
  required: boolean;
  visibleOnStore: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export const mockAttributes: Attribute[] = [
  {
    id: "attr-001",
    name: "Size",
    type: "single",
    values: ["XS", "S", "M", "L", "XL", "Adjustable"],
    applyTo: ["Bracelet", "Ring", "Necklace"],
    required: true,
    visibleOnStore: true,
    sortOrder: 1,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2025-10-20T14:30:00Z",
  },
  {
    id: "attr-002",
    name: "Metal Type",
    type: "single",
    values: ["18K Gold", "14K Gold", "Rose Gold", "Sterling Silver 925", "Stainless Steel", "Platinum"],
    applyTo: ["Bracelet", "Ring", "Necklace", "Earrings", "Pendant"],
    required: true,
    visibleOnStore: true,
    sortOrder: 2,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2025-10-22T09:15:00Z",
  },
  {
    id: "attr-003",
    name: "Stone Type",
    type: "single",
    values: [
      "Citrine",
      "Rose Quartz",
      "Amethyst",
      "Black Obsidian",
      "Moonstone",
      "Labradorite",
      "Black Tourmaline",
      "Clear Quartz",
      "Tiger's Eye",
      "Turquoise",
      "Pearl",
      "Diamond"
    ],
    applyTo: ["Bracelet", "Ring", "Necklace", "Earrings", "Pendant"],
    required: false,
    visibleOnStore: true,
    sortOrder: 3,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2025-10-28T11:00:00Z",
  },
  {
    id: "attr-004",
    name: "Bead Size",
    type: "single",
    values: ["4mm", "6mm", "8mm", "10mm", "12mm"],
    applyTo: ["Bracelet"],
    required: false,
    visibleOnStore: true,
    sortOrder: 4,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2025-10-15T16:20:00Z",
  },
  {
    id: "attr-005",
    name: "Chain Length",
    type: "single",
    values: ["14 inches", "16 inches", "18 inches", "20 inches", "22 inches", "24 inches"],
    applyTo: ["Necklace"],
    required: true,
    visibleOnStore: true,
    sortOrder: 5,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2025-10-18T13:45:00Z",
  },
  {
    id: "attr-006",
    name: "Ring Size",
    type: "single",
    values: ["4", "5", "6", "7", "8", "9", "10", "11", "12"],
    applyTo: ["Ring"],
    required: true,
    visibleOnStore: true,
    sortOrder: 6,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2025-10-20T10:00:00Z",
  },
  {
    id: "attr-007",
    name: "Color",
    type: "single",
    values: ["Gold", "Silver", "Rose Gold", "Black", "White", "Multi-Color"],
    applyTo: ["Bracelet", "Ring", "Necklace", "Earrings", "Pendant"],
    required: false,
    visibleOnStore: true,
    sortOrder: 7,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2025-10-25T14:00:00Z",
  },
  {
    id: "attr-008",
    name: "Intention",
    type: "single",
    values: [
      "Love",
      "Prosperity",
      "Protection",
      "Healing",
      "Harmony",
      "Peace",
      "Abundance",
      "Courage",
      "Wisdom",
      "Clarity"
    ],
    applyTo: ["Bracelet", "Ring", "Necklace", "Earrings", "Pendant"],
    required: false,
    visibleOnStore: true,
    sortOrder: 8,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2025-10-28T09:30:00Z",
  },
  {
    id: "attr-009",
    name: "Charm Type",
    type: "multiple",
    values: [
      "Lotus",
      "Moon",
      "Star",
      "Heart",
      "Evil Eye",
      "Hamsa",
      "Om",
      "Tree of Life",
      "Infinity",
      "Angel Wings"
    ],
    applyTo: ["Bracelet", "Necklace", "Pendant"],
    required: false,
    visibleOnStore: true,
    sortOrder: 9,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2025-10-27T15:20:00Z",
  },
  {
    id: "attr-010",
    name: "Gender",
    type: "single",
    values: ["Male", "Female", "Unisex"],
    applyTo: ["Bracelet", "Ring", "Necklace", "Earrings", "Pendant"],
    required: false,
    visibleOnStore: true,
    sortOrder: 10,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2025-10-20T11:00:00Z",
  },
  {
    id: "attr-011",
    name: "Engraving Text",
    type: "text",
    values: [],
    applyTo: ["Bracelet", "Ring", "Necklace", "Pendant"],
    required: false,
    visibleOnStore: true,
    sortOrder: 11,
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2025-10-15T10:00:00Z",
  },
  {
    id: "attr-012",
    name: "Element",
    type: "single",
    values: ["Fire", "Earth", "Water", "Air", "Ether"],
    applyTo: ["Bracelet", "Ring", "Necklace", "Pendant"],
    required: false,
    visibleOnStore: true,
    sortOrder: 12,
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2025-10-22T14:15:00Z",
  },
];
