export interface Gemstone {
  id: string;
  sku: string;
  name: string;
  stoneType: "precious" | "semi-precious";
  variety: string;
  color: string;
  origin: string;
  shape: string;
  cut: string;
  carat: number;
  dimensions: string;
  clarity: string;
  treatment: "None" | "Heated" | "Oiled" | "Irradiated" | "Dyed" | "Enhanced";
  certification?: string;
  certificateNumber?: string;
  hardness: string;
  quantityInStock: number;
  location: "VN" | "US";
  unitCost: number;
  retailPrice: number;
  vendor: string;
  status: "available" | "reserved" | "sold";
  lastUpdate: string;
  imageUrl?: string;
  healingProperties?: string;
  notes?: string;
}

export const mockGemstones: Gemstone[] = [
  {
    id: "gem-001",
    sku: "GEM-CIT-8MM-RND",
    name: "Natural Citrine",
    stoneType: "semi-precious",
    variety: "Citrine Quartz",
    color: "Golden Yellow",
    origin: "Brazil",
    shape: "Round",
    cut: "Cabochon",
    carat: 2.5,
    dimensions: "8mm diameter",
    clarity: "Translucent",
    treatment: "Heated",
    hardness: "7 Mohs",
    quantityInStock: 245,
    location: "VN",
    unitCost: 3.50,
    retailPrice: 8.50,
    vendor: "Golden Gems Supply",
    status: "available",
    lastUpdate: "2025-10-28T09:00:00Z",
    imageUrl: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400",
    healingProperties: "Prosperity, abundance, manifestation, joy, confidence",
    notes: "Popular for prosperity bracelets",
  },
  {
    id: "gem-002",
    sku: "GEM-RQ-10MM-HRT",
    name: "Rose Quartz Heart",
    stoneType: "semi-precious",
    variety: "Rose Quartz",
    color: "Soft Pink",
    origin: "Madagascar",
    shape: "Heart",
    cut: "Smooth Polish",
    carat: 8.0,
    dimensions: "10 x 10 x 5mm",
    clarity: "Translucent",
    treatment: "None",
    hardness: "7 Mohs",
    quantityInStock: 180,
    location: "VN",
    unitCost: 4.20,
    retailPrice: 12.50,
    vendor: "Golden Gems Supply",
    status: "available",
    lastUpdate: "2025-10-27T14:30:00Z",
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400",
    healingProperties: "Love, compassion, emotional healing, self-love, relationships",
    notes: "Best seller for Valentine's collection",
  },
  {
    id: "gem-003",
    sku: "GEM-AME-6MM-RND",
    name: "Amethyst Round",
    stoneType: "semi-precious",
    variety: "Amethyst Quartz",
    color: "Deep Purple",
    origin: "Uruguay",
    shape: "Round",
    cut: "Faceted",
    carat: 1.2,
    dimensions: "6mm diameter",
    clarity: "Transparent",
    treatment: "None",
    hardness: "7 Mohs",
    quantityInStock: 320,
    location: "VN",
    unitCost: 2.80,
    retailPrice: 7.50,
    vendor: "Golden Gems Supply",
    status: "available",
    lastUpdate: "2025-10-28T11:15:00Z",
    imageUrl: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=400",
    healingProperties: "Peace, intuition, spiritual awareness, stress relief, clarity",
    notes: "Premium quality, deep color",
  },
  {
    id: "gem-004",
    sku: "GEM-OBS-10MM-RND",
    name: "Black Obsidian",
    stoneType: "semi-precious",
    variety: "Volcanic Glass",
    color: "Black",
    origin: "Mexico",
    shape: "Round",
    cut: "Smooth Polish",
    carat: 3.5,
    dimensions: "10mm diameter",
    clarity: "Opaque",
    treatment: "None",
    hardness: "5-5.5 Mohs",
    quantityInStock: 420,
    location: "VN",
    unitCost: 1.50,
    retailPrice: 4.50,
    vendor: "Stone Haven Trading",
    status: "available",
    lastUpdate: "2025-10-28T10:45:00Z",
    imageUrl: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400",
    healingProperties: "Protection, grounding, negativity shield, root chakra",
    notes: "Very popular for protection jewelry",
  },
  {
    id: "gem-005",
    sku: "GEM-EMR-5X7-OVL",
    name: "Natural Emerald",
    stoneType: "precious",
    variety: "Beryl - Emerald",
    color: "Vivid Green",
    origin: "Colombia",
    shape: "Oval",
    cut: "Faceted",
    carat: 1.5,
    dimensions: "5 x 7mm",
    clarity: "VS",
    treatment: "Oiled",
    certification: "GIA",
    certificateNumber: "GIA-5567890",
    hardness: "7.5-8 Mohs",
    quantityInStock: 8,
    location: "US",
    unitCost: 450.00,
    retailPrice: 850.00,
    vendor: "Prestige Gemstone Imports",
    status: "available",
    lastUpdate: "2025-10-26T13:20:00Z",
    imageUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400",
    healingProperties: "Abundance, heart chakra, wisdom, growth, harmony",
    notes: "Premium quality, excellent color saturation",
  },
  {
    id: "gem-006",
    sku: "GEM-SAP-6MM-RND",
    name: "Blue Sapphire",
    stoneType: "precious",
    variety: "Corundum - Sapphire",
    color: "Royal Blue",
    origin: "Sri Lanka",
    shape: "Round",
    cut: "Brilliant",
    carat: 1.0,
    dimensions: "6mm diameter",
    clarity: "VVS",
    treatment: "Heated",
    certification: "GIA",
    certificateNumber: "GIA-5567891",
    hardness: "9 Mohs",
    quantityInStock: 5,
    location: "US",
    unitCost: 380.00,
    retailPrice: 720.00,
    vendor: "Prestige Gemstone Imports",
    status: "available",
    lastUpdate: "2025-10-25T09:30:00Z",
    imageUrl: "https://images.unsplash.com/photo-1603561596112-0a132b757442?w=400",
    healingProperties: "Wisdom, royalty, divine favor, mental focus",
    notes: "Ceylon sapphire, excellent clarity",
  },
  {
    id: "gem-007",
    sku: "GEM-RUB-4MM-RND",
    name: "Ruby Round",
    stoneType: "precious",
    variety: "Corundum - Ruby",
    color: "Pigeon Blood Red",
    origin: "Myanmar",
    shape: "Round",
    cut: "Brilliant",
    carat: 0.5,
    dimensions: "4mm diameter",
    clarity: "VS",
    treatment: "Heated",
    certification: "GIA",
    certificateNumber: "GIA-5567892",
    hardness: "9 Mohs",
    quantityInStock: 3,
    location: "US",
    unitCost: 520.00,
    retailPrice: 980.00,
    vendor: "Prestige Gemstone Imports",
    status: "reserved",
    lastUpdate: "2025-10-28T15:00:00Z",
    imageUrl: "https://images.unsplash.com/photo-1603561596112-0a132b757442?w=400",
    healingProperties: "Passion, vitality, courage, life force",
    notes: "Reserved for custom ring order",
  },
  {
    id: "gem-008",
    sku: "GEM-MOON-8MM-OVL",
    name: "Rainbow Moonstone",
    stoneType: "semi-precious",
    variety: "Feldspar - Moonstone",
    color: "White with Blue Flash",
    origin: "India",
    shape: "Oval",
    cut: "Cabochon",
    carat: 3.0,
    dimensions: "8 x 6mm",
    clarity: "Translucent",
    treatment: "None",
    hardness: "6-6.5 Mohs",
    quantityInStock: 145,
    location: "VN",
    unitCost: 5.50,
    retailPrice: 15.00,
    vendor: "Mystic Moon Traders",
    status: "available",
    lastUpdate: "2025-10-27T16:45:00Z",
    imageUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400",
    healingProperties: "Intuition, femininity, new beginnings, emotional balance",
    notes: "Strong blue adularescence",
  },
  {
    id: "gem-009",
    sku: "GEM-LAB-8MM-RND",
    name: "Labradorite Round",
    stoneType: "semi-precious",
    variety: "Feldspar - Labradorite",
    color: "Gray with Aurora Flash",
    origin: "Madagascar",
    shape: "Round",
    cut: "Cabochon",
    carat: 2.8,
    dimensions: "8mm diameter",
    clarity: "Translucent",
    treatment: "None",
    hardness: "6-6.5 Mohs",
    quantityInStock: 220,
    location: "VN",
    unitCost: 3.20,
    retailPrice: 9.50,
    vendor: "Mystic Moon Traders",
    status: "available",
    lastUpdate: "2025-10-28T12:30:00Z",
    imageUrl: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400",
    healingProperties: "Transformation, magic, protection, psychic abilities",
    notes: "Excellent play of color, mystical appeal",
  },
  {
    id: "gem-010",
    sku: "GEM-TUR-6MM-RND",
    name: "Black Tourmaline",
    stoneType: "semi-precious",
    variety: "Tourmaline - Schorl",
    color: "Deep Black",
    origin: "Brazil",
    shape: "Round",
    cut: "Smooth Polish",
    carat: 1.8,
    dimensions: "6mm diameter",
    clarity: "Opaque",
    treatment: "None",
    hardness: "7-7.5 Mohs",
    quantityInStock: 380,
    location: "VN",
    unitCost: 2.20,
    retailPrice: 6.50,
    vendor: "Stone Haven Trading",
    status: "available",
    lastUpdate: "2025-10-28T08:15:00Z",
    imageUrl: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400",
    healingProperties: "EMF protection, grounding, purification, security",
    notes: "Popular for tech protection jewelry",
  },
  {
    id: "gem-011",
    sku: "GEM-AQU-10MM-EMR",
    name: "Aquamarine Emerald Cut",
    stoneType: "semi-precious",
    variety: "Beryl - Aquamarine",
    color: "Sky Blue",
    origin: "Brazil",
    shape: "Emerald",
    cut: "Step Cut",
    carat: 4.5,
    dimensions: "10 x 8mm",
    clarity: "VS",
    treatment: "Heated",
    hardness: "7.5-8 Mohs",
    quantityInStock: 12,
    location: "US",
    unitCost: 85.00,
    retailPrice: 195.00,
    vendor: "Prestige Gemstone Imports",
    status: "available",
    lastUpdate: "2025-10-27T10:00:00Z",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400",
    healingProperties: "Calming, communication, courage, clarity",
    notes: "Beautiful sea-blue color, great for pendants",
  },
  {
    id: "gem-012",
    sku: "GEM-PER-12MM-RND",
    name: "Freshwater Pearl",
    stoneType: "precious",
    variety: "Cultured Pearl",
    color: "White Cream",
    origin: "China",
    shape: "Round",
    cut: "Natural",
    carat: 5.0,
    dimensions: "12mm diameter",
    clarity: "AAA Grade",
    treatment: "None",
    hardness: "2.5-4.5 Mohs",
    quantityInStock: 95,
    location: "VN",
    unitCost: 18.00,
    retailPrice: 45.00,
    vendor: "Pearl Paradise Suppliers",
    status: "available",
    lastUpdate: "2025-10-28T13:45:00Z",
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400",
    healingProperties: "Purity, innocence, integrity, wisdom, focus",
    notes: "Near-perfect round shape, high luster",
  },
];
