export interface Material {
  id: string;
  sku: string;
  name: string;
  category: "metal" | "stone" | "charm" | "component" | "packaging";
  type: string;
  color?: string;
  size?: string;
  unit: string;
  quantityInStock: number;
  reorderLevel: number;
  unitCost: number;
  vendor: string;
  lastOrderDate?: string;
  status: "in_stock" | "low_stock" | "out_of_stock";
  location: "VN" | "US";
}

export const mockMaterials: Material[] = [
  {
    id: "1",
    sku: "MAT-CIT-8MM",
    name: "Citrine Beads 8mm",
    category: "stone",
    type: "Natural Citrine",
    color: "Golden Yellow",
    size: "8mm",
    unit: "piece",
    quantityInStock: 2450,
    reorderLevel: 500,
    unitCost: 0.85,
    vendor: "Golden Gems Supply",
    lastOrderDate: "2025-09-15",
    status: "in_stock",
    location: "VN",
  },
  {
    id: "2",
    sku: "MAT-RQ-6MM",
    name: "Rose Quartz Beads 6mm",
    category: "stone",
    type: "Natural Rose Quartz",
    color: "Pink",
    size: "6mm",
    unit: "piece",
    quantityInStock: 1850,
    reorderLevel: 500,
    unitCost: 0.65,
    vendor: "Golden Gems Supply",
    lastOrderDate: "2025-09-20",
    status: "in_stock",
    location: "VN",
  },
  {
    id: "3",
    sku: "MAT-GLD-18K",
    name: "18K Gold Plated Wire",
    category: "metal",
    type: "Gold Plated",
    color: "Gold",
    unit: "meter",
    quantityInStock: 450,
    reorderLevel: 100,
    unitCost: 3.50,
    vendor: "Silver Star Materials",
    lastOrderDate: "2025-09-10",
    status: "in_stock",
    location: "VN",
  },
  {
    id: "4",
    sku: "MAT-SLV-925",
    name: "Sterling Silver 925 Wire",
    category: "metal",
    type: "Sterling Silver",
    color: "Silver",
    unit: "meter",
    quantityInStock: 380,
    reorderLevel: 100,
    unitCost: 2.80,
    vendor: "Silver Star Materials",
    lastOrderDate: "2025-09-12",
    status: "in_stock",
    location: "VN",
  },
  {
    id: "5",
    sku: "MAT-CHM-LOT",
    name: "Lotus Charm Gold",
    category: "charm",
    type: "Symbolic Charm",
    color: "Gold",
    size: "12mm",
    unit: "piece",
    quantityInStock: 156,
    reorderLevel: 50,
    unitCost: 1.20,
    vendor: "Jade Masters Workshop",
    lastOrderDate: "2025-08-25",
    status: "in_stock",
    location: "VN",
  },
  {
    id: "6",
    sku: "MAT-CHM-MOON",
    name: "Moon Charm Silver",
    category: "charm",
    type: "Symbolic Charm",
    color: "Silver",
    size: "15mm",
    unit: "piece",
    quantityInStock: 89,
    reorderLevel: 50,
    unitCost: 0.95,
    vendor: "Jade Masters Workshop",
    lastOrderDate: "2025-08-30",
    status: "in_stock",
    location: "VN",
  },
  {
    id: "7",
    sku: "MAT-OBS-10MM",
    name: "Black Obsidian Beads 10mm",
    category: "stone",
    type: "Natural Obsidian",
    color: "Black",
    size: "10mm",
    unit: "piece",
    quantityInStock: 320,
    reorderLevel: 500,
    unitCost: 0.75,
    vendor: "Golden Gems Supply",
    lastOrderDate: "2025-09-18",
    status: "low_stock",
    location: "VN",
  },
  {
    id: "8",
    sku: "MAT-PKG-POUCH",
    name: "Velvet Jewelry Pouch",
    category: "packaging",
    type: "Pouch",
    color: "Black",
    size: "Small",
    unit: "piece",
    quantityInStock: 850,
    reorderLevel: 200,
    unitCost: 0.45,
    vendor: "Premium Pack Solutions",
    lastOrderDate: "2025-09-05",
    status: "in_stock",
    location: "US",
  },
  {
    id: "9",
    sku: "MAT-PKG-BOX",
    name: "Gift Box Premium",
    category: "packaging",
    type: "Box",
    color: "White",
    size: "Medium",
    unit: "piece",
    quantityInStock: 425,
    reorderLevel: 150,
    unitCost: 1.25,
    vendor: "Premium Pack Solutions",
    lastOrderDate: "2025-09-08",
    status: "in_stock",
    location: "US",
  },
  {
    id: "10",
    sku: "MAT-COMP-CLASP",
    name: "Lobster Clasp Gold",
    category: "component",
    type: "Clasp",
    color: "Gold",
    size: "10mm",
    unit: "piece",
    quantityInStock: 1200,
    reorderLevel: 300,
    unitCost: 0.15,
    vendor: "Silver Star Materials",
    lastOrderDate: "2025-09-15",
    status: "in_stock",
    location: "VN",
  },
];
