import { OrderData } from "../types/modules/crm";

// List of available sale reps for dropdown selection
export const SALE_REPS = [
  "Hang Tran",
  "Ngoc Vo",
  "Hai Lam",
  "Hoang My",
  "Laura Sale",
  "Michael Chen",
  "Sarah Park",
  "David Kim",
  "Jennifer Lee",
  "Alex Johnson"
];

export const mockOrderBoardData: OrderData[] = [
  {
    id: "1",
    orderNumber: "666021905",
    amount: 200,
    saleRepConverted: "Hang Tran",
    customerName: "Ha Tu Tran",
    customerRank: "VIP",
    saleRepMain: "Hang Tran",
    createdDate: "Oct 11, 2025",
    createdTime: "",
    orderStatus: "Processing",
    orderType: "regular",
    customerNote: "Please add gift wrapping and include a thank you card.",
    alerts: {
      customerNote: true,
    },
    followUp: {
      tagColor: "#F59E0B",
      status: "Follow up Processing",
      approvalStatus: "Pending Admin Review",
    },
    statusProcess: {
      group: "US1101-01",
      currentStatus: "Assigned Batch",
    },
    fulfillmentType: "Store Pickup",
    tracking: [],
    customerService: {
      feedback: "Great service, fast response!",
      csatStatus: "Love It",
    },
    shippingAddress: {
      street: "123 Main Street, Apt 4B",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
    },
    shippingMethod: "standard",
    totalItems: 2,
    lineItems: [
      {
        id: "line-001",
        productId: "prod-001",
        sku: "JW-GLD-001",
        name: "Golden Lotus Bracelet",
        quantity: 2,
        price: 79.99,
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=200",
        warehouseLocation: "A-12-3",
      },
    ],
    tags: ["signature"],
  },
  {
    id: "2",
    orderNumber: "666021904",
    amount: 350,
    paidAmount: 100,
    dueAmount: 250,
    saleRepConverted: "Ngoc Vo",
    customerName: "Duy Vo",
    customerRank: "VVIP",
    saleRepMain: "Ngoc Vo",
    createdDate: "Oct 11, 2025",
    createdTime: "",
    orderStatus: "Partial Payment",
    orderType: "pre-order",
    customerNote: "Will provide shipping address once item arrives. Please keep me updated weekly on the pre-order status.",
    alerts: {
      imageMissing: true,
      addressMissing: true,
    },
    followUp: {
      tagColor: "#EF4444",
      status: "Keep customer updated",
      approvalStatus: "Under Review",
    },
    statusProcess: {
      group: "Pre Ordered",
      currentStatus: "Incoming",
    },
    tracking: [
      {
        trackingNumber: "1Z999AA10123456799",
        carrier: "UPS",
        dateShipped: "Oct 11, 2025",
        status: "Processing",
      },
      {
        trackingNumber: "1Z999AA10123456800",
        carrier: "UPS",
        dateShipped: "Oct 11, 2025",
        status: "Label Created",
      },
    ],
    customerService: {
      socialReview: {
        platform: "Instagram",
        rating: 5,
        comment: "Beautiful jewelry! Highly recommend!",
      },
      reviewSources: ["Google", "Yelp"],
      csatStatus: "Neutral",
    },
    preOrderDetails: {
      reasonStatus: "Out of Stock",
      productType: "Jewelry",
      preorderStatus: "US Processing",
      vendor: "Golden Gems Supply",
      updatedBy: "Ngoc Vo",
      updatedDate: "Oct 09 2025",
      estDate: "Nov 15 2025",
    },
    shippingMethod: "express",
    totalItems: 1,
    lineItems: [
      {
        id: "line-002",
        productId: "prod-002",
        sku: "JW-SLV-002",
        name: "Moonlight Pearl Necklace",
        quantity: 1,
        price: 149.99,
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=200",
        warehouseLocation: "A-12-3",
      },
    ],
    tags: ["rush", "insurance"],
  },
  {
    id: "3",
    orderNumber: "555005163A",
    amount: 340,
    saleRepConverted: "Hai Lam",
    customerName: "Hai Lam",
    customerRank: "VIP",
    saleRepMain: "Hai Lam",
    createdDate: "Oct 11, 2025",
    createdTime: "",
    orderStatus: "Completed",
    orderType: "customize",
    customerNote: "Loving the custom design! Can't wait to receive it. Thank you for the great service!",
    alerts: {
      linkedOrders: true,
    },
    followUp: {
      tagColor: "#10B981",
      status: "Send Tracking",
      approvalStatus: "Excellent",
    },
    statusProcess: {
      group: "Customize",
      currentStatus: "Production Start",
    },
    tracking: [
      {
        trackingNumber: "1Z999AA10123456784",
        carrier: "UPS",
        dateShipped: "Oct 11, 2025",
        status: "In Transit",
      },
    ],
    customerService: {
      feedback: "Package arrived on time, very satisfied!",
      socialReview: {
        platform: "Facebook",
        rating: 5,
        comment: "Amazing quality and fast shipping!",
      },
      reviewSources: ["Facebook", "UGC"],
      csatStatus: "Love It",
    },
    customizeDetails: {
      design3DStatus: "Approved",
      materialStatus: "In Stock",
      productCompleteStatus: "Completed",
    },
    shippingAddress: {
      street: "456 Oak Avenue",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      country: "USA",
    },
    shippingMethod: "express",
    totalItems: 2,
    lineItems: [
      {
        id: "line-003",
        productId: "prod-002",
        sku: "JW-SLV-002",
        name: "Moonlight Pearl Necklace",
        quantity: 1,
        price: 149.99,
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=200",
        warehouseLocation: "B-05-7",
      },
      {
        id: "line-003b",
        productId: "prod-003",
        sku: "JW-RG-003",
        name: "Rose Quartz Ring",
        quantity: 1,
        price: 129.99,
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=200",
        warehouseLocation: "C-08-2",
      },
    ],
    tags: ["fragile"],
  },
  {
    id: "4",
    orderNumber: "555005163S",
    amount: 325,
    paidAmount: 325,
    dueAmount: 0,
    paymentBreakdown: [
      {
        orderNumber: "555005163S-1",
        amount: 150,
        paidAmount: 150,
        dueAmount: 0,
      },
      {
        orderNumber: "555005163S-2",
        amount: 175,
        paidAmount: 175,
        dueAmount: 0,
      },
    ],
    saleRepConverted: "Hoang My",
    customerName: "Tuyet Le",
    customerRank: "Repeat",
    saleRepMain: "Hoang My",
    createdDate: "Oct 3, 2025",
    createdTime: "",
    orderStatus: "Shipped",
    orderType: "regular",
    customerNote: "Order is delayed. Not happy with the wait time. Expected faster delivery.",
    alerts: {
      late: 7,
      imageMissing: true,
    },
    followUp: {
      tagColor: "#EF4444",
      status: "Ask for feedback",
      approvalStatus: "Bad",
    },
    tracking: [
      {
        trackingNumber: "9405511899562017530421",
        carrier: "USPS",
        dateShipped: "Oct 3, 2025",
        status: "Delivered",
      },
      {
        trackingNumber: "9405511899562017530499",
        carrier: "USPS",
        dateShipped: "Oct 4, 2025",
        status: "In Transit",
      },
    ],
    customerService: {
      csatStatus: "Not Satisfied",
    },
    shippingAddress: {
      street: "789 Pine Road, Suite 200",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
      country: "USA",
    },
    shippingMethod: "economy",
    totalItems: 1,
    lineItems: [
      {
        id: "line-004",
        productId: "prod-004",
        sku: "JW-DIA-004",
        name: "Diamond Eternity Band",
        quantity: 1,
        price: 325.00,
        image: "https://images.unsplash.com/photo-1611652022419-a9419f74343a?w=200",
        warehouseLocation: "D-15-1",
      },
    ],
    tags: ["gift"],
  },
  {
    id: "5",
    orderNumber: "555005163Z",
    amount: 425,
    saleRepConverted: "Laura Sale",
    customerName: "Arabella Vu",
    customerRank: "VVIP",
    saleRepMain: "Laura Sale",
    createdDate: "Oct 10, 2025",
    createdTime: "",
    orderStatus: "Delivered",
    orderType: "regular",
    customerNote: "Please add custom engraving 'Forever Yours - A.V.' on the back. Confirm before finalizing!",
    alerts: {
      customerNote: true,
      linkedOrders: true,
    },
    followUp: {
      tagColor: "#8B5CF6",
      status: "Suggest cross sale",
      approvalStatus: "Qualified",
    },
    tracking: [
      {
        trackingNumber: "1Z999AA10123456785",
        carrier: "UPS",
        dateShipped: "Oct 10, 2025",
        status: "Out for Delivery",
      },
    ],
    customerService: {
      feedback: "Waiting for confirmation on custom engraving.",
      reviewSources: ["Yelp"],
      csatStatus: "No Respond",
    },
    shippingAddress: {
      street: "2341 Sunset Boulevard",
      city: "San Francisco",
      state: "CA",
      zipCode: "94103",
      country: "USA",
    },
    shippingMethod: "express",
    totalItems: 1,
    lineItems: [
      {
        id: "line-005",
        productId: "prod-005",
        sku: "JW-SAP-005",
        name: "Sapphire Pendant",
        quantity: 1,
        price: 425.00,
        image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=200",
        warehouseLocation: "E-20-5",
      },
    ],
  },
  {
    id: "6",
    orderNumber: "555005164A",
    amount: 280,
    saleRepConverted: "Michael Chen",
    customerName: "Lisa Nguyen",
    customerRank: "New",
    saleRepMain: "Michael Chen",
    createdDate: "Oct 10, 2025",
    createdTime: "",
    orderStatus: "Refunded",
    orderType: "return-warranty",
    customerNote: "The color doesn't match the photo on the website. Requesting a full refund.",
    alerts: {
      customerNote: true,
      addressMissing: true,
      late: 3,
      refundRequest: true,
    },
    followUp: {
      tagColor: "#EF4444",
      status: "Need win back",
      approvalStatus: "Bad",
    },
    tracking: [
      {
        trackingNumber: "TRK-987654321",
        carrier: "FedEx",
        dateShipped: "Oct 10, 2025",
        status: "Out for Delivery",
      },
      {
        trackingNumber: "TRK-987654322",
        carrier: "FedEx",
        dateShipped: "Oct 9, 2025",
        status: "Delivered",
      },
    ],
    customerService: {
      csatStatus: "Complain",
    },
    returnWarrantyDetails: {
      returnType: "Return",
      receivedDate: "Oct 12, 2025",
      shippingStatus: "Received",
      refundStatus: "Pending",
      note: "Customer not satisfied with color",
    },
    shippingAddress: {
      street: "1567 Market Street",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
      country: "USA",
    },
    shippingMethod: "standard",
    totalItems: 1,
    lineItems: [
      {
        id: "line-006",
        productId: "prod-006",
        sku: "JW-EME-006",
        name: "Emerald Drop Earrings",
        quantity: 1,
        price: 280.00,
        image: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=200",
        warehouseLocation: "F-11-8",
      },
    ],
  },
  {
    id: "7",
    orderNumber: "555005165B",
    amount: 520,
    paidAmount: 200,
    dueAmount: 320,
    paymentBreakdown: [
      {
        orderNumber: "555005165B-1",
        amount: 280,
        paidAmount: 100,
        dueAmount: 180,
      },
      {
        orderNumber: "555005165B-2",
        amount: 240,
        paidAmount: 100,
        dueAmount: 140,
      },
    ],
    saleRepConverted: "Sarah Park",
    customerName: "Emma Wilson",
    customerRank: "VVIP",
    saleRepMain: "Sarah Park",
    createdDate: "Oct 9, 2025",
    createdTime: "",
    orderStatus: "Completed",
    orderType: "regular",
    customerNote: "Absolutely love your service! The quality is amazing. Will definitely order again!",
    alerts: {},
    followUp: {
      tagColor: "#10B981",
      status: "Send Tracking",
      approvalStatus: "Excellent",
    },
    tracking: [
      {
        trackingNumber: "DHL-456789123",
        carrier: "DHL",
        dateShipped: "Oct 9, 2025",
        status: "Delivered",
      },
    ],
    customerService: {
      feedback: "Excellent service! Will order again.",
      socialReview: {
        platform: "Instagram",
        rating: 5,
        comment: "Absolutely stunning! Worth every penny!",
      },
      reviewSources: ["Facebook", "Google", "UGC"],
      csatStatus: "Love It",
    },
    shippingAddress: {
      street: "890 Broadway Avenue, Unit 12",
      city: "Boston",
      state: "MA",
      zipCode: "02101",
      country: "USA",
    },
    shippingMethod: "overnight",
    totalItems: 1,
    lineItems: [
      {
        id: "line-007",
        productId: "prod-007",
        sku: "JW-RUB-007",
        name: "Ruby Tennis Bracelet",
        quantity: 1,
        price: 520.00,
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=200",
        warehouseLocation: "G-03-4",
      },
    ],
  },
  {
    id: "8",
    orderNumber: "555005166C",
    amount: 195,
    saleRepConverted: "David Kim",
    customerName: "Sophie Chen",
    customerRank: "Repeat",
    saleRepMain: "David Kim",
    createdDate: "Oct 9, 2025",
    createdTime: "",
    orderStatus: "Processing",
    orderType: "regular",
    customerNote: "This is a service order for repair. Please handle with care and update me on the status.",
    alerts: {
      imageMissing: true,
      serviceRequest: true,
    },
    followUp: {
      tagColor: "#F59E0B",
      status: "Follow up Processing",
      approvalStatus: "Pending Admin Review",
    },
    statusProcess: {
      group: "US1102-01",
      currentStatus: "Warehouse Received",
    },
    fulfillmentType: "Manual Mark Shipped",
    tracking: [],
    customerService: {},
    shippingAddress: {
      street: "3421 Elm Street",
      city: "Portland",
      state: "OR",
      zipCode: "97201",
      country: "USA",
    },
    shippingMethod: "standard",
    totalItems: 1,
    lineItems: [
      {
        id: "line-008",
        productId: "prod-008",
        sku: "JW-TOP-008",
        name: "Topaz Cocktail Ring",
        quantity: 1,
        price: 195.00,
        image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=200",
        warehouseLocation: "H-09-2",
      },
    ],
  },
  {
    id: "9",
    orderNumber: "555005167D",
    amount: 700,
    paidAmount: 200,
    dueAmount: 0,
    paymentBreakdown: [
      {
        orderNumber: "555005167D-1",
        amount: 700,
        paidAmount: 300,
        dueAmount: 400,
      },
      {
        orderNumber: "555005167D-2",
        amount: 400,
        paidAmount: 200,
        dueAmount: 200,
      },
    ],
    saleRepConverted: "Jennifer Lee",
    customerName: "Victoria Smith",
    customerRank: "VVIP",
    saleRepMain: "Jennifer Lee",
    createdDate: "Oct 8, 2025",
    createdTime: "",
    orderStatus: "Shipped",
    orderType: "regular",
    customerNote: "Please send me tracking updates. I need this to arrive before Oct 15th for an event.",
    alerts: {
      linkedOrders: true,
    },
    followUp: {
      tagColor: "#3B82F6",
      status: "Keep customer updated",
      approvalStatus: "Approved",
    },
    statusProcess: {
      group: "Regular",
      currentStatus: "Warehouse Transfer",
    },
    tracking: [
      {
        trackingNumber: "1Z999AA10123456786",
        carrier: "UPS",
        dateShipped: "Oct 8, 2025",
        status: "In Transit",
      },
      {
        trackingNumber: "1Z999AA10123456787",
        carrier: "UPS",
        dateShipped: "Oct 8, 2025",
        status: "In Transit",
      },
    ],
    customerService: {
      socialReview: {
        platform: "Facebook",
        rating: 5,
        comment: "Best online shopping experience!",
      },
      reviewSources: ["Facebook", "Yelp", "UGC"],
      csatStatus: "Love It",
    },
    shippingAddress: {
      street: "4567 Park Avenue",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      country: "USA",
    },
    shippingMethod: "express",
    totalItems: 2,
    lineItems: [
      {
        id: "line-009",
        productId: "prod-009",
        sku: "JW-AME-009",
        name: "Amethyst Statement Necklace",
        quantity: 2,
        price: 350.00,
        image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=200",
        warehouseLocation: "I-14-6",
      },
    ],
  },
  {
    id: "10",
    orderNumber: "555005168E",
    amount: 310,
    saleRepConverted: "Alex Johnson",
    customerName: "Rachel Brown",
    customerRank: "VIP",
    saleRepMain: "Alex Johnson",
    createdDate: "Oct 5, 2025",
    createdTime: "",
    orderStatus: "Processing",
    orderType: "regular",
    customerNote: "Need custom sizing - ring size 6.5. Please confirm before shipping. Thank you!",
    alerts: {
      customerNote: true,
      imageMissing: true,
      addressMissing: true,
      linkedOrders: true,
      late: 4,
    },
    followUp: {
      tagColor: "#EF4444",
      status: "Follow up Processing",
      approvalStatus: "Pending Admin Review",
    },
    tracking: [
      {
        trackingNumber: "9405511899562017530422",
        carrier: "USPS",
        dateShipped: "Oct 5, 2025",
        status: "Processing",
      },
      {
        trackingNumber: "9405511899562017530423",
        carrier: "USPS",
        dateShipped: "Oct 6, 2025",
        status: "Label Created",
      },
    ],
    customerService: {
      feedback: "Requested custom sizing, waiting for confirmation.",
      reviewSources: ["UGC"],
      csatStatus: "No Respond",
    },
    statusProcess: {
      group: "US1102-02",
      currentStatus: "Ready to Ship",
    },
    shippingMethod: "standard",
    totalItems: 1,
    lineItems: [
      {
        id: "line-010",
        productId: "prod-010",
        sku: "JW-PRL-010",
        name: "Pearl Cluster Earrings",
        quantity: 1,
        price: 310.00,
        image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=200",
        warehouseLocation: "J-07-3",
      },
    ],
  },
  // Additional Pre-Order examples
  {
    id: "11",
    orderNumber: "555005156B",
    amount: 360,
    saleRepConverted: "Hang Tran",
    customerName: "John Smith",
    customerRank: "VIP",
    saleRepMain: "Hang Tran",
    createdDate: "Oct 08 2025",
    createdTime: "",
    orderStatus: "Processing",
    orderType: "pre-order",
    customerNote: "Excited for the pre-order! Please keep me updated on the arrival date.",
    alerts: {
      customerNote: true,
    },
    followUp: {
      tagColor: "#F59E0B",
      status: "Follow up Processing",
      approvalStatus: "Pending Admin Review",
    },
    statusProcess: {
      group: "Pre Ordered",
      currentStatus: "Incoming",
    },
    fulfillmentType: "Tracking",
    tracking: [
      {
        trackingNumber: "1Z999AA10123456784",
        carrier: "UPS",
        dateShipped: "Oct 10 2025",
        status: "In Transit"
      }
    ],
    customerService: {},
    preOrderDetails: {
      reasonStatus: "Pre Order",
      productType: "Jewelry",
      preorderStatus: "US Processing",
      vendor: "Golden Gems Supply",
      updatedBy: "Hang Tran",
      updatedDate: "Oct 09 2025",
      estDate: "Nov 15 2025",
    },
    shippingAddress: {
      street: "5678 Washington Street",
      city: "Denver",
      state: "CO",
      zipCode: "80201",
      country: "USA",
    },
    shippingMethod: "express",
    totalItems: 1,
    lineItems: [
      {
        id: "line-011",
        productId: "prod-011",
        sku: "JW-GAR-011",
        name: "Garnet Pendant Necklace",
        quantity: 1,
        price: 360.00,
        image: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=200",
        warehouseLocation: "K-18-9",
      },
    ],
  },
  // Additional Customize Order
  {
    id: "12",
    orderNumber: "555005170F",
    amount: 890,
    saleRepConverted: "Sarah Park",
    customerName: "Maria Garcia",
    customerRank: "VVIP",
    saleRepMain: "Sarah Park",
    createdDate: "Oct 07 2025",
    createdTime: "",
    orderStatus: "Processing",
    orderType: "customize",
    alerts: {
      linkedOrders: true,
    },
    followUp: {
      tagColor: "#8B5CF6",
      status: "Follow up Processing",
      approvalStatus: "Under Review",
    },
    statusProcess: {
      group: "Customize",
      currentStatus: "Design Approval",
    },
    tracking: [],
    customerService: {
      feedback: "Excited to see the custom design!",
      csatStatus: "No Respond",
    },
    customizeDetails: {
      design3DStatus: "Pending Review",
      materialStatus: "Ordered",
      productCompleteStatus: "Not Started",
    },
    shippingAddress: {
      street: "7890 Vine Street",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
      country: "USA",
    },
    shippingMethod: "overnight",
    totalItems: 1,
    lineItems: [
      {
        id: "line-012",
        productId: "prod-012",
        sku: "JW-CUS-012",
        name: "Custom Diamond Ring",
        quantity: 1,
        price: 890.00,
        image: "https://images.unsplash.com/photo-1611652022419-a9419f74343a?w=200",
        warehouseLocation: "L-22-1",
      },
    ],
  },
  // Additional Return & Warranty
  {
    id: "13",
    orderNumber: "555005171G",
    amount: 250,
    saleRepConverted: "Michael Chen",
    customerName: "Robert Johnson",
    customerRank: "Repeat",
    saleRepMain: "Michael Chen",
    createdDate: "Oct 06 2025",
    createdTime: "",
    orderStatus: "Refunded",
    orderType: "return-warranty",
    alerts: {
      refundRequest: true,
    },
    followUp: {
      tagColor: "#EF4444",
      status: "Need win back",
      approvalStatus: "Bad",
    },
    tracking: [],
    customerService: {
      csatStatus: "Not Satisfied",
    },
    returnWarrantyDetails: {
      returnType: "Warranty",
      receivedDate: "Oct 08 2025",
      shippingStatus: "Processing",
      refundStatus: "Completed",
      note: "Product defect - clasp broken",
    },
    shippingAddress: {
      street: "9012 Cedar Lane",
      city: "Philadelphia",
      state: "PA",
      zipCode: "19101",
      country: "USA",
    },
    shippingMethod: "standard",
    totalItems: 1,
    lineItems: [
      {
        id: "line-013",
        productId: "prod-001",
        sku: "JW-GLD-001",
        name: "Golden Lotus Bracelet",
        quantity: 1,
        price: 250.00,
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=200",
        warehouseLocation: "M-12-5",
      },
    ],
  },
  // Additional Customize Orders
  {
    id: "14",
    orderNumber: "666021909B",
    amount: 1250,
    saleRepConverted: "Le My Nguyen",
    customerName: "Sophie Martinez",
    customerRank: "VVIP",
    saleRepMain: "Le My Nguyen",
    createdDate: "Oct 09 2025",
    createdTime: "",
    orderStatus: "Processing",
    orderType: "customize",
    alerts: {
      linkedOrders: true,
    },
    followUp: {
      tagColor: "#8B5CF6",
      status: "Follow up Processing",
      approvalStatus: "Under Review",
    },
    statusProcess: {
      group: "Customize",
      currentStatus: "Production Start",
    },
    tracking: [],
    customerService: {
      feedback: "Looking forward to the custom piece!",
      csatStatus: "No Respond",
    },
    customizeDetails: {
      design3DStatus: "Approved",
      materialStatus: "Received",
      productCompleteStatus: "In Progress",
    },
    shippingAddress: {
      street: "2345 Custom Avenue",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      country: "USA",
    },
    shippingMethod: "express",
    totalItems: 1,
    lineItems: [
      {
        id: "line-014",
        productId: "prod-014",
        sku: "JW-CUS-014",
        name: "Platinum Custom Engagement Ring",
        quantity: 1,
        price: 1250.00,
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=200",
        warehouseLocation: "N-05-3",
      },
    ],
  },
  {
    id: "15",
    orderNumber: "555005155B",
    amount: 360,
    saleRepConverted: "Hang Tran",
    customerName: "Kim Vo",
    customerRank: "VIP",
    saleRepMain: "Hang Tran",
    createdDate: "Oct 08 2025",
    createdTime: "",
    orderStatus: "Processing",
    orderType: "return-warranty",
    alerts: {},
    followUp: {
      tagColor: "#F59E0B",
      status: "Follow up Processing",
      approvalStatus: "Under Review",
    },
    tracking: [
      {
        trackingNumber: "1Z999AA10123456789",
        carrier: "UPS",
        dateShipped: "Oct 09 2025",
        status: "In Transit",
      },
    ],
    customerService: {
      csatStatus: "Neutral",
    },
    returnWarrantyDetails: {
      returnType: "Warranty",
      receivedDate: "Oct 10 2025",
      shippingStatus: "In Transit",
      refundStatus: "N/A",
      note: "Warranty Claim",
    },
    shippingAddress: {
      street: "1122 Warranty Road",
      city: "Houston",
      state: "TX",
      zipCode: "77001",
      country: "USA",
    },
    shippingMethod: "standard",
    totalItems: 1,
    lineItems: [
      {
        id: "line-015",
        productId: "prod-015",
        sku: "JW-BRC-015",
        name: "Silver Chain Bracelet",
        quantity: 1,
        price: 360.00,
        image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=200",
        warehouseLocation: "O-11-2",
      },
    ],
  },
  {
    id: "16",
    orderNumber: "555005154T",
    amount: 699.99,
    saleRepConverted: "Chuyet Vo",
    customerName: "Samson Pham",
    customerRank: "New",
    saleRepMain: "Chuyet Vo",
    createdDate: "Oct 08 2025",
    createdTime: "",
    orderStatus: "Completed",
    orderType: "return-warranty",
    alerts: {},
    followUp: {
      tagColor: "#10B981",
      status: "Exchange Completed",
      approvalStatus: "Excellent",
    },
    tracking: [
      {
        trackingNumber: "9400123456789012345679",
        carrier: "USPS",
        dateShipped: "Oct 10 2025",
        status: "Delivered",
      },
    ],
    customerService: {
      csatStatus: "Love It",
    },
    returnWarrantyDetails: {
      returnType: "Return",
      receivedDate: "Oct 12 2025",
      shippingStatus: "Received",
      refundStatus: "Processed",
      note: "Size Issue",
    },
    shippingAddress: {
      street: "3344 Exchange Street",
      city: "Atlanta",
      state: "GA",
      zipCode: "30301",
      country: "USA",
    },
    shippingMethod: "express",
    totalItems: 1,
    lineItems: [
      {
        id: "line-016",
        productId: "prod-016",
        sku: "JW-RNG-016",
        name: "White Gold Wedding Band",
        quantity: 1,
        price: 699.99,
        image: "https://images.unsplash.com/photo-1611652022419-a9419f74343a?w=200",
        warehouseLocation: "P-08-1",
      },
    ],
  },
  {
    id: "16b",
    orderNumber: "555005154T-OLD",
    amount: 780,
    saleRepConverted: "Chuyet Vo",
    customerName: "Daniel Park",
    customerRank: "New",
    saleRepMain: "Chuyet Vo",
    createdDate: "Oct 08 2025",
    createdTime: "",
    orderStatus: "Processing",
    orderType: "customize",
    alerts: {
      customerNote: true,
    },
    followUp: {
      tagColor: "#F59E0B",
      status: "Follow up Processing",
      approvalStatus: "Pending Admin Review",
    },
    statusProcess: {
      group: "Customize",
      currentStatus: "Design Approval",
    },
    tracking: [],
    customerService: {},
    customizeDetails: {
      design3DStatus: "In Progress",
      materialStatus: "Partial",
      productCompleteStatus: "Design Approval",
    },
    shippingAddress: {
      street: "5566 Custom Way",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85001",
      country: "USA",
    },
    shippingMethod: "overnight",
    totalItems: 1,
    lineItems: [
      {
        id: "line-016b",
        productId: "prod-016b",
        sku: "JW-CUS-016B",
        name: "Custom Sapphire Ring",
        quantity: 1,
        price: 780.00,
        image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=200",
        warehouseLocation: "Q-14-7",
      },
    ],
  },
  {
    id: "17",
    orderNumber: "666021907B",
    amount: 360,
    saleRepConverted: "Hai Lam",
    customerName: "Ngoc Anh Ng...",
    customerRank: "VVIP",
    saleRepMain: "Hai Lam",
    createdDate: "Oct 09 2025",
    createdTime: "",
    orderStatus: "Processing",
    orderType: "return-warranty",
    alerts: {},
    followUp: {
      tagColor: "#F59E0B",
      status: "Pending Return",
      approvalStatus: "Under Review",
    },
    tracking: [],
    customerService: {
      csatStatus: "Not Satisfied",
    },
    returnWarrantyDetails: {
      returnType: "Return",
      receivedDate: "Oct 12 2025",
      shippingStatus: "Pending",
      refundStatus: "Under Review",
      note: "Color not as expected",
    },
    shippingAddress: {
      street: "7788 Return Boulevard",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      country: "USA",
    },
    shippingMethod: "standard",
    totalItems: 1,
    lineItems: [
      {
        id: "line-017",
        productId: "prod-017",
        sku: "JW-EAR-017",
        name: "Rose Gold Hoop Earrings",
        quantity: 1,
        price: 360.00,
        image: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=200",
        warehouseLocation: "R-09-4",
      },
    ],
    returnWarrantyDetails: {
      returnType: "Return",
      receivedDate: "",
      shippingStatus: "Label Sent",
      refundStatus: "Pending",
      note: "Defective",
    },
  },
  {
    id: "17b",
    orderNumber: "666021907B-OLD",
    amount: 1450,
    saleRepConverted: "Le My Nguyen",
    customerName: "Olivia Thompson",
    customerRank: "VVIP",
    saleRepMain: "Le My Nguyen",
    createdDate: "Oct 09 2025",
    createdTime: "",
    orderStatus: "Processing",
    orderType: "customize",
    alerts: {
      linkedOrders: true,
      customerNote: true,
    },
    followUp: {
      tagColor: "#8B5CF6",
      status: "Keep customer updated",
      approvalStatus: "Approved",
    },
    statusProcess: {
      group: "Customize",
      currentStatus: "Production Start",
    },
    tracking: [],
    customerService: {
      feedback: "Very impressed with the design mockups!",
      csatStatus: "Love It",
    },
    customizeDetails: {
      design3DStatus: "Approved",
      materialStatus: "In Stock",
      productCompleteStatus: "Quality Check",
    },
  },
  {
    id: "18",
    orderNumber: "666021984S",
    amount: 620,
    saleRepConverted: "Hai Lam",
    customerName: "James Wilson",
    customerRank: "Repeat",
    saleRepMain: "Hai Lam",
    createdDate: "Oct 09 2025",
    createdTime: "",
    orderStatus: "Processing",
    orderType: "customize",
    alerts: {
      late: 2,
    },
    followUp: {
      tagColor: "#EF4444",
      status: "Follow up Processing",
      approvalStatus: "Under Review",
    },
    statusProcess: {
      group: "Customize",
      currentStatus: "Design Approval",
    },
    tracking: [],
    customerService: {
      csatStatus: "Neutral",
    },
    customizeDetails: {
      design3DStatus: "Revision Needed",
      materialStatus: "Backordered",
      productCompleteStatus: "Not Started",
    },
  },
];
